#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ORDER N6-Z · Z1 — write _next6/SOW_MATRIX.md from the join and the verdicts."""
import collections
import json
import os
import sys

ORDER = ['BUILD_ASDAN', 'GROW_ASDAN', 'LAUNCH_ASDAN',
         'BUILD_Science', 'GROW_Science', 'LAUNCH_Science',
         'BUILD_Humanities', 'GROW_Humanities', 'LAUNCH_Humanities']
VERDICTS = ['ALIGNED', 'PARTIAL', 'MISALIGNED', 'SURFACE-SPLIT',
            'SOW-SILENT', 'DELIBERATE-DIVERGENCE', 'UNRESOLVED']


def esc(s):
    return (s or '').replace('|', '\\|').replace('\n', ' ').strip()


def main(matrix_path, verdict_path, grid_path, out):
    M = json.load(open(matrix_path))
    G = json.load(open(grid_path))
    V = json.load(open(verdict_path)) if os.path.exists(verdict_path) else {}
    byid = {r['id'] or r['base']: r for r in M}

    L = []
    W = L.append
    W('# ORDER N6-Z · §Z1 — SoW ALIGNMENT MATRIX')
    W('')
    W('`mbm-next-six-weeks-final-2026-08-28-N6Z` · one row per lesson · generated by')
    W('`_next6/tools/z1_write_matrix.py` from the two pack instruments and the three workbooks.')
    W('')
    W('## The instruments, and their SHAs')
    W('')
    W('| lane | workbook | sha256 |')
    W('|---|---|---|')
    for lane in ('BUILD', 'GROW', 'LAUNCH'):
        b = G['books'][lane]
        W('| %s | `%s` | `%s` |' % (lane, b['path'], b['sha256'][:32] + '…'))
    W('')
    W('**BUILD is the vB instrument**, per `_passsb/inputs/README.md` — the Version B')
    W('(FoodWise-only) scheme. `vC-PROPOSED` was **not** used; there is none in the repository.')
    W('')
    W('> **A stale pointer, found on the way in and not fixed here.** All three workbooks were')
    W('> edited at `a946f1ce` ("label Aut1 W1-W2 as baseline weeks in the three SoW workbooks"),')
    W('> which rewrote 8 science rows in the Autumn 1 W1–W2 cells. The files above are the')
    W('> operative, post-edit ones. But `_passsb/inputs/README.md`, `_passsb/FINDINGS.md`,')
    W('> `_passsb/SOW_MATRIX.md`, `_passsl/FINDINGS.md` and `BUILD_ASDAN/…/manifest.json` all')
    W('> still cite the **pre-edit** shas (`730f9a86…`, `05f385ae…`). The edited rows are')
    W('> outside these packs\' range, so no row below is affected — but the pointers are wrong')
    W('> and a later pass reading them will audit against a workbook that is no longer there.')
    W('')
    W('## The population')
    W('')
    W('The order says "one row per lesson across all 192". **192 is the count of HTML *files*')
    W('across twelve packs.** Nine packs are in the repository (159 files); the three Art packs')
    W('(33 files) are not, so §Z4 halted. Of the 159, **132 are lessons** and 27 are support')
    W('surfaces — hubs, front doors, evidence windows, printable resource sheets, the assessor-')
    W('side teacher planning SoW, and the Science practicals matrix. This matrix has **132 rows**.')
    W('')
    W('## How each row was derived — two instruments, no shared code path')
    W('')
    W('| | reads | never reads |')
    W('|---|---|---|')
    W('| **A** | the filename and the pack manifest | the deck |')
    W('| **B** | the rendered deck, every slide activated in turn | the manifest or the filename |')
    W('')
    W('**INSTRUMENT-SPLIT: 0 of 132.** Every row is compared — packs that state a half-term and')
    W('week are compared on that, packs that state a bare estate week on that — and the')
    W('comparator is red-proved on all three deck shapes.')
    W('')
    W('**The join is on what the pack claims, not on a derived week.** A pack naming "Aut2·W1"')
    W('already speaks the workbook\'s units; converting through the disputed calendar shifted')
    W('every ASDAN row by one in a first attempt. Confirmed by a third instrument: BUILD_ASDAN')
    W('prints its own `Exact SOW outcome` and it equals the selected cell **24/24**;')
    W('LAUNCH_ASDAN\'s manifest `sow_topic` matches **27/30**, the three being paraphrases.')
    W('')

    W('## §Z2 — the one-week conflict, which this matrix places but does not settle')
    W('')
    W('Two instruments, both measured:')
    W('')
    W('| | Autumn shape | source |')
    W('|---|---|---|')
    W('| **SoW grid** | Aut1 W1–W7 + Aut2 W1–W7 = **14 weeks** | all three workbooks, read directly; the half-term rows agree (*"Aut 1 · Sep to Oct (7 wks)"*) |')
    W('| **repo calendar** | Aut1 W1–W8 + Aut2 W9–W15 = **15 weeks** | `_passpq/tools/l2k_plan.py` `BLOCKS`; `Planning/*/README.txt`: *"W8 = w/c 19 Oct ← LAST WEEK OF AUT 1"*, *"The LA calendar confirms the 8-week Aut 1"*; `_assert_calendar()` passes |')
    W('')
    W('They disagree by exactly one week, and **the disagreement is estate-wide, not a LAUNCH')
    W('peculiarity** — all three workbooks carry the identical 7/7 autumn. §Z2 rule 1 (the SoW')
    W('governs where its grid is explicit) and rule 2 (the repo calendar governs where the SoW')
    W('is silent) therefore both fire and point opposite ways. That is **rule 3: record both,')
    W('change nothing, put it to Matt.**')
    W('')
    W('**Each ASDAN pack is internally consistent under a *different* reading, in its own manifest:**')
    W('')
    W('| pack | states | consistent only under |')
    W('|---|---|---|')
    W('| BUILD_ASDAN | `"Autumn 2 · Week n"` **and** `continuationWeek` 9–14 | **CALENDAR** (Aut2·W1 = estate W9) |')
    W('| LAUNCH_ASDAN | `pack_week` 7–12 **and** `source_week` Aut1·W7, Aut2·W1–W5 | **SoW** (pack W8 = Aut2·W1, so Aut1 ends at W7) |')
    W('')
    W('Neither pack is wrong on its own terms. **The estate has two conventions in use at once.**')
    W('')
    W('**The cost of each reading**')
    W('')
    W('| | what it costs |')
    W('|---|---|')
    W('| **SoW governs** | every lesson lands on a real SoW cell (132/132). BUILD_ASDAN and GROW_ASDAN re-seat to estate W8–W13; LAUNCH_ASDAN to W7–W12. BUILD_ASDAN\'s own `continuationWeek` then contradicts its own term label. |')
    W('| **calendar governs** | **7 Science lessons land on `Aut1·W8`, a cell the SoW does not have** — the workbook supplies 14 autumn rows for a 15-week autumn. 125/132 map. LAUNCH_ASDAN re-seats to W7–W13. |')
    W('')
    W('**Nothing was relabelled.** No week number, term tag, sequence chip, manifest, checksum or')
    W('nav string was changed for this. It is a named stop condition and it is Matt\'s call.')
    W('')
    W('*The SoW-alignment verdicts below are unaffected by it:* the packs that claim a half-term')
    W('week are joined on that claim, so they select the same workbook cell under either reading.')
    W('')

    # per-pack summary
    W('## Per-pack summary')
    W('')
    W('| pack | lessons | ' + ' | '.join(VERDICTS[:6]) + ' | INSTRUMENT-SPLIT |')
    W('|---|---:|' + '---:|' * 6 + '---:|')
    grand = collections.Counter()
    for p in ORDER:
        rs = [r for r in M if r['pack'] == p]
        c = collections.Counter()
        for r in rs:
            v = V.get(r['id'] or r['base'], {}).get('verdict', 'UNRESOLVED')
            c[v] += 1
            grand[v] += 1
        W('| `%s` | %d | %s | %d |' % (p, len(rs),
          ' | '.join(str(c.get(v, 0)) for v in VERDICTS[:6]),
          sum(1 for r in rs if r['instrumentSplit'])))
    W('| **total** | **%d** | %s | **0** |' % (len(M),
      ' | '.join('**%d**' % grand.get(v, 0) for v in VERDICTS[:6])))
    W('')

    # the rows
    for p in ORDER:
        rs = [r for r in M if r['pack'] == p]
        if not rs:
            continue
        W('## %s — %d lessons' % (p, len(rs)))
        W('')
        W('| pack week | SoW week | SoW strand | SoW outcome | lesson LO / SC | verdict | tier |')
        W('|---|---|---|---|---|---|---|')
        for r in sorted(rs, key=lambda x: (str(x['sowStrand']), x['A_weekManifest'] or 0)):
            s = r['sow_SOW'] or {}
            v = V.get(r['id'] or r['base'], {})
            lo = esc(r['B_objective'] or r['A_objective'])
            sc = r['B_sc'] or []
            locell = lo + (('<br>· ' + '<br>· '.join(esc(x) for x in sc[:3])) if sc else '')
            W('| %s | %s | %s | %s | %s | **%s** | %s |' % (
                esc(r['manifestHtwk'] or ('W%s' % r['A_weekManifest'])),
                esc('%s·W%s' % (s.get('ht'), s.get('week'))) if s else '—',
                esc((r['sowStrand'] or '')[:46]),
                esc((s.get('outcome') or '')[:110]),
                locell[:300],
                v.get('verdict', 'UNRESOLVED'), v.get('tier', '—')))
        W('')
    open(out, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    print('wrote %s — %d rows, verdicts %s' % (out, len(M), dict(grand)))


if __name__ == '__main__':
    main(*sys.argv[1:5])
