/* Find-out-more posters: one static QR per poster, pointing at the poster's own LIVE page.
   Shared by stamp_qr.mjs (--posters / --posters-check) and qr_gate.mjs (--posters /
   --posters-self-test), so the stamper and the reader agree on ONE route rule and ONE region
   shape, while the DECODE stays independent: the gate reads the stamped SVG back with the
   vendored jsQR, never with the encoder.

   Route rule (ORDER LW-4 §2a): find-out-more/<subject>/<pathway>/autumn-2/w0n/POSTER.html
   points at https://madebymatt.uk/Lessons/find-out-more/<subject>/<pathway>/autumn-2/w0n/,
   the page served from index.html beside it. The URL is derived from the poster's own
   repository path, never from the authored {QR:…} text (that names the review-pack layout).

   The code is static inline SVG (one <path>, module units, 4-module quiet zone) so it prints
   with JavaScript off and needs no load. Codes live on posters only, never on the pages. */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const HERE = path.dirname(new URL(import.meta.url).pathname);
export const ROOT = path.resolve(HERE, '..', '..');
export const LTQR = require(path.join(HERE, 'qr_source.js'));

export const TREE = 'find-out-more';
export const ORIGIN = 'https://madebymatt.uk/Lessons/';
const ROUTE = /^find-out-more\/(humanities|science|re)\/(build|grow|launch)\/autumn-2\/w0[1-7]\/POSTER\.html$/;
export const BEGIN_PREFIX = '<!-- MBM-POSTER-QR:BEGIN generated by tools/liveteach/stamp_qr.mjs --posters from tools/liveteach/qr_source.js; url=';
export const END = '<!-- MBM-POSTER-QR:END -->';
export const PLACEHOLDER = /<strong>QR placeholder<\/strong><br>\{QR:[^}]*\}<br>No code stamped yet\./;
const QUIET = 4;

function walk(dir, out) {
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith('_') || e.name.startsWith('.')) continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out); else out.push(path.relative(ROOT, p).split(path.sep).join('/'));
  }
  return out;
}
export function posters(root = ROOT) {
  return walk(path.join(root, TREE), []).map(r => r).filter(r => r.endsWith('/POSTER.html')).sort();
}
export function pages(root = ROOT) {
  return walk(path.join(root, TREE), []).filter(r => r.endsWith('/index.html')).sort();
}
export function liveUrl(rel) {
  if (!ROUTE.test(rel)) throw new Error('not a find-out-more poster route: ' + rel);
  return ORIGIN + rel.replace(/POSTER\.html$/, '');
}
export function svgFor(code, label) {
  const dim = code.size + QUIET * 2;
  let d = '';
  for (let y = 0; y < code.size; y++)
    for (let x = 0; x < code.size; x++)
      if (code.modules[y * code.size + x] === 1) d += 'M' + (x + QUIET) + ' ' + (y + QUIET) + 'h1v1h-1z';
  return '<svg class="qr-code" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ' + dim + ' ' + dim +
    '" width="36mm" height="36mm" shape-rendering="crispEdges" role="img" aria-label="' + label +
    '"><rect width="' + dim + '" height="' + dim + '" fill="#fff"/><path fill="#000" d="' + d + '"/></svg>';
}
export function region(url) {
  const code = LTQR.encode(url);
  const shown = url.replace(/^https:\/\//, '');
  return BEGIN_PREFIX + url + ' -->' + svgFor(code, 'QR code: ' + shown) +
    '<br><span class="qr-url">' + shown + '</span>' + END;
}
/* Returns { url, modules, size } read back from a stamped poster, or null. */
export function readRegion(html) {
  const a = html.indexOf(BEGIN_PREFIX), b = html.indexOf(END);
  if (a === -1 || b === -1 || b < a) return null;
  const body = html.slice(a, b);
  const url = body.slice(BEGIN_PREFIX.length, body.indexOf(' -->'));
  const vb = /viewBox="0 0 (\d+) \1"/.exec(body);
  const dm = /<path fill="#000" d="([^"]*)"/.exec(body);
  if (!vb || !dm) return { url, modules: null, size: 0 };
  const dim = +vb[1], modules = new Uint8Array(dim * dim);
  for (const m of dm[1].matchAll(/M(\d+) (\d+)h1v1h-1z/g)) modules[(+m[2]) * dim + (+m[1])] = 1;
  return { url, modules, size: dim };
}
export function stamp(html, url) {
  const a = html.indexOf(BEGIN_PREFIX), b = html.indexOf(END);
  if (a !== -1 && b !== -1) return html.slice(0, a) + region(url) + html.slice(b + END.length);
  if (!PLACEHOLDER.test(html)) throw new Error('no {QR:…} placeholder and no stamped region');
  return html.replace(PLACEHOLDER, region(url));
}
