/* Stamp tools/liveteach/qr_source.js into the projector and teacher views
   between the MBM-LIVETEACH-QR markers — the same pinned-region pattern as
   the core and the splash. Edit the source, run this; never a stamped copy.

     node tools/liveteach/stamp_qr.mjs            rewrite the stamped regions
     node tools/liveteach/stamp_qr.mjs --check    exit 1 on drift (CI mode)
     node tools/liveteach/stamp_qr.mjs --self-test prove --check can fail */
import fs from 'node:fs';
import path from 'node:path';

const HERE = path.dirname(new URL(import.meta.url).pathname);
const ROOT = path.resolve(HERE, '..', '..');
const SOURCE = path.join(HERE, 'qr_source.js');
const VIEWS = ['liveteach/projector.html', 'liveteach/teacher.html'];
const BEGIN = '<!-- MBM-LIVETEACH-QR:BEGIN generated by tools/liveteach/stamp_qr.mjs from tools/liveteach/qr_source.js — do not edit by hand -->';
const END = '<!-- MBM-LIVETEACH-QR:END -->';

function region() {
  return BEGIN + '\n<script>\n' + fs.readFileSync(SOURCE, 'utf8') + '</script>\n' + END;
}
function check(files) {
  const reg = region();
  const bad = [];
  for (const rel of files) {
    const p = path.join(ROOT, rel);
    if (!fs.existsSync(p)) { bad.push(rel + ': MISSING FILE'); continue; }
    const html = fs.readFileSync(p, 'utf8');
    const a = html.indexOf(BEGIN), b = html.indexOf(END);
    if (a === -1 || b === -1) { bad.push(rel + ': NO QR REGION'); continue; }
    if (html.slice(a, b + END.length) !== reg) bad.push(rel + ': QR REGION DRIFTED');
  }
  return bad;
}

const MODE = process.argv[2] || '';
if (MODE === '--check') {
  const bad = check(VIEWS);
  if (bad.length) { bad.forEach(b => console.log('[FAIL] ' + b)); process.exit(1); }
  console.log('[OK] both stamped QR regions match qr_source.js byte-for-byte');
} else if (MODE === '--self-test') {
  const tmp = fs.mkdtempSync(path.join(HERE, 'selftest-'));
  try {
    const rel = path.join(path.basename(tmp), 'view.html');
    fs.writeFileSync(path.join(HERE, rel), region().replace('0x11d', '0x11e'));
    const bad = check([path.join('tools/liveteach', rel)]);
    if (bad.length === 1 && /DRIFTED/.test(bad[0])) console.log('[SELF-TEST] PASS — a perturbed GF polynomial is detected');
    else { console.log('[SELF-TEST] FAIL'); process.exit(1); }
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
} else {
  const reg = region();
  for (const rel of VIEWS) {
    const p = path.join(ROOT, rel);
    let html = fs.readFileSync(p, 'utf8');
    const a = html.indexOf(BEGIN), b = html.indexOf(END);
    if (a !== -1 && b !== -1) html = html.slice(0, a) + reg + html.slice(b + END.length);
    else html = html.replace('<!-- MBM-LIVETEACH-CORE:BEGIN', reg + '\n<!-- MBM-LIVETEACH-CORE:BEGIN');
    fs.writeFileSync(p, html);
    console.log('[STAMPED] ' + rel);
  }
}
