/* Stamp tools/liveteach/core_source.js into every liveteach view between the
   MBM-LIVETEACH-CORE markers, byte-identically — the inline-exit pattern:
   shared code inside single self-contained files, pinned by a checker instead
   of a runtime include.

     node tools/liveteach/stamp_core.mjs          rewrite the stamped regions
     node tools/liveteach/stamp_core.mjs --check  exit 1 on any drift (CI mode)
     node tools/liveteach/stamp_core.mjs --self-test  prove --check can fail

   The --self-test is the negative control: it perturbs one byte of a stamped
   copy in a temp clone and asserts --check logic reports the drift. */
import fs from 'node:fs';
import path from 'node:path';

const HERE = path.dirname(new URL(import.meta.url).pathname);
const ROOT = path.resolve(HERE, '..', '..');
const SOURCE = path.join(HERE, 'core_source.js');
const VIEWS = ['liveteach/index.html', 'liveteach/projector.html', 'liveteach/teacher.html'];
const BEGIN = '<!-- MBM-LIVETEACH-CORE:BEGIN generated by tools/liveteach/stamp_core.mjs from tools/liveteach/core_source.js — do not edit by hand -->';
const END = '<!-- MBM-LIVETEACH-CORE:END -->';

function region() {
  const src = fs.readFileSync(SOURCE, 'utf8');
  return BEGIN + '\n<script>\n' + src + '</script>\n' + END;
}

function splice(html, reg) {
  const a = html.indexOf(BEGIN);
  const b = html.indexOf(END);
  if (a === -1 || b === -1) return null;
  return html.slice(0, a) + reg + html.slice(b + END.length);
}

function check(files) {
  const reg = region();
  const bad = [];
  for (const rel of files) {
    const p = path.join(ROOT, rel);
    if (!fs.existsSync(p)) { bad.push(rel + ': MISSING FILE'); continue; }
    const html = fs.readFileSync(p, 'utf8');
    const a = html.indexOf(BEGIN);
    const b = html.indexOf(END);
    if (a === -1 || b === -1) { bad.push(rel + ': NO STAMPED REGION'); continue; }
    const got = html.slice(a, b + END.length);
    if (got !== reg) bad.push(rel + ': REGION DRIFTED from core_source.js');
  }
  return bad;
}

const MODE = process.argv[2] || '';
if (MODE === '--check') {
  const bad = check(VIEWS);
  if (bad.length) { bad.forEach(b => console.log('[FAIL] ' + b)); process.exit(1); }
  console.log('[OK] all ' + VIEWS.length + ' stamped copies match core_source.js byte-for-byte');
} else if (MODE === '--self-test') {
  // Negative control: a one-byte perturbation must be reported as drift.
  const tmp = fs.mkdtempSync(path.join(HERE, 'selftest-'));
  try {
    const rel = path.join(path.basename(tmp), 'view.html');
    const good = '<!doctype html>\n' + region() + '\n';
    fs.writeFileSync(path.join(HERE, rel), good.replace('mbm_liveteach_v1', 'mbm_liveteach_vX'));
    const bad = check([path.join('tools/liveteach', rel)]);
    if (bad.length === 1 && /DRIFTED/.test(bad[0])) { console.log('[SELF-TEST] PASS — drift detected'); }
    else { console.log('[SELF-TEST] FAIL — a perturbed copy was not reported'); process.exit(1); }
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
} else {
  const reg = region();
  for (const rel of VIEWS) {
    const p = path.join(ROOT, rel);
    if (!fs.existsSync(p)) { console.log('[SKIP] ' + rel + ' (absent)'); continue; }
    const html = fs.readFileSync(p, 'utf8');
    const out = splice(html, reg);
    if (out === null) { console.log('[SKIP] ' + rel + ' (no markers)'); continue; }
    if (out !== html) { fs.writeFileSync(p, out); console.log('[STAMPED] ' + rel); }
    else console.log('[OK] ' + rel + ' already current');
  }
}
