/* Stamp the canonical Made by Matt splash into every liveteach view.

   tools/liveteach/splash_canonical.html is the estate's inlined splash
   IMPLEMENTATION, byte-for-byte as it ships in Games/ (marker comment +
   opening <script> + the MadeByMattSplash IIFE through `})(window);`). The
   splash gate's own self-test depends on exact byte patterns inside it, so it
   is never edited here — only the small per-view CALLER (the title) is
   authored by this stamper.

     node tools/liveteach/stamp_splash.mjs          rewrite the stamped regions
     node tools/liveteach/stamp_splash.mjs --check  exit 1 on drift (CI mode)
     node tools/liveteach/stamp_splash.mjs --self-test  prove --check can fail */
import fs from 'node:fs';
import path from 'node:path';

const HERE = path.dirname(new URL(import.meta.url).pathname);
const ROOT = path.resolve(HERE, '..', '..');
const CANON = path.join(HERE, 'splash_canonical.html');
const VIEWS = [
  { file: 'liveteach/index.html', title: 'LIVE-TEACH' },
  { file: 'liveteach/projector.html', title: 'LIVE-TEACH' },
  { file: 'liveteach/teacher.html', title: 'TEACHER HUD' },
];
const BEGIN = '<!-- MBM-LIVETEACH-SPLASH:BEGIN generated by tools/liveteach/stamp_splash.mjs — canonical splash + per-view caller; do not edit by hand -->';
const END = '<!-- MBM-LIVETEACH-SPLASH:END -->';

function region(title) {
  const impl = fs.readFileSync(CANON, 'utf8');
  const caller = [
    '</script>',
    '<script>',
    '(function () {',
    '  function boot() {',
    '    /* One start state: the splash plays above the view and fades to reveal',
    '       it; onComplete adds nothing. */',
    "    window.MadeByMattSplash.start({ title: '" + title + "', onComplete: function () {} });",
    '  }',
    '  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);',
    '  else boot();',
    '})();',
    '</script>',
  ].join('\n');
  return BEGIN + '\n' + impl + '\n' + caller + '\n' + END;
}

function check(views) {
  const bad = [];
  for (const v of views) {
    const p = path.join(ROOT, v.file);
    if (!fs.existsSync(p)) { bad.push(v.file + ': MISSING FILE'); continue; }
    const html = fs.readFileSync(p, 'utf8');
    const a = html.indexOf(BEGIN);
    const b = html.indexOf(END);
    if (a === -1 || b === -1) { bad.push(v.file + ': NO SPLASH REGION'); continue; }
    if (html.slice(a, b + END.length) !== region(v.title)) bad.push(v.file + ': SPLASH REGION DRIFTED');
  }
  return bad;
}

const MODE = process.argv[2] || '';
if (MODE === '--check') {
  const bad = check(VIEWS);
  if (bad.length) { bad.forEach(b => console.log('[FAIL] ' + b)); process.exit(1); }
  console.log('[OK] all ' + VIEWS.length + ' splash regions match the canonical bytes');
} else if (MODE === '--self-test') {
  const tmpdir = fs.mkdtempSync(path.join(HERE, 'selftest-'));
  try {
    const rel = path.join(path.basename(tmpdir), 'view.html');
    fs.writeFileSync(path.join(HERE, rel),
      region('X').replace('stopImmediatePropagation', 'stopImmediatePropagatioX'));
    const bad = check([{ file: path.join('tools/liveteach', rel), title: 'X' }]);
    if (bad.length === 1 && /DRIFTED/.test(bad[0])) console.log('[SELF-TEST] PASS — perturbed hardening byte detected');
    else { console.log('[SELF-TEST] FAIL'); process.exit(1); }
  } finally {
    fs.rmSync(tmpdir, { recursive: true, force: true });
  }
} else {
  for (const v of VIEWS) {
    const p = path.join(ROOT, v.file);
    if (!fs.existsSync(p)) { console.log('[SKIP] ' + v.file); continue; }
    let html = fs.readFileSync(p, 'utf8');
    const a = html.indexOf(BEGIN);
    const b = html.indexOf(END);
    const reg = region(v.title);
    if (a !== -1 && b !== -1) html = html.slice(0, a) + reg + html.slice(b + END.length);
    else html = html.replace('</body>', reg + '\n</body>');
    fs.writeFileSync(p, html);
    console.log('[STAMPED] ' + v.file);
  }
}
