const pptxgen = require('pptxgenjs');
const {imageSizingCrop, safeOuterShadow, warnIfSlideHasOverlaps, warnIfSlideElementsOutOfBounds} = require('/home/oai/skills/slides/pptxgenjs_helpers');
const pptx = new pptxgen();
pptx.defineLayout({name:'A4L', width:11.6929, height:8.2677}); pptx.layout='A4L';
pptx.author='Matt Roper'; pptx.subject='LundyLoop teacher and pupil posters'; pptx.title='The LundyLoop - Professional Poster Collection'; pptx.company='Progress Schools Tees Valley'; pptx.lang='en-GB';
pptx.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos',lang:'en-GB'};
const C={navy:'17213E',navy2:'202D54',pink:'E50083',gold:'D4A63A',cream:'FFF7DB',paper:'F7F4ED',blue:'2E63D6',teal:'168B89',green:'16735B',red:'A91647',purple:'6845C2',ink:'20283A',muted:'667085',line:'D8DFEA',white:'FFFFFF',pale:'EFF3F8'};
const data=[
{n:'SCIENCE',tag:'Experiment • explain • improve',img:'01_science.png',dialect:'Hybrid: written, practical and discursive.',steps:['Safe conditions; equipment and success criteria ready.','Correct, explain, rework, improve the method or re-attempt safely.','Read the correction or watch the practical response; check the science.','Change the next question, variable, model, scaffold or challenge.'],good:'A learner repeats a reading at eye level. The adult watches, checks precision and introduces uncertainty.',bad:'R is added because a second value appears, but nobody checks the method.',ask:'What does your evidence show - and what should we test next?'},
{n:'ENGLISH',tag:'Read • craft • refine',img:'02_english.png',dialect:'Book-based, with oral and creative episodes.',steps:['Accessible text, clear model and protected response time.','Edit, redraft, rehearse orally or strengthen an inference.','Read or hear the response and engage with meaning, not just accuracy.','Change the model, question, scaffold, vocabulary or next redraft.'],good:'A learner adds evidence to explain hesitation. The adult reads the link and probes motive.',bad:'Every technical error is corrected, obscuring the intended learning.',ask:'How did this change strengthen your meaning?'},
{n:'MATHEMATICS',tag:'Reason • rework • transfer',img:'03_maths.png',dialect:'Predominantly book-based, with modelled and practical episodes.',steps:['Calm conditions, visible method and manageable question set.','Correct a step, rework, represent or explain an alternative method.','Check the reasoning and locate the misconception - not just the answer.','Choose the next example, representation, scaffold or variation.'],good:'A learner realigns place values. The adult checks the method and gives a transfer question.',bad:'R is added only because the final answer is correct.',ask:'Talk me through the step you changed.'},
{n:'HUMANITIES',tag:'Evidence • explain • interpret',img:'04_humanities.png',dialect:'Hybrid: written, discursive and fieldwork.',steps:['Accessible sources, safe discussion and clear chronology or context.','Improve an explanation, inference, map skill, fieldwork action or judgement.','Receive the reasoning and check how evidence has been used.','Select the next source, question, scaffold or interpretation.'],good:'A learner compares two sources. The adult receives the reasoning and introduces a conflicting source.',bad:'Unsupported opinion is treated as a completed response.',ask:'Which evidence changed your judgement?'},
{n:'PE & OUTDOOR EDUCATION',tag:'Perform • observe • adapt',img:'05_pe.png',dialect:'Practical and physical.',steps:['Safe timing, clear boundaries and private correction when needed.','Correct the movement, rep, route, teamwork action or tactical choice.','Watch the re-attempt and respond to what actually happened.','Change the next cue, support, route, equipment or challenge.'],good:'A learner changes foot placement. The adult watches the rep and progresses to target placement.',bad:'A worksheet or photograph is created for every live coaching moment.',ask:'Show me the cue in your next attempt.'},
{n:'D&T & FOOD',tag:'Make • test • refine',img:'06_dtfood.png',dialect:'Practical, technical and book-based.',steps:['Safe workstation, equipment checks, clear demonstration and hygiene.','Use a safer cut, improved joint, adjusted setting, recipe or prototype.','Observe the change and check the technical understanding.','Change the next process, tool, specification or quality-control decision.'],good:'A learner reduces heat and stirs continuously. The adult observes and probes viscosity.',bad:'Safe practical flow is interrupted merely to create evidence.',ask:'What changed in the process or product?'},
{n:'ART',tag:'Explore • create • develop',img:'07_art.png',dialect:'Creative; personal style and identity are respected.',steps:['Sensitive timing; feedback addresses work, process and intention.','Make a study, experiment, compositional change or final refinement.','Compare versions and discuss the learner’s intention.','Change the next material, technique, composition or artist reference.'],good:'A learner increases focal contrast. The adult compares studies and discusses intention.',bad:'Personal expression is graded according to adult taste.',ask:'Which version best supports your intention?'},
{n:'MUSIC & DRAMA',tag:'Rehearse • perform • shape',img:'08_musicdrama.png',dialect:'Creative and performance-based.',steps:['Emotionally safe rehearsal climate and a manageable cue.','Make a second take; alter timing, dynamics, characterisation or staging.','Watch or listen to the full response and name the change.','Change the rehearsal target, role, technical cue or challenge.'],good:'A learner retries a transition at half tempo. The adult listens and restores tempo gradually.',bad:'Every creative moment is interrupted for coding or filming.',ask:'What changed in the second take?'},
{n:'PSHE & RSHE',tag:'Distance • reason • safeguard',img:'09_pshe.png',dialect:'Discursive, with a safeguarding firewall.',steps:['Use distancing, scenarios, right to pass and anonymous questions.','Give safe scenario advice, revisit a concept or ask anonymously.','Hear the whole answer or answer the class question box.','Let misconceptions shape the next explanation; never trace anonymous Voice.'],good:'Scenario advice adds a trusted adult and support route; the next scenario tests emergency help.',bad:'A disclosure is coded, photographed or investigated as learning evidence.',ask:'What could the character do next - and why?'},
{n:'RE & CITIZENSHIP',tag:'Compare • reason • evaluate',img:'10_re.png',dialect:'Discursive and book-based.',steps:['Respectful norms, balanced presentation and a clear right to pass.','Compare evidence, improve an argument or give a reasoned judgement.','Receive the reasoning; check evidence, balance and misconception.','Change the next source, counterargument, concept or case study.'],good:'A learner adds a contrasting viewpoint. The adult introduces a case that complicates both.',bad:'A learner is required to defend a personal belief.',ask:'What evidence supports that viewpoint?'},
];
const pupils=[
{n:'BUILD',title:'I CAN SHOW MY LEARNING',tag:'Safe • simple • supported',img:'11_build.png',accent:'2E79B7',steps:['GET READY|I feel safe and calm. I have what I need.','HAVE A GO|I fix it, say it, point, choose or try again.','SHOW AN ADULT|An adult really looks, listens or watches.','WHAT HAPPENS NEXT|My next job or help changes because of my response.'],say:['Can you watch me try again?','I need help to start.','I did my next step.'],closed:'You try again. An adult watches and gives the next cue.',open:'You tried again, but nobody has checked yet. That is Voice - keep the loop open.'},
{n:'GROW',title:'I OWN MY FEEDBACK',tag:'Respond • be heard • move forward',img:'12_grow.png',accent:'168B68',steps:['SPACE|I am ready and have enough time and support.','VOICE|I correct, rework, explain, show or try again.','AUDIENCE|My teacher genuinely checks my response.','INFLUENCE|What I showed changes the next question, help or challenge.'],say:['What is my one next step?','Can you check my response?','What changed because of my answer?'],closed:'You correct the method and explain it. The teacher checks and gives a transfer question.',open:'You copy a model without understanding it, or R appears before checking.'},
{n:'LAUNCH',title:'TURN FEEDBACK INTO PROGRESS',tag:'Act • check • adapt • remember',img:'13_launch.png',accent:'6845C2',steps:['SPOT THE GAP|Use feedback, criteria or a mark scheme to locate the issue.','RESPOND|Correct, redraft, rework, rehearse or improve.','GET AUDIENCE|Ask for genuine checking against the standard - not a tick.','USE THE PATTERN|Let closed loops guide revision and the next target.'],say:['Which mark did this change earn?','What pattern is in my next steps?','What should I practise next?'],closed:'You redraft one paragraph. The teacher checks it against the criteria and targets a new gap.',open:'You change words only to make the page look different, without checking improvement.'}
];
function addBrand(slide,label){slide.addShape(pptx.ShapeType.rect,{x:0,y:0,w:11.693,h:.17,fill:{color:C.pink},line:{color:C.pink}});slide.addText('M',{x:.32,y:.29,w:.36,h:.36,fontFace:'Aptos Display',fontSize:17,bold:true,color:C.gold,align:'center',margin:0,line:{color:C.gold,pt:1.4}});slide.addText('PROGRESS SCHOOLS TEES VALLEY  /  THE LUNDY LOOP',{x:.79,y:.31,w:4.4,h:.2,fontSize:7.5,bold:true,color:C.white,charSpacing:1.2,margin:0});slide.addText(label,{x:9.2,y:.31,w:2.1,h:.2,fontSize:7.5,bold:true,color:'DDE5F4',align:'right',charSpacing:1,margin:0});}
function rounded(slide,x,y,w,h,fill,line=C.line,r=.1){slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:r,fill:{color:fill},line:{color:line,pt:1}})}
function header(slide,title,tag,label){slide.background={color:C.navy};addBrand(slide,label);slide.addText(title,{x:.36,y:.69,w:7.5,h:.56,fontFace:'Aptos Display',fontSize:title.length>21?25:31,bold:true,color:C.white,margin:0,breakLine:false});slide.addText(tag,{x:.39,y:1.28,w:6.6,h:.25,fontSize:10.5,bold:true,color:'EBC5D9',margin:0,charSpacing:.5});}
function addSteps(slide,steps,x,y,w){const gap=.12; const cw=(w-gap*3)/4; const icons=['1','2','3','4']; const titles=['SPACE','VOICE','AUDIENCE','INFLUENCE']; for(let i=0;i<4;i++){const xx=x+i*(cw+gap); const isAud=i===2; rounded(slide,xx,y,cw,1.19,isAud?C.cream:C.white,isAud?C.gold:C.line); slide.addShape(pptx.ShapeType.ellipse,{x:xx+.13,y:y+.14,w:.34,h:.34,fill:{color:isAud?C.gold:C.pink},line:{color:isAud?C.gold:C.pink}});slide.addText(icons[i],{x:xx+.13,y:y+.20,w:.34,h:.13,fontSize:8,bold:true,color:C.white,align:'center',margin:0});slide.addText(titles[i],{x:xx+.55,y:y+.15,w:cw-.65,h:.18,fontSize:8.5,bold:true,color:C.navy,margin:0,charSpacing:.7});slide.addText(steps[i],{x:xx+.14,y:y+.52,w:cw-.28,h:.53,fontSize:7.4,color:C.ink,margin:.02,breakLine:false,fit:'shrink'});}}
function addRGate(slide,y){rounded(slide,4.47,y,6.82,.81,C.cream,C.gold);slide.addShape(pptx.ShapeType.ellipse,{x:4.64,y:y+.1,w:.59,h:.59,fill:{color:C.pink},line:{color:C.pink}});slide.addText('R',{x:4.64,y:y+.19,w:.59,h:.24,fontSize:19,bold:true,color:C.white,align:'center',margin:0});slide.addText('R ONLY AFTER GENUINE AUDIENCE',{x:5.42,y:y+.12,w:4.9,h:.21,fontSize:13.5,bold:true,color:C.navy,margin:0});slide.addText('A response is Voice. R closes the loop only after an adult genuinely reads, hears or watches it.',{x:5.42,y:y+.43,w:5.45,h:.2,fontSize:7.8,color:C.ink,margin:0});}
const whyLines=[
'A changed number is not a checked method.',
'Over-correction drowned the meaning the learner voiced.',
'A right answer can still hide a wrong method.',
'Voice without evidence was closed as if audienced.',
'Evidence-hunting replaced watching the actual re-attempt.',
'The record mattered more than the making.',
'Audience judged taste instead of the learner’s intention.',
'Capturing the take replaced listening to it.',
'Safeguarding, not evidence — disclosures leave the loop entirely.',
'Space failed — beliefs are not assessable positions.'
];
function teacherPoster(d,idx){const s=pptx.addSlide(); header(s,d.n,d.tag,`TEACHER POSTER ${idx+1}/10`);s.addImage({path:`/mnt/data/lundy_poster_build/assets/${d.img}`,...imageSizingCrop(`/mnt/data/lundy_poster_build/assets/${d.img}`,.35,1.72,3.82,5.88)});s.addShape(pptx.ShapeType.rect,{x:.35,y:6.58,w:3.82,h:1.02,fill:{color:C.navy,transparency:5},line:{color:C.navy,transparency:100}});s.addText('SUBJECT DIALECT',{x:.57,y:6.73,w:1.4,h:.16,fontSize:7,bold:true,color:C.gold,margin:0,charSpacing:.8});s.addText(d.dialect,{x:.57,y:6.98,w:3.25,h:.38,fontSize:10.5,bold:true,color:C.white,margin:0,fit:'shrink'});
addSteps(s,d.steps,4.47,1.72,6.82);addRGate(s,3.06);
rounded(s,4.47,4.02,3.32,1.47,C.white);s.addText('✓ GOOD USE',{x:4.67,y:4.2,w:1.5,h:.2,fontSize:8,bold:true,color:C.green,margin:0,charSpacing:.5});s.addText(d.good,{x:4.67,y:4.53,w:2.92,h:.61,fontSize:9.2,color:C.ink,margin:0,fit:'shrink'});s.addText(`ASK  “${d.ask}”`,{x:4.67,y:5.17,w:2.9,h:.19,fontSize:7.4,bold:true,color:C.green,margin:0});
rounded(s,7.97,4.02,3.32,1.47,'FFF0F5','D88AA6');s.addText('✕ NOT YET',{x:8.17,y:4.2,w:1.5,h:.2,fontSize:8,bold:true,color:C.red,margin:0,charSpacing:.5});s.addText(d.bad,{x:8.17,y:4.53,w:2.92,h:.61,fontSize:9.2,color:C.ink,margin:0,fit:'shrink'});s.addText('WHY  '+whyLines[idx],{x:8.17,y:5.14,w:2.9,h:.26,fontSize:7.2,bold:true,color:C.red,margin:0,fit:'shrink'});
rounded(s,4.47,5.68,6.82,1.31,'F2EEFC','B7A6E6');s.addText('HELPFUL TEACHER MOVES',{x:4.67,y:5.87,w:2.3,h:.19,fontSize:8,bold:true,color:C.purple,margin:0,charSpacing:.55});const tips=['One precise next step','Protect response time','Use the least loaded mode','Let the response change what comes next'];tips.forEach((t,i)=>{const xx=4.67+i*1.61;slide=s;slide.addShape(pptx.ShapeType.ellipse,{x:xx,y:6.21,w:.22,h:.22,fill:{color:C.pink},line:{color:C.pink}});slide.addText(String(i+1),{x:xx,y:6.265,w:.22,h:.08,fontSize:5.8,bold:true,color:C.white,align:'center',margin:0});slide.addText(t,{x:xx+.29,y:6.17,w:1.22,h:.38,fontSize:7.5,bold:true,color:C.navy,margin:0,fit:'shrink'});});s.addText('Ask yourself: What did the learner do? How did I receive it? What changed next?',{x:4.47,y:7.23,w:4.5,h:.22,fontSize:8.6,bold:true,color:C.gold,margin:0});s.addText('SPACE  →  VOICE  →  AUDIENCE  →  INFLUENCE',{x:4.47,y:7.57,w:4.35,h:.18,fontSize:8,bold:true,color:C.white,charSpacing:.65,margin:0});s.addText('Version 3.1 · July 2026 · Matt Roper',{x:8.02,y:7.87,w:2.28,h:.15,fontSize:6.4,color:'B9C4D8',align:'right',margin:0});s.addText('SCAN FOR THE FULL GUIDE',{x:9.02,y:7.23,w:1.48,h:.16,fontSize:5.7,bold:true,color:C.white,align:'right',margin:0});s.addImage({path:`/mnt/data/lundy_poster_build/qr/${String(idx+1).padStart(2,'0')}.svg`,x:10.62,y:7.15,w:.55,h:.55});s.addNotes('Visual on this slide was generated with Microsoft Copilot.\n[Sources]\n- Uploaded LundyLoop subject guide: '+d.n+'\n[/Sources]');warnIfSlideHasOverlaps(s,pptx);warnIfSlideElementsOutOfBounds(s,pptx);}
function pupilPoster(d,idx){const s=pptx.addSlide(); header(s,d.title,d.tag,`PUPIL POSTER · ${d.n}`);s.addImage({path:`/mnt/data/lundy_poster_build/assets/${d.img}`,...imageSizingCrop(`/mnt/data/lundy_poster_build/assets/${d.img}`,.35,1.72,4.0,5.88)});s.addShape(pptx.ShapeType.rect,{x:.35,y:6.56,w:4,h:1.04,fill:{color:C.navy,transparency:4},line:{color:C.navy,transparency:100}});s.addText('FEEDBACK IS A CHANCE TO SHOW WHAT YOU CAN DO NEXT',{x:.58,y:6.74,w:3.48,h:.42,fontSize:12,bold:true,color:C.white,margin:0,fit:'shrink'});s.addText('Writing • speaking • pointing • choosing • demonstrating • trying again',{x:.58,y:7.25,w:3.5,h:.18,fontSize:7.2,color:'DCE5F4',margin:0});
const x=4.62,y=1.72,w=6.67,g=.11,cw=(w-g*3)/4;d.steps.forEach((z,i)=>{const [t,b]=z.split('|');const xx=x+i*(cw+g);rounded(s,xx,y,cw,1.37,i===2?C.cream:C.white,i===2?C.gold:C.line);s.addShape(pptx.ShapeType.ellipse,{x:xx+.5,y:y+.08,w:.48,h:.48,fill:{color:i===2?C.gold:d.accent},line:{color:i===2?C.gold:d.accent}});s.addText(String(i+1),{x:xx+.5,y:y+.205,w:.48,h:.12,fontSize:9,bold:true,color:C.white,align:'center',margin:0});s.addText(t,{x:xx+.12,y:y+.52,w:cw-.24,h:.22,fontSize:9.2,bold:true,color:C.navy,align:'center',margin:0,fit:'shrink'});s.addText(b,{x:xx+.15,y:y+.82,w:cw-.3,h:.48,fontSize:8.1,color:C.ink,align:'center',margin:0,fit:'shrink'});});
rounded(s,4.62,3.32,6.67,.95,C.cream,C.gold);s.addShape(pptx.ShapeType.ellipse,{x:4.82,y:3.47,w:.6,h:.6,fill:{color:C.pink},line:{color:C.pink}});s.addText('R',{x:4.82,y:3.63,w:.6,h:.2,fontSize:20,bold:true,color:C.white,align:'center',margin:0});s.addText('THE LOOP CLOSES AFTER AN ADULT REALLY LOOKS, LISTENS OR WATCHES.',{x:5.62,y:3.48,w:5.25,h:.32,fontSize:12.2,bold:true,color:C.navy,margin:0,fit:'shrink'});s.addText('Your attempt matters. R means your response has been genuinely received.',{x:5.62,y:3.9,w:5.1,h:.18,fontSize:8,color:C.ink,margin:0});
rounded(s,4.62,4.48,2.15,1.67,'EEF5FF','8FB0EB');s.addText('USE YOUR VOICE',{x:4.83,y:4.69,w:1.7,h:.18,fontSize:8,bold:true,color:C.blue,margin:0});d.say.forEach((v,i)=>s.addText('“'+v+'”',{x:4.83,y:5.02+i*.34,w:1.7,h:.23,fontSize:8.1,bold:true,color:C.navy,margin:0,fit:'shrink'}));rounded(s,6.94,4.48,2.09,1.67,'EDFBF5','64A58D');s.addText('✓ CLOSED LOOP',{x:7.15,y:4.69,w:1.55,h:.18,fontSize:8,bold:true,color:C.green,margin:0});s.addText(d.closed,{x:7.15,y:5.05,w:1.68,h:.73,fontSize:9,color:C.ink,margin:0,fit:'shrink'});rounded(s,9.2,4.48,2.09,1.67,'FFF0F5','D88AA6');s.addText('↻ KEEP IT OPEN',{x:9.41,y:4.69,w:1.55,h:.18,fontSize:8,bold:true,color:C.red,margin:0});s.addText(d.open,{x:9.41,y:5.05,w:1.68,h:.73,fontSize:9,color:C.ink,margin:0,fit:'shrink'});rounded(s,4.62,6.37,6.67,.93,'F2EEFC','B7A6E6');s.addText('REMEMBER',{x:4.84,y:6.59,w:1.1,h:.18,fontSize:8,bold:true,color:C.purple,margin:0});s.addText('Getting it wrong first is allowed. Asking for help is Voice. Your response should matter.',{x:5.95,y:6.53,w:4.92,h:.31,fontSize:10.5,bold:true,color:C.navy,margin:0,fit:'shrink'});s.addText('SPACE  →  VOICE  →  AUDIENCE  →  INFLUENCE  →  then the loop starts again',{x:4.62,y:7.57,w:6.67,h:.18,fontSize:8.2,bold:true,color:C.white,align:'center',charSpacing:.35,margin:0});s.addText('Version 3.1 · July 2026 · Matt Roper',{x:8.85,y:7.91,w:2.44,h:.13,fontSize:5.8,color:'B9C4D8',align:'right',margin:0});s.addNotes('Visual on this slide was generated with Microsoft Copilot.\n[Sources]\n- Uploaded LundyLoop pupil-facing pathway guidance: '+d.n+'\n[/Sources]');warnIfSlideHasOverlaps(s,pptx);warnIfSlideElementsOutOfBounds(s,pptx);}
data.forEach(teacherPoster);pupils.forEach(pupilPoster);
pptx.writeFile({fileName:'/mnt/data/LundyLoop_Sublime_Posters.pptx'});
