/* PACK-1R shell. One owner per control. No pupil response leaves this page. */
(()=>{'use strict';
 const $=s=>document.querySelector(s), all=s=>[...document.querySelectorAll(s)];
 const slides=all('.slide'),config=JSON.parse($('#lesson-config').textContent);
 let index=0,remaining=0,running=false,tick=null,opener=null;
 const timer=$('#auto-timer-display');
 function clock(){timer.textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');}
 function stop(){running=false;clearInterval(tick);$('#auto-timer-toggle').textContent='Start timer';$('#auto-timer-toggle').setAttribute('aria-pressed','false');}
 function go(n){stop();index=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,i)=>{s.classList.toggle('active',i===index);s.hidden=i!==index;});$('#slide-picker').value=String(index);$('#previous-slide').disabled=index===0;$('#next-slide').disabled=index===slides.length-1;$('#progressBar').value=index+1;$('#progressLabel').textContent=`${index+1} / ${slides.length} · ${config.stages[index]}`;$('#classic-status').textContent=`${config.pathway} · Sum1·W1 · ${config.timers[index]} minutes`;$('#classic-progress').textContent=`${config.timers.slice(0,index).reduce((a,b)=>a+b,0)} of 40 minutes before this stage`;remaining=config.timers[index]*60;clock();$('#auto-timer-toggle').disabled=remaining===0;if($('#xpCount')){$('#xpCount').textContent=String(index+1);$('#xpFill').style.width=((index+1)/slides.length*100)+'%';}window.scrollTo(0,0);}
 $('#previous-slide').addEventListener('click',()=>go(index-1));$('#next-slide').addEventListener('click',()=>go(index+1));$('#slide-picker').addEventListener('change',e=>go(Number(e.target.value)));
 $('#auto-timer-toggle').addEventListener('click',()=>{if(running){stop();return;}if(remaining===0)return;running=true;$('#auto-timer-toggle').textContent='Pause timer';$('#auto-timer-toggle').setAttribute('aria-pressed','true');tick=setInterval(()=>{remaining=Math.max(0,remaining-1);clock();if(!remaining){stop();$('#timer-status').textContent='Stage time has ended. Move on when ready.';}},1000);});
 all('[data-sx3-shell]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();const a=el.dataset.action;if(a==='close'){el.closest('dialog').close();return;}if(a==='goto'){el.closest('dialog').close();go(Number(el.dataset.goto));return;}if(a==='finish'){$('#lc-overlay').hidden=false;$('#close-complete').focus();return;}if(a==='close-complete'){$('#lc-overlay').hidden=true;return;}const ids={words:'word-dialog',pause:'pause-dialog',tools:'tools-dialog',organiser:'organiser-dialog',ta:'ta-dialog',picker:'cold-call-dialog'};if(ids[a]){opener=el;stop();$('#'+ids[a]).showModal();}}));
 all('dialog').forEach(d=>d.addEventListener('close',()=>{if(opener)opener.focus();}));
 all('[data-route-group]').forEach(group=>{const scope=group.closest('[data-route-scope]');group.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{group.querySelectorAll('[data-route]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));scope.querySelectorAll('[data-route-panel]').forEach(x=>x.hidden=x.dataset.routePanel!==b.dataset.route);}));});
 all('[data-reveal]').forEach(b=>b.addEventListener('click',()=>{const nodes=all(b.dataset.reveal),reveal=nodes.some(n=>n.hidden);nodes.forEach(n=>n.hidden=!reveal);b.setAttribute('aria-expanded',String(reveal));b.textContent=reveal?'Hide answers':'Reveal answers';}));
 all('[data-check]').forEach(root=>root.querySelectorAll('[data-option]').forEach(b=>b.addEventListener('click',()=>{root.querySelectorAll('[data-option]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const ok=Number(b.dataset.option)===Number(root.dataset.answer);root.querySelector('[data-check-result]').textContent=(ok?'Supported. ':'Try again. ')+root.dataset.feedback;})));
 all('[data-model]').forEach(b=>b.addEventListener('click',()=>{const n=$('#'+b.dataset.model);n.hidden=!n.hidden;b.textContent=n.hidden?'Show worked explanation':'Hide worked explanation';b.setAttribute('aria-expanded',String(!n.hidden));}));
 all('[data-map-view]').forEach(b=>b.addEventListener('click',()=>{const scope=b.closest('[data-map-scope]');scope.querySelectorAll('[data-map-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));scope.querySelectorAll('[data-map-panel]').forEach(x=>x.hidden=x.dataset.mapPanel!==b.dataset.mapView);}));
 $('#pick-volunteer').addEventListener('click',()=>{const pool=$('#volunteers').value.split('\n').map(x=>x.trim()).filter(Boolean);$('#picker-result').textContent=pool.length?'Invite '+pool[Math.floor(Math.random()*pool.length)]+'. They may pass.':'Ask for volunteers first. Enter initials only; they stay in this page.';});
 $('#clear-volunteers').addEventListener('click',()=>{$('#volunteers').value='';$('#picker-result').textContent='List cleared.';});
 function printCopy(selector,answers){const root=document.createElement('div');root.className='print-sheet';const heading=document.createElement('h1');heading.textContent=config.title;root.appendChild(heading);all(selector).forEach(n=>root.appendChild(n.cloneNode(true)));root.querySelectorAll('[id]').forEach(n=>n.removeAttribute('id'));root.querySelectorAll('button,select,textarea,.lundy,.no-print').forEach(n=>n.remove());root.querySelectorAll('[hidden]').forEach(n=>{if(answers||!n.matches('.arrival-answer,.staff-answer,[data-model-answer]'))n.hidden=false;});if(!answers)root.querySelectorAll('.arrival-answer,.staff-answer').forEach(n=>n.remove());const area=$('#print-area');area.replaceChildren(root);area.dataset.printKind=selector;window.print();}
 all('[data-print]').forEach(b=>b.addEventListener('click',()=>printCopy(b.dataset.print,b.dataset.answers==='true')));
 if(config.pathway!=='BUILD'){try{if(localStorage.getItem('mbm_guide_v1')==='on')document.documentElement.classList.add('mbm-guide-on');}catch(e){}$('#guide-toggle').addEventListener('click',e=>{const on=document.documentElement.classList.toggle('mbm-guide-on');e.target.setAttribute('aria-pressed',String(on));$('#guide-status').textContent=on?'Staff guide preference is on. Use TA layer to read the notes.':'Staff guide preference is off.';try{localStorage.setItem('mbm_guide_v1',on?'on':'off');}catch(err){}});}
 go(0);
})();
