/* A-P0.3 — the CSP control.
 *
 * P0.1 measured what the estate injects. The answer decided P0.2:
 *
 *   NO game route on this site ships its own CSP, so Scrap Core's would be the
 *   first. /hud.js is requested by 12 of 23 root game routes. ELEVEN request no
 *   same-origin subresource at all — including /emberwild/ and /relicforge/,
 *   which give the player a way out through the estate's own generated INLINE
 *   EXIT REGION instead. data/hud-coverage.json says why that exists in as many
 *   words: "No src, no dependency, no request: the single-file promise these
 *   games make is intact."
 *
 * So the ruling is KEEP THE CSP AS SHIPPED. Not one directive is widened,
 * because on this route not one directive has a measured consumer — and P0.2
 * says a directive widened without a named consumer is a fault, not a fix.
 *
 * This gate proves that decision holds in a browser on the served page, and it
 * carries the planted failure that makes it a control rather than a claim: put
 * /hud.js back in, and the CSP must visibly BLOCK it.
 */
import fs from 'node:fs'; import path from 'node:path'; import http from 'node:http';
import { execFileSync } from 'node:child_process';
const _pw = await import(process.env.SC_PLAYWRIGHT || '/opt/node22/lib/node_modules/playwright/index.js')
  .catch(() => import('playwright'));
const chromium = _pw.chromium || _pw.default.chromium;
const ROOT = process.env.SC_ROOT || path.dirname(new URL(import.meta.url).pathname);
const SITE = process.env.MBM_SITE || '/workspace/mattroper1977.github.io';
const PAYLOAD = path.join(ROOT, 'release', 'Scrap_Core_Expedition_SIGNATURE_v10.html');
const SCRATCH = process.env.SC_SCRATCH || '/tmp/scrapcore-p0-scratch';

const rows = [];
const row = (id, what, ok, detail) => rows.push({ id, what, ok, detail });

/* ---- assemble a scratch estate: the real site plus /scrapcore/ ------------ */
fs.rmSync(SCRATCH, { recursive: true, force: true });
fs.mkdirSync(SCRATCH, { recursive: true });
for (const rel of ['data', 'tools', 'for', 'games', 'assets']) {
  const src = path.join(SITE, rel);
  if (fs.existsSync(src)) fs.cpSync(src, path.join(SCRATCH, rel), { recursive: true });
}
for (const f of ['hud.js']) {
  const src = path.join(SITE, f);
  if (fs.existsSync(src)) fs.cpSync(src, path.join(SCRATCH, f));
}
fs.mkdirSync(path.join(SCRATCH, 'scrapcore'), { recursive: true });
fs.copyFileSync(PAYLOAD, path.join(SCRATCH, 'scrapcore', 'index.html'));
/* Every route already declared in the ledger has to exist here too:
   render_inline_exit.py stamps ALL of them and exits if one is missing. The
   first cut copied five directories and the generator refused — which is the
   generator being right, and is why this is assembled from the ledger rather
   than from a list typed here. */
{
  const covSrc = JSON.parse(fs.readFileSync(path.join(SITE, 'data', 'hud-coverage.json'), 'utf8'));
  for (const e of covSrc.excluded || []) {
    const rel = e.route.endsWith('.html')
      ? (e.route.startsWith('/Lessons/') ? e.route.slice('/Lessons/'.length) : e.route.replace(/^\//, ''))
      : e.route.replace(/^\/|\/$/g, '') + '/index.html';
    const from = path.join(SITE, rel);
    if (!fs.existsSync(from)) continue;
    fs.mkdirSync(path.dirname(path.join(SCRATCH, rel)), { recursive: true });
    fs.copyFileSync(from, path.join(SCRATCH, rel));
  }
}

/* declare the route the way the estate's own ledger requires, so the region is
   stamped by tools/render_inline_exit.py rather than hand-copied */
const covPath = path.join(SCRATCH, 'data', 'hud-coverage.json');
const cov = JSON.parse(fs.readFileSync(covPath, 'utf8'));
const already = cov.excluded.some(e => e.route === '/scrapcore/');
if (!already) cov.excluded.push({
  route: '/scrapcore/',
  verifier: 'tools/scrapcore/verify_csp_allows_estate.mjs',
  gates: ['content-security-policy-carries-no-self'],
  note: "The shipped CSP is default-src 'none' with no 'self' on any directive. "
      + "A <script src=\"/hud.js\"> would be blocked by script-src, so this route takes "
      + "the generated inline exit region instead — the same choice /emberwild/ and "
      + "/relicforge/ make, and the reason the region exists.",
});
fs.writeFileSync(covPath, JSON.stringify(cov, null, 2) + '\n');

let stampOut = '';
try {
  stampOut = execFileSync('python3', [path.join(SCRATCH, 'tools', 'render_inline_exit.py'), '--root', SCRATCH],
    { encoding: 'utf8', stdio: 'pipe' });
} catch (e) { stampOut = 'STAMP FAILED: ' + String(e.stderr || e.message).slice(0, 300); }
const stamped = fs.readFileSync(path.join(SCRATCH, 'scrapcore', 'index.html'), 'utf8');
row('P0.3a', "the estate's own generator stamps the inline exit region into the route",
  /MBM-INLINE-EXIT:BEGIN generated by tools\/render_inline_exit\.py/.test(stamped),
  (stampOut.trim().split('\n').slice(-2).join(' | ') || 'no output') +
  ` · region bytes ${(stamped.match(/MBM-INLINE-EXIT:BEGIN[\s\S]*?MBM-INLINE-EXIT:END[^>]*-->/) || [''])[0].length}`);

/* ---- serve it -------------------------------------------------------------- */
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css',
               '.json': 'application/json', '.png': 'image/png', '.svg': 'image/svg+xml', '.ico': 'image/x-icon' };
function serve(dir) {
  const s = http.createServer((req, res) => {
    let rel = decodeURIComponent(req.url.split('?')[0]);
    if (rel.endsWith('/')) rel += 'index.html';
    const file = path.join(dir, rel);
    if (!file.startsWith(dir) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) { res.writeHead(404); res.end(); return; }
    res.writeHead(200, { 'Content-Type': MIME[path.extname(file)] || 'application/octet-stream' });
    fs.createReadStream(file).pipe(res);
  });
  return new Promise(r => s.listen(0, '127.0.0.1', () => r({ s, base: `http://127.0.0.1:${s.address().port}` })));
}
const { s: server, base: BASE } = await serve(SCRATCH);
const browser = await chromium.launch();

async function visit(url, { descend = false } = {}) {
  const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  const pg = await ctx.newPage();
  const errs = [], blocked = [];
  pg.on('pageerror', e => errs.push(String(e).slice(0, 140)));
  pg.on('requestfailed', r => blocked.push(new URL(r.url()).pathname + ' :: ' + ((r.failure() || {}).errorText || '')));
  await pg.addInitScript(() => {
    window.__csp = [];
    document.addEventListener('securitypolicyviolation', e =>
      window.__csp.push({ directive: e.violatedDirective, blocked: e.blockedURI, sample: (e.sample || '').slice(0, 40) }));
  });
  await pg.goto(url, { waitUntil: 'load', timeout: 45000 });
  await pg.waitForTimeout(2000);
  if (descend) {
    /* one live descent, driven through the page's own controls */
    await pg.evaluate(async () => {
      const sleep = ms => new Promise(r => setTimeout(r, ms));
      const hit = sel => { const e = document.querySelector(sel); if (e) { e.click(); return true; } return false; };
      for (const s of ['#startBtn', '#launchBtn', '[data-action="launch"]', 'button']) if (hit(s)) break;
      await sleep(1500);
      for (const k of ['ArrowRight', 'ArrowDown', 'Space']) {
        window.dispatchEvent(new KeyboardEvent('keydown', { key: k === 'Space' ? ' ' : k, bubbles: true }));
        await sleep(300);
        window.dispatchEvent(new KeyboardEvent('keyup', { key: k === 'Space' ? ' ' : k, bubbles: true }));
      }
      await sleep(1200);
    }).catch(() => {});
    await pg.waitForTimeout(800);
  }
  const csp = await pg.evaluate(() => window.__csp || []);
  const exitMounted = await pg.evaluate(() => !!window.__mbmExit);
  const painted = await pg.evaluate(() => {
    const c = document.querySelector('canvas'); if (!c) return null;
    const g = c.getContext('2d') || c.getContext('webgl') || c.getContext('webgl2');
    if (!g || !g.getImageData) return 'non-2d context';
    const w = Math.min(c.width, 400), h = Math.min(c.height, 300);
    const d = g.getImageData(0, 0, w, h).data;
    let lit = 0; for (let i = 0; i < d.length; i += 4) if (d[i] + d[i + 1] + d[i + 2] > 30) lit++;
    return lit;
  }).catch(() => null);
  await ctx.close();
  return { csp, errs, blocked, exitMounted, painted };
}

/* ---- the assertion ---------------------------------------------------------- */
const boot = await visit(BASE + '/scrapcore/');
row('P0.3b', 'zero securitypolicyviolation on the served page at boot',
  boot.csp.length === 0, boot.csp.length ? JSON.stringify(boot.csp) : 'none');
row('P0.3c', 'the inline exit region EXECUTED — its side effect, not its tag',
  boot.exitMounted === true, `window.__mbmExit = ${boot.exitMounted}`);
row('P0.3d', 'no page errors at boot', boot.errs.length === 0, boot.errs.join(' | ') || 'clean');

const live = await visit(BASE + '/scrapcore/', { descend: true });
row('P0.3e', 'zero securitypolicyviolation through one live descent',
  live.csp.length === 0, live.csp.length ? JSON.stringify(live.csp) : 'none');
row('P0.3f', 'the canvas is painting after the descent',
  typeof live.painted === 'number' && live.painted > 0, `lit pixels: ${live.painted}`);

/* ---- THE PLANTED FAILURE.
 * The ruling is "no 'self', because nothing needs it". The way to prove that
 * gate can go red on the real target is to give it something that does need it:
 * put /hud.js back in and the CSP must visibly block it. If this passes, the
 * CSP is not doing anything and the whole ruling is worthless. */
{
  const p = path.join(SCRATCH, 'scrapcore', 'index.html');
  const clean = fs.readFileSync(p, 'utf8');
  const injected = clean.replace('</body>', `${cov.scriptLine}\n</body>`);
  if (injected === clean) throw new Error('planted failure could not be inserted — no </body>');
  fs.writeFileSync(p, injected);
  const planted = await visit(BASE + '/scrapcore/');
  fs.writeFileSync(p, clean);
  const restored = await visit(BASE + '/scrapcore/');

  const blockedScript = planted.csp.some(v => /script-src/.test(v.directive) && /hud\.js/.test(v.blocked))
                     || planted.blocked.some(b => /hud\.js/.test(b));
  row('P0.3g', 'PLANTED FAILURE: reinstating <script src="/hud.js"> is BLOCKED by the shipped CSP',
    blockedScript,
    `violations ${JSON.stringify(planted.csp)} · failed requests ${JSON.stringify(planted.blocked.filter(b => /hud/.test(b)))}`);
  row('P0.3h', 'and removing it again restores a clean run — the gate is not stuck red',
    restored.csp.length === 0 && restored.exitMounted === true,
    `violations ${restored.csp.length}, exit mounted ${restored.exitMounted}`);
}

/* ---- what P0.2 actually ruled, restated as an assertion -------------------- */
{
  const csp = (fs.readFileSync(PAYLOAD, 'utf8').match(/content="(default-src[^"]*)"/) || [])[1] || '';
  row('P0.2', "the shipped CSP is unchanged: no 'self' was added to any directive",
    csp.length > 0 && !/'self'/.test(csp),
    csp || 'CSP NOT FOUND IN THE PAYLOAD');
}

await browser.close();
server.close();

console.log(`${'id'.padEnd(8)} verdict  what`);
console.log('-'.repeat(78));
for (const r of rows) {
  console.log(`${r.id.padEnd(8)} ${(r.ok ? 'PASS' : 'FAIL').padEnd(8)} ${r.what}`);
  console.log(`         ${r.detail}`);
}
const bad = rows.filter(r => !r.ok);
console.log(`\n${bad.length} failure(s)`);
process.exit(bad.length ? 1 : 0);
