#!/usr/bin/env python3
"""Is a modified file's ONLY difference the generator's exact stamped region?

Why this exists
---------------
tools/verify_cross_estate_unification.py asserts that no standalone lesson or
studio is CHANGED by a release. It implements that as FILE IDENTITY:

    git diff --name-only --diff-filter=MRD base...HEAD   minus   ALLOWED_DIFF

Stamping the maker splash into a lesson modifies that lesson's bytes, so the
stamp and the boundary contradict each other by construction. 550 of the 675
estate-wide splash declines come from exactly that collision.

The smallest change that could admit a stamped lesson WITHOUT weakening the
intent is to compare AUTHORED CONTENT instead of FILE IDENTITY: permit a
modification only when reverse-applying the generator reproduces the base file
byte for byte AND the removed region is byte-identical to the generator's
canonical output.

Both halves are load-bearing, and each has its own negative control below:

  * "reverse-apply reproduces the base" alone would accept a HAND-FORGED
    region, which is exactly what RL6 exists to forbid.
  * "the region is canonical" alone would accept a file that also carries an
    unrelated authored edit smuggled in beside a legitimate stamp.

The reverse-apply span was derived empirically, not assumed. On Town Life at
Site 79232c2e against its pre-splash base 7041e767: head 317,779 B, base
309,421 B, delta 8,358 = an 8,356-byte region plus exactly one leading and one
trailing newline. Removing that span reproduces the base byte for byte.

A predicate that cannot fail admits anything, so this module ships negative
controls and is not to be trusted until --self-test has been observed to turn
each of them red.
"""
from __future__ import annotations

BEGIN = b"<!-- MBM-MAKER-SPLASH:BEGIN generated by tools/render_maker_splash.py, do not edit by hand -->"
END = b"<!-- MBM-MAKER-SPLASH:END -->"


def split_region(head: bytes) -> tuple[bytes, bytes] | None:
    """Return (file-with-the-region-removed, region-bytes), or None.

    None means the file does not carry exactly one well-formed region. The
    span removed is one leading newline + region + one trailing newline, which
    is what tools/render_maker_splash.py writes.
    """
    if head.count(BEGIN) != 1 or head.count(END) != 1:
        return None
    i = head.index(BEGIN)
    j = head.index(END) + len(END)
    if j < i:
        return None
    region = head[i:j]
    start = i - 1 if head[i - 1 : i] == b"\n" else i
    stop = j + 1 if head[j : j + 1] == b"\n" else j
    return head[:start] + head[stop:], region


def only_generated_delta(base: bytes, head: bytes, canonical_region: bytes) -> tuple[bool, str]:
    """True iff head is base plus exactly the generator's canonical region.

    Returns (verdict, reason) so a red says WHICH half failed, not merely that
    something did.
    """
    if base == head:
        return False, "no delta: the file was never stamped"
    parts = split_region(head)
    if parts is None:
        return False, "head does not carry exactly one generated region"
    stripped, region = parts
    if region != canonical_region:
        return False, "region is not the generator's canonical bytes (hand-forged or stale)"
    if stripped != base:
        return False, "reverse-apply does not reproduce the base: an authored edit rides along"
    return True, "the only delta is the generator's canonical region"
