#!/usr/bin/env python3
"""RX3 P2 — THE ONE WRITER for R2 (FoodWise taught-week rule) and R3 (a lesson landed beside an existing one
carries the one non-recommended value 'alternative'; the existing lesson keeps its standing).

Everything it writes is data at a source of truth; every derived surface is then regenerated by the estate's own
generators (build_catalogue.py → terms-and-styles / evidence / shelf JSON; build_science_shelf.py; build_humanities_shelf.py)
and pinned by tools/catalogue/pin_catalogue_contract.py. It never hand-edits a generated file.

Writes (idempotent):
  resources.json                                  rows for the files the landing created (24 classic lessons + 6 FoodWise chassis pages)
  tools/catalogue/pin_catalogue_contract.py       SHELF_ROWS = the reviewed appended rows (everything after the original 734)
  tools/verify_cross_estate_unification.py        CATALOGUE_SHELF_ROWS = len(SHELF_ROWS)   (Lessons copy; --apps patches the mirror too)
  tools/catalogue/SHELF_SELECTION.json            recommended / alternative / recommendedBatches / science (+6 routes with evidence)
  tools/catalogue/SCIENCE_WEEK_BINDINGS.json      source hashes for the three re-cut Science routes; six new bindings from the pack's ruled placement
  tools/catalogue/HUMANITIES_SELECTION.json       every Humanities lesson the manifests and catalogue now declare (the static check's own rule)
  BUILD_ASDAN/FoodWise/manifest.json              the six chassis pages bound to their workbook cells (term evidence the catalogue builder reads)
  BUILD_ASDAN/FoodWise/START_HERE.html            every card states which version is recommended and why, in text

Usage: rx3_recommended.py --repo <worktree> --land <land_all.json> --pack <pack manifest.json> [--apps <apps worktree>] [--run-date 2026-09-07] [--dry]
Prints the per-cell table (cell · recommended · other · rule) and the numbers the pinned checks must carry.
"""
import argparse, json, os, re, sys, datetime, glob, hashlib, pprint, html as H
ap = argparse.ArgumentParser()
ap.add_argument('--repo', required=True); ap.add_argument('--land'); ap.add_argument('--pack')
ap.add_argument('--apps'); ap.add_argument('--run-date', default='2026-09-07'); ap.add_argument('--dry', action='store_true')
ap.add_argument('--science-cells', metavar='TERM', help='HUB1 R1: for every Science cell of TERM (BUILD, GROW and LAUNCH), the animated Explore/Introduce deck (A / L1) is recommended and each Classic is alternative; writes SHELF_SELECTION.json only, then the estate regenerates')
ap.add_argument('--served', help='hub gate only: a published education-lessons tree; asserts exactly one recommended per cell from its own catalogue metadata and hub bytes, writes nothing')
ap.add_argument('--land-a2', nargs='+', metavar='FOLDER', help='LAND-A2 R1/R3: the Autumn 2 Science lessons landed one per folder under each FOLDER are bound to their week from their own evidence, catalogued, and made the recommended lesson of their cell; the cell\'s previous recommended becomes alternative in place')
a = ap.parse_args(); R = a.repo; RUN = datetime.date.fromisoformat(a.run_date)
if a.served: a.dry = True
if not a.science_cells and not a.land_a2 and not (a.land and a.pack): ap.error('--land and --pack are required unless --science-cells or --land-a2')

def P(p): return os.path.join(R, p)
def J(p): return json.load(open(P(p), encoding='utf-8'))
def W(p, d, indent=2):
    if a.dry: return
    open(P(p), 'w', encoding='utf-8').write(json.dumps(d, ensure_ascii=False, indent=indent) + '\n')
def sha(p): return hashlib.sha256(open(P(p), 'rb').read()).hexdigest()
def title_of(p):
    raw = open(P(p), encoding='utf-8').read()
    m = re.search(r'<title>(.*?)</title>', raw, re.S)
    return H.unescape(re.sub(r'\s+', ' ', m.group(1)).strip()).split(' · Made by Matt')[0].strip() if m else p
def title_slide(p):
    raw = open(P(p), encoding='utf-8').read()
    m = re.search(r'<section[^>]*class="[^"]*\bslide\b[^"]*"[^>]*>(.*?)</section>', raw, re.S)
    return re.sub(r'\s+', ' ', H.unescape(re.sub(r'<[^>]+>', ' ', m.group(1)))).strip() if m else ''

# ------------------------------------------------------------------ HUB1 R1 (ruled 2026-09-23): one recommended per Science cell
# "Per cell, RECOMMENDED = the animated Explore/Introduce deck (A / L1). Do decks (B / L2, L3) sit beside as
# 'Full Lundy Loop'. Classics are 'Alternative version'. Nothing in an Aut2 cell that is taught from is ever
# 'Earlier retained versions'. Applies to BUILD, GROW and LAUNCH Aut2 alike; GROW is the proof cell."
#
# Measured before this mode existed: every animated Explore/Introduce deck in Autumn 2 carried style 'earlier',
# because build_catalogue.py derives style from BYTES (>= 4 Lundy panels -> full-lundy, chassis markers ->
# current, else earlier) and the only editorial route to 'recommended' is SHELF_SELECTION.json, which this
# writer had populated for FoodWise and LAUNCH W3-W7 only. The scope is widened here, as R2 says, rather than
# a second writer being added. Do decks are NOT touched: 'Full Lundy Loop' is a claim about the deck's bytes
# and the builder keeps deriving it from them.
#
# A deck's PART is read from what the deck or its pack DECLARES, never from its path: the pack manifest's
# kind/phase, else the title slide ("Week 9A · Explore", "LESSON A", "Lesson 2 of 2 · Do", "LESSON 2"), else
# the pack manifest's own row order (L1 first). A member whose part cannot be read is reported and the cell
# is left alone, so a wrong guess is never written.
def _science_cells(term):
    sel = J('tools/catalogue/SHELF_SELECTION.json'); sel.setdefault('alternative', []); sel.setdefault('recommendedBatches', {})
    TERM_LABEL = {'Aut1': 'Autumn 1', 'Aut2': 'Autumn 2', 'Spr1': 'Spring 1', 'Spr2': 'Spring 2', 'Sum1': 'Summer 1', 'Sum2': 'Summer 2'}
    hub = J('assets/catalogue/science-hub-bindings.json')
    kinds = {}
    for mf in sorted(glob.glob(P('Science_Teesside/**/manifest*.json'), recursive=True)):
        try: md = json.load(open(mf, encoding='utf-8'))
        except ValueError: continue
        rws = md if isinstance(md, list) else md.get('lessons', md.get('sequence', []))
        order = 0
        for row in rws:
            if not isinstance(row, dict) or not isinstance(row.get('file'), str): continue
            f = os.path.relpath(os.path.join(os.path.dirname(mf), row['file']), R); order += 1
            k = row.get('kind') or row.get('phase')
            kinds.setdefault(f, (k, order, mf))
    def declared_classic(p):
        # the hub's own rule (build_science_hub.declared_classic, which cannot be imported because that
        # module builds as it imports): a 'Classic' segment in the head <title>, or lesson-config naming it
        raw = open(P(p), encoding='utf-8', errors='replace').read()
        m = re.search(r'<title>(.*?)</title>', raw, re.S)
        if m and any(seg.strip().lower() == 'classic' for seg in H.unescape(m.group(1)).split('\u00b7')): return True
        m = re.search(r'<script[^>]*id="lesson-config"[^>]*>(.*?)</script>', raw, re.S)
        try: cfg = json.loads(m.group(1)) if m else None
        except ValueError: cfg = None
        if not isinstance(cfg, dict): return False
        word = re.compile(r'(?<![A-Za-z])Classic(?![A-Za-z])')
        if any(isinstance(cfg.get(k), str) and word.search(cfg[k]) for k in ('key', 'prefix', 'title')): return True
        return any(isinstance(st, dict) and st.get('lesson') == 'Classic' for st in (cfg.get('stages') or []))
    def part_from_title_text(text, first_kinds):
        """The part a deck DECLARES on its own title slide -- "Week 9A", "LESSON A", "Lesson 2 of 2",
        "Week 7 · Explore" -- read from that slide's rendered text, never from its path or file name
        (g27: no week from a filename). The caller passes the text; this sees no path."""
        m = re.search(r'\bWeek \d+([AB])\b', text)
        if m: return ('first' if m.group(1).lower() in first_kinds else 'other'), 'title slide "Week n%s"' % m.group(1)
        m = re.search(r'\bLESSON ([AB123])\b|\bLesson ([123]) of [23]\b', text)
        if m:
            tok = (m.group(1) or m.group(2)).lower()
            return ('first' if tok in first_kinds else 'other'), 'title slide "LESSON %s"' % tok.upper()
        m = re.search(r'\bWeek \d+\s*\u00b7\s*(Explore|Introduce|Do)\b', text)
        if m: return ('first' if m.group(1).lower() in first_kinds else 'other'), 'title slide "%s"' % m.group(1)
        return None
    def part_of(p, pathway, cell_members):
        # LAUNCH teaches three lessons a week and its first is the Introduce deck (L1); BUILD and GROW teach
        # two and their first is the Explore deck (A). R1 names both: "the animated Explore/Introduce deck (A / L1)".
        first_kinds = {'introduce', 'l1', 'lesson 1', '1'} if pathway == 'LAUNCH' else {'explore', 'a', 'lesson a'}
        if declared_classic(p): return 'classic', 'declares Classic (head title or lesson-config)'
        k, order, mf = kinds.get(p, (None, None, None))
        if k: return ('first' if k.lower() in first_kinds else 'other'), 'manifest kind %r (%s)' % (k, os.path.relpath(mf, R))
        declared = part_from_title_text(title_slide(p), first_kinds)
        if declared: return declared
        if order is not None:
            same = [q for q in cell_members if q in kinds and kinds[q][2] == mf]
            return ('first' if order == min(kinds[q][1] for q in same) else 'other'), 'manifest row order %d in %s' % (order, os.path.relpath(mf, R))
        return None, 'no declaration found'
    from lxml import html as _lhtml
    def lundy_panels(p):
        # the builder's own count (build_catalogue.py: >= 4 .lundy-grid / .lundy-loop nodes -> 'full-lundy'), read from bytes
        doc = _lhtml.fromstring(open(P(p), 'rb').read())
        return len(doc.xpath('//*[contains(concat(" ",normalize-space(@class)," ")," lundy-grid ") or contains(concat(" ",normalize-space(@class)," ")," lundy-loop ")]'))
    rec_now = set(sel['recommended']); alt_now = set(sel['alternative']); cur_now = set(sel.setdefault('currentSeries', [])); report = []; unread = []
    for slot in hub['slots']:
        if slot['term'] != term or slot['week'] is None: continue
        cell_members = [c['path'] for c in slot['current']]
        parts = {p: part_of(p, slot['pathway'], cell_members) for p in cell_members}
        if any(v[0] is None for v in parts.values()):
            unread.append((slot['pathway'], slot['week'], [p for p, v in parts.items() if v[0] is None])); continue
        firsts = [p for p, v in parts.items() if v[0] == 'first']; classics = [p for p, v in parts.items() if v[0] == 'classic']
        if len(firsts) != 1:
            unread.append((slot['pathway'], slot['week'], 'expected exactly one A / L1 deck, found %d: %s' % (len(firsts), firsts))); continue
        rec = firsts[0]
        for p in cell_members:
            rec_now.discard(p); alt_now.discard(p); sel['recommendedBatches'].pop(p, None)
        rec_now.add(rec); sel['recommendedBatches'][rec] = 'Science · %s · HUB1 R1: the A / L1 deck of the cell is recommended' % TERM_LABEL[term]
        for p in classics: alt_now.add(p)
        # R1: a Do deck (B / L2, L3) is 'Full Lundy Loop' when its bytes earn it (the builder derives that);
        # until its transplant lands, it is 'Current classroom series' by selection, never 'Earlier retained'.
        for p in cell_members:
            if p == rec or p in classics: continue
            if lundy_panels(p) >= 4: cur_now.discard(p)      # the bytes earn 'full-lundy'; the builder derives it
            else: cur_now.add(p)
        report.append((slot['pathway'], slot['week'], rec, parts[rec][1], classics, [p for p in cell_members if p != rec and p not in classics]))
    sel['recommended'] = sorted(rec_now); sel['alternative'] = sorted(alt_now); sel['currentSeries'] = sorted(cur_now)
    print('| pathway | week | recommended (A / L1) | read from | alternative (Classic) | beside (Do decks, style stays derived from bytes) |'); print('|---|---|---|---|---|---|')
    for pw, wk, rec, how, cl, rest in sorted(report, key=lambda r: (['BUILD', 'GROW', 'LAUNCH'].index(r[0]), r[1])):
        print('| %s | W%d | %s | %s | %s | %s |' % (pw, wk, rec.split('/')[-1], how, ', '.join(x.split('/')[-1] for x in cl) or '—', ', '.join(x.split('/')[-1] for x in rest) or '—'))
    for u in unread: print('UNREAD cell, left alone:', u)
    print('\nSHELF_SELECTION: recommended %d · alternative %d · currentSeries %d · cells written %d · cells left alone %d' % (len(sel['recommended']), len(sel['alternative']), len(sel['currentSeries']), len(report), len(unread)))
    W('tools/catalogue/SHELF_SELECTION.json', sel)
    json.dump({'term': term, 'cells': [{'pathway': pw, 'week': wk, 'recommended': rec, 'readFrom': how, 'alternative': cl, 'beside': rest} for pw, wk, rec, how, cl, rest in report], 'unread': unread,
               'recommended': sel['recommended'], 'alternative': sel['alternative']}, open(os.environ.get('RX3_RECOMMENDED_OUT', '/tmp/rx3_recommended.json'), 'w'), indent=1)
    return 1 if unread else 0

if a.science_cells:
    sys.exit(_science_cells(a.science_cells))


# ------------------------------------------------------------------ LAND-A2 (Claude, rulings R1 and R3, 2026-09-25)
# "Science hub: bind each new lesson to its Autumn 2 week from its own evidence (book header term/week,
# LESSON_SOURCE.json), make it Recommended; prior Recommended -> Alternative, keeping order; estate lessons keep
# their bindings; one Recommended per cell." The scope of THE ONE WRITER is widened again rather than a second
# writer added. What it reads and why:
#   * the lesson's OWN declarations, which must agree: its head <title> ("... · BUILD Science Autumn 2 W1"), its
#     hero line ("BUILD · Science · Autumn 2 · Week 1"; LAUNCH W02-W07 write "LAUNCH Science Autumn 2 Wn") and
#     its printed book header ("Science · BUILD · Autumn 2 · Week 01");
#   * the delivery's lesson record, LESSON_SOURCE.json, which R1 moved to _land_a2/<ZIP stem>/ so that it is
#     never served. Its id must equal the page's stem; its term and week must agree; its workbook cell must
#     resolve in _sownb/CALENDAR_SPINE.json to the same Autumn 2 week. The record names the school's workbook,
#     so the cell reference is written only into SCIENCE_WEEK_BINDINGS.json (tools/, never published) and never
#     into a served file: no manifest.json is created for these folders.
# Any disagreement is named and nothing is written. Rows are derived from the page's own hero (<h1> title,
# "I am learning to…" line), never typed (the #638/#639 rule).
def _land_a2(folders):
    TERM_LABEL = {'Aut2': 'Autumn 2'}
    spine = J('_sownb/CALENDAR_SPINE.json'); cells = {x['reference']: x for x in spine['workbookCells']}
    cal = J('_sownb/CALENDAR_2026_27.json')
    def abs_week(tw):
        term, wk = tw.split('·'); n = int(wk[1:]); rule = cal['mapping'][term + '·Wn']
        return n if rule == 'n' else int(rule.split('+')[0]) + n
    records = {}
    for rp in sorted(glob.glob(P('_land_a2/SCI_*/**/LESSON_SOURCE.json'), recursive=True)):
        rec = json.load(open(rp, encoding='utf-8')); records.setdefault(rec['id'], []).append((os.path.relpath(rp, R), rec))
    decl = re.compile(r'\b(BUILD|GROW|LAUNCH)\b(?:\s*·)?\s*Science\s*(?:·\s*)?Autumn\s*2\s*(?:·\s*)?(?:Week\s*|W)0*(\d+)\b')
    book = re.compile(r'Science\s*·\s*(BUILD|GROW|LAUNCH)\s*·\s*Autumn 2\s*·\s*Week\s*0*(\d+)\b')
    cellref = re.compile(r'\b(BUILD|GROW|LAUNCH) Weekly - Autumn!(?:[A-Z]+\d+:)?([A-Z]+\d+)$')
    txt = lambda s: re.sub(r'\s+', ' ', H.unescape(re.sub(r'<[^>]+>', ' ', s))).strip()
    landed, problems = [], []
    for folder in folders:
        for d in sorted(glob.glob(P(folder.rstrip('/') + '/*/'))):
            stem = os.path.basename(os.path.normpath(d)); f = os.path.relpath(os.path.join(d, stem + '.html'), R)
            if not os.path.isfile(P(f)): continue
            raw = open(P(f), encoding='utf-8').read()
            head = title_of(f)
            # the page's first <header> is its hero (the printed book header before it is a div). Three shapes
            # ship: <header class="hero"> with the declaration in a <p> or a <span class="badge"> just above the
            # <h1>, and LAUNCH's <header> with <p class="goal">; the goal reads "I am learning to…", "…to:" or "…to".
            hero = re.search(r'<header\b[^>]*>(.*?)</header>', raw, re.S)
            hero = hero.group(1) if hero else ''
            dm = re.search(r'<(p|span)\b[^>]*>((?:(?!</?\1\b).)*?)</\1>\s*<h1\b', hero, re.S)
            hero_p = txt(dm.group(2)) if dm else ''
            h1 = re.search(r'<h1[^>]*>(.*?)</h1>', hero, re.S); h1 = txt(h1.group(1)) if h1 else ''
            goal = re.search(r'I am learning to(?:…|:)?\s*(?:</strong>)?(.*?)</p>', hero, re.S)
            goal = txt(goal.group(1)) if goal else ''
            said = {'head <title>': decl.search(head), 'hero line': decl.search(hero_p), 'book header': book.search(raw)}
            recs = records.get(stem, [])
            if len(recs) != 1: problems.append('%s: %d LESSON_SOURCE records carry id %s' % (f, len(recs), stem)); continue
            rp, rec = recs[0]
            wk_rec = int(str(rec.get('week', '')).lstrip('W') or 0)
            m = cellref.search(rec.get('sow_cell', '').strip())
            ref = "'%s Weekly - Autumn'!%s" % (m.group(1), m.group(2)) if m else None
            c = cells.get(ref)
            got = {k: (v.group(1), int(v.group(2))) if v else None for k, v in said.items()}
            got['LESSON_SOURCE term/week'] = (rec.get('pathway'), wk_rec) if rec.get('term') == 'Autumn 2' else None
            got['workbook cell ' + str(ref)] = (m.group(1), int(c['termWeek'].split('·W')[1])) if c and c['termWeek'].startswith('Aut2·W') else None
            if None in got.values() or len(set(got.values())) != 1 or not h1:
                problems.append('%s: its own evidence does not agree: %s%s' % (f, got, '' if h1 else ' (no <h1> in the hero)')); continue
            pw, n = next(iter(got.values()))
            landed.append({'path': f, 'pathway': pw, 'week': n, 'title': h1, 'goal': goal, 'head': head, 'hero': hero_p, 'record': rp, 'ref': ref})
    if problems:
        print('REFUSED, nothing written:'); [print('  ' + p) for p in problems]; return 1
    # the cells: today's members from the hub's own record; the previous recommended in each becomes alternative
    sel = J('tools/catalogue/SHELF_SELECTION.json'); sel.setdefault('alternative', []); sel.setdefault('recommendedBatches', {})
    hub = J('assets/catalogue/science-hub-bindings.json')
    members = {(s['pathway'], s['week']): [c['path'] for c in s['current']] for s in hub['slots'] if s['term'] == 'Aut2' and s['week'] is not None}
    rec_now, alt_now = list(sel['recommended']), list(sel['alternative']); report = []
    for L in sorted(landed, key=lambda L: (['BUILD', 'GROW', 'LAUNCH'].index(L['pathway']), L['week'])):
        prior = [p for p in members.get((L['pathway'], L['week']), []) if p in rec_now and p != L['path']]
        for p in prior:
            rec_now.remove(p); sel['recommendedBatches'].pop(p, None)
            if p not in alt_now: alt_now.append(p)
        if L['path'] not in rec_now: rec_now.append(L['path'])
        sel['recommendedBatches'][L['path']] = 'Science · Autumn 2 · LAND-A2: the landed lesson is recommended; the previous recommended is alternative'
        report.append((L['pathway'], L['week'], L['path'], prior, [p for p in members.get((L['pathway'], L['week']), []) if p not in prior]))
    sel['recommended'] = sorted(rec_now); sel['alternative'] = sorted(alt_now)
    have = {x['path'] for x in sel['science']}
    for L in landed:
        if L['path'] not in have:
            # exactly the shape build_catalogue.py emits for these pages (no slide; the head <title> declares the term)
            sel['science'].append({'path': L['path'], 'classificationEvidence': [{'method': 'own title slide declaration', 'source': L['path'], 'quote': L['head']}]})
    W('tools/catalogue/SHELF_SELECTION.json', sel)
    wb = J('tools/catalogue/SCIENCE_WEEK_BINDINGS.json'); ent = wb['entries']
    for L in landed:
        tw = 'Aut2·W%d' % L['week']
        ent[L['path']] = {'pathway': L['pathway'], 'style': 'recommended', 'title': '%s · %s' % (L['pathway'], L['title']),
                          'weeks': [{'key': tw, 'term': 'Aut2', 'weekWithinTerm': L['week'], 'label': 'Autumn 2 · Week %d' % L['week'], 'ruledAbsoluteWeek': abs_week(tw)}],
                          'sourceSha256': sha(L['path']), 'sourceProofUnchanged': True, 'status': 'set',
                          'evidence': [{'method': 'own title slide declaration', 'source': L['path'], 'quote': L['hero'] or L['head']},
                                       {'method': 'delivery lesson record, not served (workbook cell)', 'source': L['record'], 'refs': [L['ref']]}]}
    # entries keep the record's own order (it is not sorted); the landed rows are appended after it
    wb.setdefault('bindingRuns', []).append({'by': 'tools/rx3_recommended.py --land-a2', 'bound': len(landed), 'listed': sorted(L['path'] for L in landed)})
    W('tools/catalogue/SCIENCE_WEEK_BINDINGS.json', wb, indent=1)   # the record's own shape (indent 1), so only the new rows move
    # catalogue rows: after the reviewed appended rows, before the derived companion-pack tail
    rows = J('resources.json'); files = {r['file'] for r in rows}
    pc = 'tools/catalogue/pin_catalogue_contract.py'; src = open(P(pc), encoding='utf-8').read()
    spec = __import__('importlib.util').util.spec_from_file_location('pcc', P(pc)); pcc = __import__('importlib.util').util.module_from_spec(spec); spec.loader.exec_module(pcc)
    at = pcc.ORIGINAL_ROW_COUNT + len(pcc.SHELF_ROWS); new = []
    slug = lambda s: re.sub(r'-+', '-', re.sub(r'[^a-z0-9]+', '-', s.lower())).strip('-')
    for L in sorted(landed, key=lambda L: (['BUILD', 'GROW', 'LAUNCH'].index(L['pathway']), L['week'])):
        if L['path'] in files: continue
        words = [w for w in slug(L['title']).split('-') if len(w) > 2 and w not in ('and', 'the', 'for', 'use')]
        new.append({'subject': 'Science · Teesside', 'title': '%s · %s' % (L['pathway'], L['title']), 'file': L['path'],
                    'id': 'land-a2-sci-%s-a2-w%02d-%s' % (L['pathway'].lower(), L['week'], slug(L['title'])), 'type': 'lesson', 'family': 'Science Teesside',
                    'keywords': [L['pathway'].lower(), 'science', 'autumn 2'] + words,
                    'desc': '%s Science · Autumn 2 · Week %d. I am learning to %s' % (L['pathway'], L['week'], L['goal'][0].lower() + L['goal'][1:] if L['goal'] else L['title']),
                    'added': a.run_date, 'new': True, 'year': '2026-27'})
    rows[at:at] = new
    if not a.dry:
        open(P('resources.json'), 'w', encoding='utf-8').write(json.dumps(rows, ensure_ascii=False, indent=2) + '\n')
        lines = src.rstrip('\n').split('\n'); last = max(i for i, l in enumerate(lines) if l.startswith('SHELF_ROWS.append('))
        add = ['SHELF_ROWS.append(%r)' % r for r in new]
        open(P(pc), 'w', encoding='utf-8').write('\n'.join(lines[:last + 1] + add + lines[last + 1:]) + '\n')
    print('| pathway | week | landed (recommended) | previous recommended -> alternative | other cards, unchanged |'); print('|---|---|---|---|---|')
    for pw, wk, f, prior, rest in report:
        print('| %s | W%d | %s | %s | %s |' % (pw, wk, f.split('/')[-1], ', '.join(p.split('/')[-1] for p in prior) or '— (new cell)', ', '.join(p.split('/')[-1] for p in rest) or '—'))
    print('\nLAND-A2: %d lessons bound from their own evidence · SHELF_SELECTION recommended %d, alternative %d, science %d · resources.json +%d rows at %d (%d total) · SCIENCE_WEEK_BINDINGS %d entries'
          % (len(landed), len(sel['recommended']), len(sel['alternative']), len(sel['science']), len(new), at, len(rows), len(ent)))
    return 0


if a.land_a2:
    sys.exit(_land_a2(a.land_a2))

land = json.load(open(a.land)); pack = json.load(open(a.pack)); pack = pack if isinstance(pack, list) else pack.get('lessons', pack)
pack = {r['id']: r for r in pack}
cal = J('_sownb/CALENDAR_2026_27.json'); ws = cal['weekStarts']
def abs_week(term_week):
    # the ruled calendar's own mapping (Aut1·Wn → n, Aut2·Wn → 8+n, …); never a filename and never the spine's obsolete cell.absoluteWeek
    term, wk = term_week.split('·'); n = int(wk[1:]); rule = cal['mapping'][term + '·Wn']
    return n if rule == 'n' else int(rule.split('+')[0]) + n
spine = J('_sownb/CALENDAR_SPINE.json'); cells = {x['reference']: x for x in spine['workbookCells']}; existing_html = spine['existingHtml']
TERM_LABEL = {'Aut1': 'Autumn 1', 'Aut2': 'Autumn 2', 'Spr1': 'Spring 1', 'Spr2': 'Spring 2', 'Sum1': 'Summer 1', 'Sum2': 'Summer 2'}
sel = J('tools/catalogue/SHELF_SELECTION.json'); sel.setdefault('alternative', []); sel.setdefault('recommendedBatches', {})
rows = J('resources.json'); by_file = {r['file']: r for r in rows}
ORIGINAL = 734
table = []; new_rows = []

def add_row(row):
    if row['file'] in by_file: return
    rows.append(row); by_file[row['file']] = row; new_rows.append(row)

# ------------------------------------------------------------------ subject / family conventions (measured from catalogued siblings)
def subject_family(path):
    top = path.split('/')[0]
    if top == 'Science_Teesside': return 'Science · Teesside', 'Science Teesside'
    if top == 'Humanities_Teesside': return 'Humanities', 'Humanities Teesside'
    if top == 'Art_Teesside': return 'Art · Teesside Studio Suite', 'Art Teesside'
    if top == 'BUILD_ASDAN': return 'BUILD Vocational & PfA', 'BUILD ASDAN · FoodWise' if '/FoodWise/' in path else 'BUILD ASDAN · Autumn 2'
    if top == 'GROW_ASDAN': return 'GROW Vocational & PfA', 'GROW ASDAN · Autumn 2'
    if top == 'LAUNCH_ASDAN': return 'LAUNCH Vocational & PfA', 'LAUNCH ASDAN · Personal Effectiveness'
    if top in ('Build', 'Grow', 'Launch'):
        tier = top.upper(); name = os.path.basename(path)
        if '_HUM_' in name: return 'Humanities', tier + ' · Humanities'
        return ('Arts Award' if tier == 'LAUNCH' else 'Art'), tier + ' · Art & Arts Award'
    raise SystemExit('no subject convention for ' + path)

# ------------------------------------------------------------------ R2: FoodWise, six cells, taught-week rule
fw_manifest = {'pack': 'BUILD ASDAN · FoodWise · the live slot pages and the classic chassis pages, week by week', 'pathway': 'BUILD', 'placement': 'build-engine/lessons/foodwise-aut1-w*.json (slot PfA-FoodWise, Autumn 1 weeks 1–6)',
               'rule': 'R2 taught-week: a week whose Monday is on or before the run date keeps the live slot page it was taught with; a later week recommends the classic chassis page. Both stay served.', 'lessons': []}
for n in range(1, 7):
    live = os.path.relpath(glob.glob(P('BUILD_ASDAN/FoodWise/FW_W%d_*.html' % n))[0], R); chassis = 'BUILD_ASDAN/FoodWise/BUILD_FOOD_W%d.html' % n
    # placement: the build-engine record for the slot (PfA-FoodWise, Autumn 1, week 1) fixes the slot and term; weeks 1–6 are the
    # slot's consecutive workbook cells C130–C135, each re-proved by its own termWeek below.
    if n == 1: eng = J('build-engine/lessons/foodwise-aut1-w1.json'); assert eng['slot'] == 'PfA-FoodWise' and eng['term'] == 'Autumn 1' and eng['week'] == 1, eng['lessonId']
    ref = "'BUILD Weekly - Autumn'!C%d" % (129 + n); c = cells[ref]; assert c['termWeek'] == 'Aut1·W%d' % n, ref; wk = abs_week(c['termWeek'])
    mon = datetime.date.fromisoformat(ws[str(wk)]); started = mon <= RUN
    rec, other = (live, chassis) if started else (chassis, live)
    rule = 'taught-week: Monday %s %s run date %s → %s' % (mon, '≤' if started else '>', RUN, 'LIVE slot page (already taught)' if started else 'CLASSIC chassis page (not yet taught)')
    table.append(('FoodWise W%d · %s (%s)' % (n, ref, c['termWeek']), rec, other, rule))
    t = title_of(chassis)
    add_row({"id": "asdan-fw-chassis-w%d" % n, "subject": "BUILD Vocational & PfA", "type": "lesson", "title": "FoodWise W%d · %s · classic chassis" % (n, t), "file": chassis,
             "family": "BUILD ASDAN · FoodWise", "added": a.run_date, "desc": "Classic-chassis teaching version of FoodWise week %d (%s), served beside the live slot page; the taught-week rule (R2) decides which of the two is recommended." % (n, t),
             "keywords": ["asdan", "foodwise", "build", "week %d" % n, "classic chassis"], "year": "2026-27"})
    cell_row = [{'lane': 'BUILD', 'workbook': '_passsb/inputs/Build SOW 2026-2027.xlsx', 'sheet': 'BUILD Weekly - Autumn', 'cell': c['cell'], 'reference': ref}]
    fw_manifest['lessons'].append({'id': 'BLD-FW-A1-W%d-LIVE' % n, 'week': n, 'version': 'live slot page', 'file': os.path.basename(live), 'title': title_of(live), 'cells': cell_row, 'sow': c['termWeek'], 'workbookOutcome': c.get('verbatimOutcome', '')})
    fw_manifest['lessons'].append({'id': 'BLD-FW-A1-W%d-CLASSIC' % n, 'week': n, 'version': 'classic chassis page', 'file': os.path.basename(chassis), 'title': t, 'cells': cell_row, 'sow': c['termWeek'], 'workbookOutcome': c.get('verbatimOutcome', ''), 'liveSlotPage': os.path.basename(live)})
    sel['recommended'] = [x for x in sel['recommended'] if x not in (live, chassis)] + [rec]
    sel['alternative'] = [x for x in sel['alternative'] if x not in (live, chassis)] + [other]
    sel['recommendedBatches'].pop(other, None); sel['recommendedBatches'][rec] = 'FoodWise · Autumn 1 · taught-week rule'
W('BUILD_ASDAN/FoodWise/manifest.json', fw_manifest)

# the slot hub: every card states its status in text (R2), both versions linked
hub = 'BUILD_ASDAN/FoodWise/START_HERE.html'; src = open(P(hub), encoding='utf-8').read()
m = re.search(r'<!--rx3-grid-->.*?<!--/rx3-grid-->', src, re.S) or re.search(r'<div class="grid">.*?</div>', src, re.S); assert m, 'FoodWise hub grid not found'
cards = []
for (label, rec, other, rule), n in zip(table[:6], range(1, 7)):
    # the card's own words (either the original grid or a previous run of this tool): "<strong>Week n · …</strong><span>…</span>"
    old = re.search(r'<strong>(Week %d · [^<]*)</strong><span>([^<]*)</span>' % n, m.group(0)); assert old, 'FoodWise hub card for week %d not found' % n
    strong, span = old.group(1), old.group(2)
    rec_kind = 'live slot page' if '/FW_W' in rec else 'classic chassis page'; oth_kind = 'classic chassis page' if rec_kind == 'live slot page' else 'live slot page'
    why = 'already taught this week' if rec_kind == 'live slot page' else 'not yet taught'
    cards.append('<div class="week"><a href="%s"><strong>%s</strong><span>%s</span><em class="status">Recommended · %s (%s)</em></a><a class="alt" href="%s"><span>Alternative version · %s</span></a></div>'
                 % (os.path.basename(rec), strong, span, rec_kind, why, os.path.basename(other), oth_kind))
grid = '<!--rx3-grid--><div class="grid" data-rx3-rule="taught-week" data-run-date="%s">' % a.run_date + ''.join(cards) + '</div><!--/rx3-grid-->'
note = ('<div class="note" id="rx3-rule"><b>Which version?</b> Every week has two served versions — the live slot page and the classic chassis page. '
        'A week whose Monday is on or before %s keeps the live page it was taught with; a later week recommends the classic chassis page. '
        'Each card says which is recommended and links the other as an alternative. Nothing is hidden or removed.</div>' % RUN.strftime('%-d %B %Y'))
css = ('.week{display:grid;gap:6px}.week a em.status{display:block;margin-top:8px;font-style:normal;color:#5B9E5B;font-weight:700;font-size:.82rem}'
       '.week a.alt{border-top:7px dashed #5B9E5B;padding:9px 15px}.week a.alt span{color:#eef1f4}')
out = src[:m.start()] + grid + src[m.end():]
out = re.sub(r'<div class="note" id="rx3-rule">.*?</div>\n?', '', out, flags=re.S)
out = out.replace('<!--rx3-grid-->', note + '\n<!--rx3-grid-->', 1)
if '.week{' not in out: out = out.replace('</style>', css + '</style>', 1)
if not a.dry: open(P(hub), 'w', encoding='utf-8').write(out)

# ------------------------------------------------------------------ the landed 33: rows for the new files, R3 standing, Science/Humanities selections
def same_cell_existing(pid):
    refs = ["'%s'!%s" % (pack[pid]['sow']['sheet'], c) for c in pack[pid]['sow']['cells']]
    found = [x['path'] for x in existing_html if any(r in x.get('contentCellReferences', []) for r in refs)]
    for mf in glob.glob(P('**/manifest*.json'), recursive=True):
        try: md = json.load(open(mf, encoding='utf-8'))
        except ValueError: continue
        for row in (md if isinstance(md, list) else md.get('lessons', md.get('sequence', []))):
            if not isinstance(row, dict): continue
            mrefs = row.get('cells') or ([row['cell']] if row.get('cell') else [])
            mrefs = [x.get('reference', '') if isinstance(x, dict) else x for x in mrefs]
            if any(r in mrefs for r in refs):
                f = os.path.relpath(os.path.join(os.path.dirname(mf), row['file']), R)
                if os.path.exists(P(f)) and f not in found: found.append(f)
    return refs, [f for f in found if not f.endswith('_Classic.html')]

science_new = []
for r in land:
    f = r['target']; s, fam = subject_family(f); pid = r['id']
    if r['verdict'] != 'REPLACE':
        p = pack[pid]
        add_row({"id": "classic-33-" + pid.replace('_', '-'), "subject": s, "type": "lesson", "title": title_of(f), "file": f, "family": fam, "added": a.run_date,
                 "desc": "Classic-chassis lesson from the reviewed 33-pack (%s · %s), served beside the existing lesson for the same week; the existing lesson keeps its standing." % (p['pathway'], p['period']),
                 "keywords": ["classic chassis", "33-pack", p['pathway'].lower(), p['subject'].lower(), p['period'].lower()], "year": "2026-27"})
        if f.startswith('Science_Teesside/'):
            science_new.append({'path': f, 'classificationEvidence': [{'method': 'own current title-slide SoW declaration', 'source': f, 'quote': title_slide(f)[:300]}]})
    if r['verdict'].startswith('ADD-BESIDE('):
        refs, ex = same_cell_existing(pid); why = r['verdict'][len('ADD-BESIDE('):-1]
        if f not in sel['alternative']: sel['alternative'].append(f)
        table.append((pid + ' (%s) · ' % why + ', '.join(refs), ', '.join(ex) + ' (existing, standing unchanged)', f, ('R3' if why == 'R3' else 'pinned bytes (cover-pack existing route)') + ': the beside lesson carries alternative'))
for x in science_new:
    if all(y['path'] != x['path'] for y in sel['science']): sel['science'].append(x)
W('tools/catalogue/SHELF_SELECTION.json', sel)

# Science week bindings: the shelf builder asserts each route's source hash and its calendar binding
wb = J('tools/catalogue/SCIENCE_WEEK_BINDINGS.json'); ent = wb['entries']
for r in land:
    f = r['target']
    if not f.startswith('Science_Teesside/'): continue
    if r['verdict'] == 'REPLACE':
        e = ent[f]; e['sourceSha256'] = sha(f); e['reviewed'] = {'date': a.run_date, 'reason': 'RX3 re-cut (REPLACE) from the reviewed 33-pack; the calendar binding is unchanged'}
    else:
        p = pack[r['id']]; refs = ["'%s'!%s" % (p['sow']['sheet'], c) for c in p['sow']['cells']]; c = next(cells[x] for x in refs if x in cells)
        term, wk = c['termWeek'].split('·'); n = int(wk[1:])
        ent[f] = {'pathway': p['pathway'], 'style': 'alternative' if r['verdict'] == 'ADD-BESIDE(R3)' else 'current', 'title': title_of(f),
                  'weeks': [{'key': c['termWeek'], 'term': term, 'weekWithinTerm': n, 'label': '%s · Week %d' % (TERM_LABEL[term], n), 'ruledAbsoluteWeek': abs_week(c['termWeek'])}],
                  'sourceSha256': sha(f), 'sourceProofUnchanged': True, 'status': 'set',
                  'evidence': [{'method': 'own title slide declaration', 'source': f, 'quote': title_slide(f)[:300]}, {'method': 'reviewed pack placement (workbook cell)', 'source': a.pack.split('/')[-1], 'refs': refs, 'period': p['period']}]}
wb['entries'] = dict(sorted(ent.items())); wb['scope'] = wb['scope'].replace('All123', 'All %d' % len(ent)).replace('All 123', 'All %d' % len(ent))
W('tools/catalogue/SCIENCE_WEEK_BINDINGS.json', wb)

# Humanities selection = exactly what the static check derives (declared manifests ∪ Humanities catalogue rows)
hs = J('tools/catalogue/HUMANITIES_SELECTION.json'); have = {x['path'] for x in hs['lessons']}
declared = {}
for row in rows:
    if row.get('subject', '').casefold() == hs['resourcesSubject'].casefold() and row.get('type') != 'hub': declared.setdefault(row['file'], ('resources.json', row['file'], row['type'], row['title']))
for mp in hs['manifestSources']:
    md = J(mp)
    for row in md.get('lessons', md.get('sequence', [])):
        f = os.path.normpath(os.path.join(os.path.dirname(mp), row['file'])); declared.setdefault(f, (mp, row['file'], 'lesson', row.get('title') or title_of(f)))
for f, (source, ident, typ, t) in sorted(declared.items()):
    if f in have: continue
    hs['lessons'].append({'path': f, 'type': typ, 'title': t, 'selectionEvidence': [{'source': source, 'identity': ident}], 'registered': True}); have.add(f)
hs['lessons'] = [x for x in hs['lessons'] if x['path'] in declared]
W('tools/catalogue/HUMANITIES_SELECTION.json', hs)

# ------------------------------------------------------------------ rows: resources.json + the reviewed appended-row list + the gate's row count
if not a.dry:
    open(P('resources.json'), 'w', encoding='utf-8').write(json.dumps(rows, ensure_ascii=False, indent=2) + '\n')
pc = 'tools/catalogue/pin_catalogue_contract.py'; src = open(P(pc), encoding='utf-8').read()
import ast
node = next(n for n in ast.parse(src).body if isinstance(n, ast.Assign) and any(getattr(t, 'id', None) == 'SHELF_ROWS' for t in n.targets))
lines = src.split('\n'); start = sum(len(l) + 1 for l in lines[:node.lineno - 1]); end = sum(len(l) + 1 for l in lines[:node.end_lineno - 1]) + node.end_col_offset
lit = 'SHELF_ROWS = ' + pprint.pformat(rows[ORIGINAL:], width=120, sort_dicts=False)
if not a.dry: open(P(pc), 'w', encoding='utf-8').write(src[:start] + lit + src[end:])
for root in [R] + ([a.apps] if a.apps else []):
    g = os.path.join(root, 'tools/verify_cross_estate_unification.py'); gs = open(g, encoding='utf-8').read()
    gs2, k = re.subn(r'^CATALOGUE_SHELF_ROWS = \d+$', 'CATALOGUE_SHELF_ROWS = %d' % len(rows[ORIGINAL:]), gs, flags=re.M); assert k == 1
    shelf_digest = hashlib.sha256(json.dumps(rows[ORIGINAL:], ensure_ascii=False, separators=(',', ':')).encode('utf-8')).hexdigest()
    gs2, k = re.subn(r'^CATALOGUE_SHELF_ROWS_SHA256 = "[0-9a-f]{64}"$', 'CATALOGUE_SHELF_ROWS_SHA256 = "%s"' % shelf_digest, gs2, flags=re.M); assert k == 1
    if not a.dry and gs2 != gs: open(g, 'w', encoding='utf-8').write(gs2)

# ------------------------------------------------------------------ the hub gate: exactly one recommended per cell, across every hub
def cell_claims(root):
    """cell reference -> set of lesson paths that claim it: every manifest row with cells/cell, the spine's audited readings, the pack placement of the landed 33."""
    claims = {}
    for mf in glob.glob(os.path.join(root, '**/manifest*.json'), recursive=True):
        if any(part.startswith(('.', '_', 'node_modules')) for part in os.path.relpath(mf, root).split(os.sep)): continue
        try: md = json.load(open(mf, encoding='utf-8'))
        except ValueError: continue
        for row in (md if isinstance(md, list) else md.get('lessons', md.get('sequence', []))):
            if not isinstance(row, dict) or not isinstance(row.get('file'), str): continue
            refs = row.get('cells') or ([row['cell']] if row.get('cell') else [])
            f = os.path.relpath(os.path.join(os.path.dirname(mf), row['file']), root)
            for x in refs:
                ref = x.get('reference', '') if isinstance(x, dict) else x
                if ref in cells and os.path.exists(os.path.join(root, f)): claims.setdefault(ref, set()).add(f)
    for x in existing_html:
        for ref in x.get('contentCellReferences', []):
            if ref in cells and os.path.exists(os.path.join(root, x['path'])): claims.setdefault(ref, set()).add(x['path'])
    for r in land:
        p_ = pack[r['id']]
        for ref in ["'%s'!%s" % (p_['sow']['sheet'], c) for c in p_['sow']['cells']]:
            if ref in cells and os.path.exists(os.path.join(root, r['target'])): claims.setdefault(ref, set()).add(r['target'])
    return claims

def hub_gate(root, styles, hub_html):
    """styles: path -> style. Returns (rows, failures)."""
    rows_, fails = [], []
    touched = {r['target'] for r in land} | {f for _, rec_, oth_, _ in table[:6] for f in (rec_, oth_)}  # the files whose standing this transaction sets
    for ref, files in sorted(cell_claims(root).items()):
        rec = sorted(f for f in files if styles.get(f) == 'recommended'); alt = sorted(f for f in files if styles.get(f) == 'alternative')
        if len(files) > 1 or rec or alt: rows_.append((ref, cells[ref]['termWeek'], len(files), rec, alt))
        if len(rec) > 1:
            if files & touched: fails.append('%s: %d recommended (%s)' % (ref, len(rec), ', '.join(rec)))
            else: print('  pre-existing, untouched by this transaction: %s carries %d recommended (%s)' % (ref, len(rec), ', '.join(rec)))
    for n in range(1, 7):
        ref = "'BUILD Weekly - Autumn'!C%d" % (129 + n); files = cell_claims(root).get(ref, set())
        if sum(styles.get(f) == 'recommended' for f in files) != 1: fails.append('%s (FoodWise W%d): expected exactly one recommended, found %d' % (ref, n, sum(styles.get(f) == 'recommended' for f in files)))
    for r in land:
        if r['verdict'].startswith('ADD-BESIDE(') and styles.get(r['target']) != 'alternative': fails.append('%s: beside lesson does not carry alternative (%s)' % (r['target'], styles.get(r['target'])))
    cards = re.findall(r'<div class="week">(.*?)</div>', hub_html, re.S)
    if len(cards) != 6 or any(c.count('Recommended ·') != 1 or c.count('Alternative version') != 1 for c in cards): fails.append('FoodWise hub: every one of the six cards must name exactly one recommended and one alternative version (found %d cards)' % len(cards))
    return rows_, fails

if a.served:
    ts = json.load(open(os.path.join(a.served, 'assets/catalogue/terms-and-styles.json'), encoding='utf-8'))['entries']
    served_styles = {p_: m_['style'] for p_, m_ in ts.items()}
    rows_, fails = hub_gate(a.served, served_styles, open(os.path.join(a.served, 'BUILD_ASDAN/FoodWise/START_HERE.html'), encoding='utf-8').read())
    print('| cell | termWeek | files | recommended | alternative |'); print('|---|---|---|---|---|')
    for ref, tw, n_, rec, alt in rows_: print('| %s | %s | %d | %s | %s |' % (ref, tw, n_, ', '.join(rec) or '—', ', '.join(alt) or '—'))
    print('\nHUB GATE (served tree %s): %s' % (a.served, 'PASS — exactly one recommended per cell' if not fails else 'FAIL\n  ' + '\n  '.join(fails)))
    sys.exit(1 if fails else 0)
local_styles = {p_: 'recommended' for p_ in sel['recommended']}; local_styles.update({p_: 'alternative' for p_ in sel['alternative']})
gate_rows, gate_fails = hub_gate(R, local_styles, out)
print('HUB GATE (this tree): %s' % ('PASS — exactly one recommended per cell' if not gate_fails else 'FAIL\n  ' + '\n  '.join(gate_fails)))
if gate_fails: sys.exit(1)

# ------------------------------------------------------------------ report
print('| cell | recommended | other | rule |'); print('|---|---|---|---|')
for c, rec, oth, rule in table: print('| %s | %s | %s | %s |' % (c, rec, oth, rule))
print('\nSHELF_SELECTION: recommended %d · alternative %d · science routes %d' % (len(sel['recommended']), len(sel['alternative']), len(sel['science'])))
print('resources.json: %d rows (original %d + appended %d; new this run %d) · HUMANITIES_SELECTION %d lessons · SCIENCE_WEEK_BINDINGS %d entries' % (len(rows), ORIGINAL, len(rows) - ORIGINAL, len(new_rows), len(hs['lessons']), len(ent)))
json.dump({'table': table, 'new_rows': [r['file'] for r in new_rows], 'recommended': sel['recommended'], 'alternative': sel['alternative'], 'science_routes': len(sel['science']), 'humanities': len(hs['lessons']), 'rows': len(rows)},
          open(os.environ.get('RX3_RECOMMENDED_OUT', '/tmp/rx3_recommended.json'), 'w'), indent=1)
