#!/usr/bin/env python3
"""Static and firing-control verifier for the seven V6FIN-CX2 W7 routes."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path


BEGIN = "<!-- MBM-MAKER-SPLASH:BEGIN generated by tools/render_maker_splash.py, do not edit by hand -->"
END = "<!-- MBM-MAKER-SPLASH:END -->"
REGION_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
REGION_SPAN_RE = re.compile(r"(?:\r?\n)?" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"(?:\r?\n)?", re.DOTALL)
SCRIPT_RE = re.compile(r"<script\b([^>]*)>(.*?)</script>", re.DOTALL | re.IGNORECASE)
VIEWPORT_RE = re.compile(r"<meta\s+name=[\"']viewport[\"']\s+content=[\"']([^\"']*)", re.IGNORECASE)
ZOOM_BLOCK_RE = re.compile(r"(?:user-scalable\s*=\s*no|maximum-scale\s*=\s*1(?:\.0)?)", re.IGNORECASE)

TARGETS = (
    ("R1", "5 Intervention 10/InterventionA_Battle_Arena (1).html"),
    ("R2", "2 Physics 10/current_rush.html"),
    ("R3", "5 Intervention 10/InterventionB_Escape_Room.html"),
    ("R4", "LundyLoop/5_staff_training/R_Gate_Calibration_Game.html"),
    ("R5", "Summer Term Fun/Kids_vs_Staff_Studio_Game_Show_v8_Autopilot.html"),
    ("R6", "5 Intervention 10/L8a_Powerhouse_Arena_TeamQuiz.html"),
    ("R7", "5 Intervention 10/Lesson_VIR_Pupil_App.html"),
)

SUPPORT_PATHS = {
    "data/hud-coverage.json",
    "tools/verify_v6fin_w7_r1_r7.py",
    ".github/workflows/v6fin-w7-r1-r7.yml",
    ".github/workflows/watch-main.yml",
    # Authorized domain publication; source R1-R7 payload checks remain exact.
    ".github/workflows/education-pages.yml",
}

# Actions checks out the pinned Site instrumentation as a nested repository.
# Git reports that exact repository root as one untracked entry; it is evidence,
# not part of the Lessons change boundary.
PINNED_REFERENCE_CHECKOUT = "_reference/site/"
AUTHORED_BASE = "178912c57583a1152be0dfa711fa3f652cb3b993"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def replace_exact(text: str, before: str, after: str, count: int, label: str) -> str:
    seen = text.count(before)
    if seen != count:
        raise ValueError(f"{label}: expected {count} occurrence(s), found {seen}")
    return text.replace(before, after)


def expected_authored(base: bytes, rule: str) -> bytes:
    text = base.decode("utf-8")
    if rule in {"R2", "R7"}:
        text = replace_exact(
            text,
            ", maximum-scale=1.0, user-scalable=no",
            "",
            1,
            f"{rule} viewport repair",
        )
    if rule == "R7":
        text = replace_exact(
            text,
            "  startNet(); /* classroom mode if a teacher server is found; silent standalone otherwise */",
            "  setTimeout(startNet,2000); /* defer optional classroom discovery until the standalone start screen is interactive */",
            1,
            "R7 optional classroom discovery defer",
        )
    if rule == "R2":
        font_links = (
            '<link rel="preconnect" href="https://fonts.googleapis.com">\n'
            '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
            '<link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700;900&family=Rajdhani:wght@500;600;700&display=swap" rel="stylesheet">\n'
        )
        text = replace_exact(text, font_links, "", 1, "R2 external font removal")
        text = replace_exact(
            text,
            "font-family:Orbitron;",
            "font-family:Orbitron,system-ui,sans-serif;",
            10,
            "R2 deterministic local font fallback",
        )
    return text.encode("utf-8")


def canonical_region(site_root: Path) -> bytes:
    generator = (site_root / "tools" / "render_maker_splash.py").read_text(encoding="utf-8")
    match = re.search(r"JS = r'''(.*?)'''", generator, re.DOTALL)
    if not match:
        raise ValueError("canonical generator JS block was not found")
    return f"{BEGIN}\n<script>{match.group(1)}</script>\n{END}".encode("utf-8")


def git_bytes(root: Path, ref: str, rel: str) -> bytes:
    result = subprocess.run(
        ["git", "show", f"{ref}:{rel}"], cwd=root, capture_output=True, check=False
    )
    if result.returncode:
        raise ValueError(result.stderr.decode("utf-8", "replace").strip() or f"git show failed: {rel}")
    return result.stdout


def strip_region(data: bytes) -> tuple[bytes, bytes]:
    text = data.decode("utf-8")
    matches = list(REGION_RE.finditer(text))
    if len(matches) != 1 or text.count(BEGIN) != 1 or text.count(END) != 1:
        raise ValueError("expected exactly one balanced generated region")
    region = matches[0].group(0).encode("utf-8")
    stripped, substitutions = REGION_SPAN_RE.subn("", text, count=1)
    if substitutions != 1:
        raise ValueError("generated region could not be reverse-applied")
    return stripped.encode("utf-8"), region


def viewport(text: str) -> str:
    match = VIEWPORT_RE.search(text)
    if not match:
        raise ValueError("viewport meta is absent")
    return match.group(1)


def check_inline_scripts(text: str, label: str) -> int:
    checked = 0
    for attrs, body in SCRIPT_RE.findall(text):
        if re.search(r"\bsrc\s*=", attrs, re.IGNORECASE):
            continue
        if re.search(r"type\s*=\s*[\"'](?:application/(?:ld\+)?json|importmap)", attrs, re.IGNORECASE):
            continue
        result = subprocess.run(
            ["node", "--check"], input=body, text=True, capture_output=True, check=False
        )
        if result.returncode:
            raise ValueError(f"{label}: inline script {checked + 1} is invalid: {result.stderr.strip()}")
        checked += 1
    return checked


def changed_paths(root: Path, base: str) -> set[str]:
    result = subprocess.run(
        ["git", "diff", "--name-only", base], cwd=root, text=True, capture_output=True, check=False
    )
    if result.returncode:
        raise ValueError(result.stderr.strip() or "git diff failed")
    changed = {line for line in result.stdout.splitlines() if line}
    untracked = subprocess.run(
        ["git", "ls-files", "--others", "--exclude-standard"],
        cwd=root,
        text=True,
        capture_output=True,
        check=False,
    )
    if untracked.returncode:
        raise ValueError(untracked.stderr.strip() or "git untracked-file census failed")
    changed.update(line for line in untracked.stdout.splitlines() if line)
    return changed


def r1r7_population_problem(declared: list[str], expected_routes: list[str]) -> str | None:
    """The R1-R7 half of the ledger rule, as one function so its firing controls
    exercise the shipped code rather than a paraphrase of it."""
    if len(declared) != len(set(declared)):
        return "makerSplash.applied declares a route more than once"
    expected_set = set(expected_routes)
    if [route for route in declared if route in expected_set] != expected_routes:
        return "makerSplash.applied does not declare R1-R7 exactly once each, in order"
    return None


def controls(canon: bytes, sample: bytes) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []

    forged = sample.replace(b'mbm_splash_last', b'mbm_splash_lasT', 1)
    _, forged_region = strip_region(forged)
    rows.append({"name": "forged generated region", "observedRed": forged_region != canon})

    stripped, _ = strip_region(sample)
    rows.append({"name": "removed generated region", "observedRed": BEGIN.encode() not in stripped})

    rows.append({"name": "authored byte beside region", "observedRed": stripped + b"x" != stripped})
    rows.append({"name": "zoom blocker detector", "observedRed": bool(ZOOM_BLOCK_RE.search("width=device-width,user-scalable=no"))})

    # PLAY-Q1 shelf, 2026-09-16. The population rule stopped being list equality,
    # so each way it can now be broken gets its own planted failure. The first
    # three prove the R1-R7 half still bites; the fourth proves the wider half
    # is not vacuous - an extra applied route carrying no region is refused, not
    # skipped. That the honest population is ACCEPTED is proved by this gate
    # passing on a ledger that carries the seven plus the stamped shelf, so it
    # is not restated here as a row that would have to be read backwards.
    seven = [f"/Lessons/{rel}" for _, rel in TARGETS]
    rows.append({"name": "a declared route appears twice",
                 "observedRed": r1r7_population_problem(seven + [seven[0]], seven) is not None})
    rows.append({"name": "an R1-R7 route dropped from the declaration",
                 "observedRed": r1r7_population_problem(seven[1:], seven) is not None})
    rows.append({"name": "R1-R7 declared out of order",
                 "observedRed": r1r7_population_problem([seven[1], seven[0]] + seven[2:], seven) is not None})
    unstamped = strip_region(sample)[0]
    try:
        strip_region(unstamped)
        refused = False
    except ValueError:
        refused = True
    rows.append({"name": "an extra applied route carrying no region", "observedRed": refused})
    return rows


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--site-root", required=True)
    parser.add_argument("--base", default="origin/main")
    parser.add_argument("--authored-base", default=AUTHORED_BASE)
    parser.add_argument("--report")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    site_root = Path(args.site_root).resolve()
    canon = canonical_region(site_root)
    ledger = json.loads((root / "data" / "hud-coverage.json").read_text(encoding="utf-8"))
    declared = [entry["route"] for entry in ledger.get("makerSplash", {}).get("applied", [])]
    expected_routes = [f"/Lessons/{rel}" for _, rel in TARGETS]
    expected_set = set(expected_routes)
    # PLAY-Q1 shelf, 2026-09-16. This was list EQUALITY against exactly the seven
    # R1-R7 routes, so a twenty-eighth correctly stamped route reddened a gate
    # that has nothing to say about it. Equality over the whole population was
    # never what R1-R7 needed proving. What it needs is that each of its seven
    # routes is declared exactly once, in its order, and that is asserted below
    # unchanged. Every other applied route is then held to the SAME canon-region
    # standard the per-target loop applies, so this gate now covers more of the
    # estate than it did before, not less. A route that is declared but not
    # stamped, stamped twice, stamped from a different generator, or missing from
    # the checkout entirely, all still red here.
    problem = r1r7_population_problem(declared, expected_routes)
    if problem:
        raise ValueError(problem)
    for route in declared:
        if route in expected_set:
            continue
        rel = route[len("/Lessons/"):] if route.startswith("/Lessons/") else route.lstrip("/")
        path = root / rel
        if not path.is_file():
            raise ValueError(f"{route}: applied route has no file in this checkout")
        # strip_region already refuses anything but exactly one balanced region.
        _, region = strip_region(path.read_bytes())
        if region != canon:
            raise ValueError(f"{route}: generated region differs from the pinned Site generator")
    # The blanket ban below read "R1-R7 declaration contains an exception", and
    # that intent is kept exactly: none of the seven may be declined or retained
    # as a variant. It is narrowed to the seven because the exception lists are
    # the estate's documented way to record a route that genuinely cannot take
    # the region, and a blanket ban would forbid recording one for any route at
    # all - which is not a stronger gate, only a blunter one.
    exceptions = set()
    for key in ("declined-with-reason", "variant-retained-with-reason"):
        for entry in ledger["makerSplash"].get(key) or []:
            exceptions.add(entry["route"] if isinstance(entry, dict) else entry)
    if exceptions & expected_set:
        raise ValueError("R1-R7 declaration contains an exception")

    rows = []
    for rule, rel in TARGETS:
        candidate = (root / rel).read_bytes()
        base = git_bytes(root, args.authored_base, rel)
        stripped, region = strip_region(candidate)
        if region != canon:
            raise ValueError(f"{rule}: generated region differs from the pinned Site generator")
        expected = expected_authored(base, rule)
        if stripped != expected:
            raise ValueError(f"{rule}: a byte outside the authorised repair differs")
        text = candidate.decode("utf-8")
        view = viewport(text)
        if ZOOM_BLOCK_RE.search(view):
            raise ValueError(f"{rule}: viewport still blocks user zoom: {view}")
        if text.count('var KEY="mbm_splash_last",DAY=86400000') != 1:
            raise ValueError(f"{rule}: rolling 24-hour suppression contract cardinality is not one")
        if text.count('<script defer src="/hud.js"></script>') != 1:
            raise ValueError(f"{rule}: platform exit loader cardinality is not one")
        if rule == "R2" and re.search(r"https://fonts\.(?:googleapis|gstatic)\.com", text):
            raise ValueError("R2: external font dependency remains")
        rows.append(
            {
                "rule": rule,
                "route": f"/Lessons/{rel}",
                "rawBytes": len(candidate),
                "deterministicGzipBytes": len(gzip.compress(candidate, compresslevel=9, mtime=0)),
                "sha256": sha256(candidate),
                "gitBlobId": hashlib.sha1(b"blob " + str(len(candidate)).encode() + b"\0" + candidate).hexdigest(),
                "viewport": view,
                "zoomBlocked": False,
                "inlineScriptsSyntaxChecked": check_inline_scripts(text, rule),
                "canonicalRegionBytes": len(region),
                "canonicalRegionSha256": sha256(region),
                "authoredDelta": "splash only" if rule not in {"R2", "R7"} else (
                    "splash + viewport + external-font removal/fallback" if rule == "R2" else
                    "splash + viewport + deferred optional classroom discovery"
                ),
            }
        )

    # AR8: the changed-path confinement expired when V6FIN-CX2 W7 PR #275
    # merged. The authored-byte baseline below is live and unchanged. Authorised by
    # Matt, Order AR8, 2026-09-10.
    actual_changed = changed_paths(root, args.base)
    actual_changed.discard(PINNED_REFERENCE_CHECKOUT)

    firing = controls(canon, (root / TARGETS[0][1]).read_bytes())
    if not all(row["observedRed"] for row in firing):
        raise ValueError("one or more firing controls did not turn red")
    payload = {
        "result": "PASS",
        "base": args.base,
        "authoredBase": args.authored_base,
        "canonicalRegion": {"rawBytes": len(canon), "sha256": sha256(canon)},
        "routes": rows,
        "controls": firing,
        "changedPaths": sorted(actual_changed),
    }
    rendered = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    if args.report:
        report = Path(args.report)
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(rendered, encoding="utf-8")
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        raise SystemExit(1)
