#!/usr/bin/env python3
"""Pin the explicitly reviewed education catalogue in both estate gate copies.

This is a deliberate review operation, never a CI repair. The row-preservation
check is independent of the moved digest: re-pinning cannot hide a removed,
reordered or rewritten original resource. Run builders and QA before this tool.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import re

GATE = "tools/verify_cross_estate_unification.py"
ORIGINAL_ROW_COUNT = 734
ORIGINAL_ROWS_SHA256 = "b8ffcb16f5fd2a413e8a0b06ad2d4b112f450364fa294377869dc32c8235bb2c"
SHELF_ROWS = [{'subject': 'Science · Teesside',
  'title': 'Science · browse by pathway, term and teaching version',
  'file': 'Science_Teesside/index.html',
  'id': 'science-pathway-term-hub',
  'type': 'hub',
  'family': 'Science Teesside',
  'keywords': ['science', 'build', 'grow', 'launch', 'pathway', 'term', 'lesson hub'],
  'desc': 'Choose a Science pathway and term, then browse the recommended sequence and retained teaching versions.',
  'added': '2026-09-05',
  'new': True,
  'year': '2026-27'},
 {'subject': 'Humanities · Teesside',
  'title': 'Humanities · browse by pathway, term and teaching version',
  'file': 'Humanities_Teesside/index.html',
  'id': 'humanities-pathway-term-hub',
  'type': 'hub',
  'family': 'Humanities Teesside',
  'keywords': ['humanities', 'religious education', 'build', 'grow', 'launch', 'pathway', 'term', 'lesson hub'],
  'desc': 'Choose a Humanities pathway and term, then browse current lessons, retained teaching versions and classroom '
          'references.',
  'added': '2026-09-05',
  'new': True,
  'year': '2026-27'},
 {'subject': 'Humanities · Teesside',
  'title': 'Humanities and RE cover pack · Autumn 1 Weeks 3–7',
  'file': 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/index.html',
  'id': 'david-humanities-re-cover-hub',
  'type': 'hub',
  'family': 'Humanities Teesside',
  'keywords': ['humanities',
               'religious education',
               'david',
               'cover',
               'build',
               'grow',
               'launch',
               'autumn 1',
               'weeks 3–7',
               'downloads'],
  'desc': 'Twenty-five 40-minute cover periods with PowerPoint, Word and PDF downloads, linked to the existing '
          'Humanities and RE lessons.',
  'added': '2026-09-05',
  'new': True,
  'year': '2026-27'},
 {'subject': 'Humanities · Teesside',
  'title': 'BUILD Humanities teaching pack · Autumn 1 Weeks 3–7 · World About Me',
  'file': 'Humanities_Teesside/Teaching_Packs/index.html#build',
  'id': 'humanities-teaching-pack-build-autumn1',
  'type': 'hub',
  'family': 'Humanities Teesside',
  'keywords': ['humanities', 'build', 'teaching pack', 'powerpoint', 'word', 'pdf', 'autumn 1', 'world about me'],
  'desc': 'Editable BUILD Humanities lessons for Autumn 1 Weeks 3–7 (World About Me): PowerPoint decks, pupil and '
          'teacher Word resources and print-ready PDFs, with a Start Here guide and matching classroom lesson links.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'Humanities · Teesside',
  'title': 'GROW Humanities teaching pack · Autumn 1 Weeks 3–7 · Black British History',
  'file': 'Humanities_Teesside/Teaching_Packs/index.html#grow',
  'id': 'humanities-teaching-pack-grow-autumn1',
  'type': 'hub',
  'family': 'Humanities Teesside',
  'keywords': ['humanities', 'grow', 'teaching pack', 'powerpoint', 'word', 'pdf', 'autumn 1', 'black british history'],
  'desc': 'Editable GROW Humanities lessons for Autumn 1 Weeks 3–7 (Black British History): PowerPoint decks, pupil '
          'and teacher Word resources and print-ready PDFs, with a Start Here guide and matching classroom lesson '
          'links.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'Humanities · Teesside',
  'title': 'LAUNCH Humanities teaching pack · Autumn 1 Weeks 3–7 · Britain in the Twentieth Century',
  'file': 'Humanities_Teesside/Teaching_Packs/index.html#launch',
  'id': 'humanities-teaching-pack-launch-autumn1',
  'type': 'hub',
  'family': 'Humanities Teesside',
  'keywords': ['humanities',
               'launch',
               'teaching pack',
               'powerpoint',
               'word',
               'pdf',
               'autumn 1',
               'britain in the twentieth century'],
  'desc': 'Editable LAUNCH Humanities lessons for Autumn 1 Weeks 3–7 (Britain in the Twentieth Century): PowerPoint '
          'decks, pupil and teacher Word resources and print-ready PDFs, with a Start Here guide and matching '
          'classroom lesson links.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'Science · Teesside',
  'title': 'BUILD Science teaching pack · Autumn 1 Weeks 3–7',
  'file': 'Science_Teesside/Teaching_Packs/index.html#build',
  'id': 'science-teaching-pack-build-autumn1',
  'type': 'hub',
  'family': 'Science Teesside',
  'keywords': ['science', 'build', 'teaching pack', 'powerpoint', 'word', 'pdf', 'autumn 1'],
  'desc': 'Editable BUILD Science lessons for Autumn 1 Weeks 3–7: PowerPoint decks, pupil resources and teacher '
          'guidance as PowerPoint, Word and PDF downloads.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'Science · Teesside',
  'title': 'GROW Science teaching pack · Autumn 1 Weeks 3–7',
  'file': 'Science_Teesside/Teaching_Packs/index.html#grow',
  'id': 'science-teaching-pack-grow-autumn1',
  'type': 'hub',
  'family': 'Science Teesside',
  'keywords': ['science', 'grow', 'teaching pack', 'powerpoint', 'word', 'pdf', 'autumn 1'],
  'desc': 'Editable GROW Science lessons for Autumn 1 Weeks 3–7: PowerPoint decks, pupil resources and teacher '
          'guidance as PowerPoint, Word and PDF downloads.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'Science · Teesside',
  'title': 'LAUNCH Science teaching pack · Autumn 1 Weeks 3–7',
  'file': 'Science_Teesside/Teaching_Packs/index.html#launch',
  'id': 'science-teaching-pack-launch-autumn1',
  'type': 'hub',
  'family': 'Science Teesside',
  'keywords': ['science', 'launch', 'teaching pack', 'powerpoint', 'word', 'pdf', 'autumn 1'],
  'desc': 'Editable LAUNCH Science lessons for Autumn 1 Weeks 3–7: PowerPoint decks, pupil resources and teacher '
          'guidance as PowerPoint, Word and PDF downloads.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'BUILD Vocational & PfA',
  'title': 'BUILD Careers teaching pack · Autumn 1 Weeks 1–7',
  'file': 'Careers/Teaching_Packs/index.html#build',
  'id': 'careers-teaching-pack-build-autumn1',
  'type': 'hub',
  'family': 'Careers',
  'keywords': ['careers',
               'build',
               'teaching pack',
               'powerpoint',
               'word',
               'pdf',
               'offline html',
               'careers',
               'my journey',
               'skills',
               'profile'],
  'desc': 'HTML lessons using the established Made by Matt classroom chassis and pathway colours. Editable PowerPoint '
          'teaching decks and matching slide PDFs.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'GROW Vocational & PfA',
  'title': 'GROW Careers teaching pack · Autumn 1 Weeks 1–7',
  'file': 'Careers/Teaching_Packs/index.html#grow',
  'id': 'careers-teaching-pack-grow-autumn1',
  'type': 'hub',
  'family': 'Careers',
  'keywords': ['careers',
               'grow',
               'teaching pack',
               'powerpoint',
               'word',
               'pdf',
               'offline html',
               'careers',
               'evidence',
               'career families',
               'profile'],
  'desc': 'HTML lessons using the established Made by Matt classroom chassis and pathway colours. Editable PowerPoint '
          'teaching decks and matching slide PDFs.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'GROW Vocational & PfA',
  'title': 'GROW ICT teaching pack · Autumn 1 Weeks 1–7',
  'file': 'ICT/Teaching_Packs/index.html#grow',
  'id': 'ict-teaching-pack-grow-autumn1',
  'type': 'hub',
  'family': 'ICT',
  'keywords': ['ict',
               'grow',
               'teaching pack',
               'powerpoint',
               'word',
               'pdf',
               'offline html',
               'ict',
               'computing',
               'documents',
               'spreadsheets',
               'starter files'],
  'desc': 'HTML lessons using the established Made by Matt classroom chassis and pathway colours. Editable PowerPoint '
          'teaching decks and matching slide PDFs.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'BUILD Vocational & PfA',
  'title': 'BUILD Textiles teaching pack · Autumn 1 Weeks 5–7',
  'file': 'DT_Textiles/Teaching_Packs/index.html#build',
  'id': 'textiles-teaching-pack-build-autumn1',
  'type': 'hub',
  'family': 'DT Textiles',
  'keywords': ['textiles',
               'build',
               'teaching pack',
               'powerpoint',
               'word',
               'pdf',
               'offline html',
               'textiles',
               'design technology',
               'pocket',
               'pattern'],
  'desc': 'HTML lessons using the established Made by Matt classroom chassis and pathway colours. Editable PowerPoint '
          'teaching decks and matching slide PDFs. Weeks 5 and 6 adapt the supplied lessons. Week 7 is newly authored '
          'from the GROW sequence, with BUILD adaptations based on the shared BUILD/GROW source lessons.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'GROW Vocational & PfA',
  'title': 'GROW Textiles teaching pack · Autumn 1 Weeks 5–7',
  'file': 'DT_Textiles/Teaching_Packs/index.html#grow',
  'id': 'textiles-teaching-pack-grow-autumn1',
  'type': 'hub',
  'family': 'DT Textiles',
  'keywords': ['textiles',
               'grow',
               'teaching pack',
               'powerpoint',
               'word',
               'pdf',
               'offline html',
               'textiles',
               'design technology',
               'pocket',
               'pattern'],
  'desc': 'HTML lessons using the established Made by Matt classroom chassis and pathway colours. Editable PowerPoint '
          'teaching decks and matching slide PDFs. Weeks 5 and 6 adapt the supplied lessons. Week 7 is newly authored '
          'from the GROW sequence, with BUILD adaptations based on the shared BUILD/GROW source lessons.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'BUILD Vocational & PfA',
  'title': 'BUILD FoodWise teaching pack · Autumn 1 Weeks 1–6',
  'file': 'BUILD_ASDAN/FoodWise/Teaching_Packs/index.html#build',
  'id': 'foodwise-teaching-pack-build-autumn1',
  'type': 'hub',
  'family': 'FoodWise',
  'keywords': ['foodwise',
               'build',
               'teaching pack',
               'powerpoint',
               'word',
               'pdf',
               'offline html',
               'foodwise',
               'food',
               'safety',
               'labels',
               'recipe'],
  'desc': 'Six existing BUILD FoodWise topics, with updated safety, labels, practical recipe support and evaluation.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'GROW Vocational & PfA',
  'title': 'GROW FoodWise teaching pack · Autumn 1 Weeks 1–4',
  'file': 'GROW_FoodWise/Teaching_Packs/index.html#grow',
  'id': 'foodwise-teaching-pack-grow-autumn1',
  'type': 'hub',
  'family': 'FoodWise',
  'keywords': ['foodwise',
               'grow',
               'teaching pack',
               'powerpoint',
               'word',
               'pdf',
               'offline html',
               'foodwise',
               'food',
               'design technology'],
  'desc': 'Four FoodWise lessons matching the uploaded D&T Weeks 1-4 and the current GROW D&T sequence.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'subject': 'PSHE & ASDAN',
  'title': 'GROW PSHE teaching pack · All About Me · Weeks 1–7',
  'file': 'PSHE/Teaching_Packs/index.html#grow',
  'id': 'pshe-teaching-pack-grow-all-about-me',
  'type': 'hub',
  'family': 'PSHE',
  'keywords': ['pshe',
               'grow',
               'teaching pack',
               'powerpoint',
               'word',
               'pdf',
               'offline html',
               'pshe',
               'all about me',
               'personal development',
               'strengths'],
  'desc': 'Seven original GROW lessons adapted from the uploaded All About Me sequence.',
  'added': '2026-09-07',
  'new': True,
  'year': '2026-27'},
 {'id': 'asdan-fw-chassis-w1',
  'subject': 'BUILD Vocational & PfA',
  'type': 'lesson',
  'title': 'FoodWise W1 · Food Groups · classic chassis',
  'file': 'BUILD_ASDAN/FoodWise/BUILD_FOOD_W1.html',
  'family': 'BUILD ASDAN · FoodWise',
  'added': '2026-09-07',
  'desc': 'Classic-chassis teaching version of FoodWise week 1 (Food Groups), served beside the live slot page; the '
          'taught-week rule (R2) decides which of the two is recommended.',
  'keywords': ['asdan', 'foodwise', 'build', 'week 1', 'classic chassis'],
  'year': '2026-27'},
 {'id': 'asdan-fw-chassis-w2',
  'subject': 'BUILD Vocational & PfA',
  'type': 'lesson',
  'title': 'FoodWise W2 · A Balanced Plate · classic chassis',
  'file': 'BUILD_ASDAN/FoodWise/BUILD_FOOD_W2.html',
  'family': 'BUILD ASDAN · FoodWise',
  'added': '2026-09-07',
  'desc': 'Classic-chassis teaching version of FoodWise week 2 (A Balanced Plate), served beside the live slot page; '
          'the taught-week rule (R2) decides which of the two is recommended.',
  'keywords': ['asdan', 'foodwise', 'build', 'week 2', 'classic chassis'],
  'year': '2026-27'},
 {'id': 'asdan-fw-chassis-w3',
  'subject': 'BUILD Vocational & PfA',
  'type': 'lesson',
  'title': 'FoodWise W3 · Reading Labels · classic chassis',
  'file': 'BUILD_ASDAN/FoodWise/BUILD_FOOD_W3.html',
  'family': 'BUILD ASDAN · FoodWise',
  'added': '2026-09-07',
  'desc': 'Classic-chassis teaching version of FoodWise week 3 (Reading Labels), served beside the live slot page; the '
          'taught-week rule (R2) decides which of the two is recommended.',
  'keywords': ['asdan', 'foodwise', 'build', 'week 3', 'classic chassis'],
  'year': '2026-27'},
 {'id': 'asdan-fw-chassis-w4',
  'subject': 'BUILD Vocational & PfA',
  'type': 'lesson',
  'title': 'FoodWise W4 · Kitchen hygiene and safety · classic chassis',
  'file': 'BUILD_ASDAN/FoodWise/BUILD_FOOD_W4.html',
  'family': 'BUILD ASDAN · FoodWise',
  'added': '2026-09-07',
  'desc': 'Classic-chassis teaching version of FoodWise week 4 (Kitchen hygiene and safety), served beside the live '
          'slot page; the taught-week rule (R2) decides which of the two is recommended.',
  'keywords': ['asdan', 'foodwise', 'build', 'week 4', 'classic chassis'],
  'year': '2026-27'},
 {'id': 'asdan-fw-chassis-w5',
  'subject': 'BUILD Vocational & PfA',
  'type': 'lesson',
  'title': 'FoodWise W5 · Prepare a snack and drink · classic chassis',
  'file': 'BUILD_ASDAN/FoodWise/BUILD_FOOD_W5.html',
  'family': 'BUILD ASDAN · FoodWise',
  'added': '2026-09-07',
  'desc': 'Classic-chassis teaching version of FoodWise week 5 (Prepare a snack and drink), served beside the live '
          'slot page; the taught-week rule (R2) decides which of the two is recommended.',
  'keywords': ['asdan', 'foodwise', 'build', 'week 5', 'classic chassis'],
  'year': '2026-27'},
 {'id': 'asdan-fw-chassis-w6',
  'subject': 'BUILD Vocational & PfA',
  'type': 'lesson',
  'title': 'FoodWise W6 · Plan a meal to a brief · classic chassis',
  'file': 'BUILD_ASDAN/FoodWise/BUILD_FOOD_W6.html',
  'family': 'BUILD ASDAN · FoodWise',
  'added': '2026-09-07',
  'desc': 'Classic-chassis teaching version of FoodWise week 6 (Plan a meal to a brief), served beside the live slot '
          'page; the taught-week rule (R2) decides which of the two is recommended.',
  'keywords': ['asdan', 'foodwise', 'build', 'week 6', 'classic chassis'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-build-science-materials',
  'subject': 'Science · Teesside',
  'type': 'lesson',
  'title': 'Where did this material come from? · BUILD Science',
  'file': 'Science_Teesside/Build/W8-W13_2026-27/SCI_B_W13_Where_did_this_material_come_from_Classic.html',
  'family': 'Science Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (BUILD · Autumn 2 · Week 5), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'build', 'science', 'autumn 2 · week 5'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-build-science-rock-uses',
  'subject': 'Science · Teesside',
  'type': 'lesson',
  'title': 'Give a rock a job · BUILD Science',
  'file': 'Science_Teesside/Build/W8-W13_2026-27/SCI_B_W12_Give_a_rock_a_job_Classic.html',
  'family': 'Science Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (BUILD · Autumn 2 · Week 4), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'build', 'science', 'autumn 2 · week 4'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-grow-science-climate',
  'subject': 'Science · Teesside',
  'type': 'lesson',
  'title': 'Follow the warming chain · GROW Science',
  'file': 'Science_Teesside/Grow/W8-W13_2026-27/SCI_G_W12_Follow_the_warming_chain_Classic.html',
  'family': 'Science Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (GROW · Autumn 2 · Week 4), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'grow', 'science', 'autumn 2 · week 4'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-grow-science-day-night',
  'subject': 'Science · Teesside',
  'type': 'lesson',
  'title': 'Turn Earth, explain the sky · GROW Science',
  'file': 'Science_Teesside/Grow/W8-W13_2026-27/SCI_G_W9_Turn_Earth_explain_the_sky_Classic.html',
  'family': 'Science Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (GROW · Autumn 2 · Week 1), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'grow', 'science', 'autumn 2 · week 1'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-launch-science-dna',
  'subject': 'Science · Teesside',
  'type': 'lesson',
  'title': 'Zoom into genetic information · LAUNCH Science',
  'file': 'Science_Teesside/Launch/W8-W13_2026-27/SCI_L_W12_Zoom_into_genetic_information_Classic.html',
  'family': 'Science Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (LAUNCH · Autumn 2 · Week 4), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'launch', 'science', 'autumn 2 · week 4'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-launch-science-mitosis',
  'subject': 'Science · Teesside',
  'type': 'lesson',
  'title': 'Copy, separate, divide · LAUNCH Science',
  'file': 'Science_Teesside/Launch/W8-W13_2026-27/SCI_L_W9_Copy_separate_divide_Classic.html',
  'family': 'Science Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (LAUNCH · Autumn 2 · Week 1), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'launch', 'science', 'autumn 2 · week 1'],
  'year': '2026-27'},
 {'id': 'classic-33-build-humanities-belonging',
  'subject': 'Humanities',
  'type': 'lesson',
  'title': 'A place in the group · BUILD Humanities',
  'file': 'Humanities_Teesside/BUILD_W1-W8_2026-27/BUILD_HUM_W7_A_place_in_the_group_Classic.html',
  'family': 'Humanities Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (BUILD · Autumn 1 · Week 7), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'build', 'humanities', 'autumn 1 · week 7'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-build-humanities-celebration-order',
  'subject': 'Humanities',
  'type': 'lesson',
  'title': 'A celebration in order · BUILD Humanities',
  'file': 'Humanities_Teesside/BUILD_W14-W20_2026-27/BUILD_HUM_W12_A_celebration_in_order_Classic.html',
  'family': 'Humanities Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (BUILD · Autumn 2 · Week 4), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'build', 'humanities', 'autumn 2 · week 4'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-build-humanities-fair-chance',
  'subject': 'Humanities',
  'type': 'lesson',
  'title': 'A fair chance to join in · BUILD Humanities',
  'file': 'Humanities_Teesside/BUILD_W14-W20_2026-27/BUILD_HUM_W14_A_fair_chance_to_join_in_Classic.html',
  'family': 'Humanities Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (BUILD · Autumn 2 · Week 6), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'build', 'humanities', 'autumn 2 · week 6'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-grow-humanities-compare-celebrations',
  'subject': 'Humanities',
  'type': 'lesson',
  'title': 'Compare celebrations with care · GROW Humanities',
  'file': 'Humanities_Teesside/GROW_W9-W14_2026-27/GROW_HUM_W13_Compare_celebrations_with_care_Classic.html',
  'family': 'Humanities Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (GROW · Autumn 2 · Week 5), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'grow', 'humanities', 'autumn 2 · week 5'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-grow-humanities-festivals-places',
  'subject': 'Humanities',
  'type': 'lesson',
  'title': 'Festival lights across places · GROW Humanities',
  'file': 'Humanities_Teesside/GROW_W9-W14_2026-27/GROW_HUM_W12_Festival_lights_across_places_Classic.html',
  'family': 'Humanities Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (GROW · Autumn 2 · Week 4), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'grow', 'humanities', 'autumn 2 · week 4'],
  'year': '2026-27'},
 {'id': 'classic-33-launch-humanities-archive',
  'subject': 'Humanities',
  'type': 'lesson',
  'title': 'Can this record prove it? · LAUNCH Humanities',
  'file': 'Humanities_Teesside/LAUNCH_W1-W8_2026-27/LAUNCH_HUM_W3_Can_this_record_prove_it_Classic.html',
  'family': 'Humanities Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (LAUNCH · Autumn 1 · Week 3), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'launch', 'humanities', 'autumn 1 · week 3'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-launch-humanities-settlement-change',
  'subject': 'Humanities',
  'type': 'lesson',
  'title': 'A growing town, an urbanising region? · LAUNCH Humanities',
  'file': 'Humanities_Teesside/LAUNCH_W9-W14_2026-27/LAUNCH_HUM_W11_A_growing_town_an_urbanising_region_Classic.html',
  'family': 'Humanities Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (LAUNCH · Autumn 2 · Week 3), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'launch', 'humanities', 'autumn 2 · week 3'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-launch-humanities-grid-references',
  'subject': 'Humanities',
  'type': 'lesson',
  'title': 'Find it with a grid reference · LAUNCH Humanities',
  'file': 'Launch/Slideshows/LAUNCH_HUM_W9_Find_it_with_a_grid_reference_Classic.html',
  'family': 'LAUNCH · Humanities',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (LAUNCH · Autumn 2 · Week 1), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'launch', 'humanities', 'autumn 2 · week 1'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-build-art-light-study',
  'subject': 'Art · Teesside Studio Suite',
  'type': 'lesson',
  'title': 'Light on a dark page · BUILD Creative Arts',
  'file': 'Art_Teesside/BUILD_W1-W8_2026-27/BUILD_Art_W11_Light_on_a_dark_page_Classic.html',
  'family': 'Art Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (BUILD · Autumn 2 · Week 3), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'build', 'creative arts', 'autumn 2 · week 3'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-build-art-steady-beat',
  'subject': 'Art',
  'type': 'lesson',
  'title': 'Our four-beat part · BUILD Creative Arts',
  'file': 'Build/Slideshows/BUILD_ART_W10_Our_four_beat_part_Classic.html',
  'family': 'BUILD · Art & Arts Award',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (BUILD · Autumn 2 · Week 2), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'build', 'creative arts', 'autumn 2 · week 2'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-grow-art-group-part',
  'subject': 'Art',
  'type': 'lesson',
  'title': 'Hold your part · GROW Creative Arts',
  'file': 'Grow/Slideshows/GROW_ART_W10_Hold_your_part_Classic.html',
  'family': 'GROW · Art & Arts Award',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (GROW · Autumn 2 · Week 2), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'grow', 'creative arts', 'autumn 2 · week 2'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-grow-art-light-study',
  'subject': 'Art · Teesside Studio Suite',
  'type': 'lesson',
  'title': 'Design a light festival panel · GROW Creative Arts',
  'file': 'Art_Teesside/GROW_W1-W8_2026-27/GROW_Art_W11_Design_a_light_festival_panel_Classic.html',
  'family': 'Art Teesside',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (GROW · Autumn 2 · Week 3), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'grow', 'creative arts', 'autumn 2 · week 3'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-launch-art-identity-culture',
  'subject': 'Arts Award',
  'type': 'lesson',
  'title': 'Whose meaning is it? · LAUNCH Creative Arts',
  'file': 'Launch/Slideshows/LAUNCH_ART_W10_Whose_meaning_is_it_Classic.html',
  'family': 'LAUNCH · Art & Arts Award',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (LAUNCH · Autumn 2 · Week 2), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'launch', 'creative arts', 'autumn 2 · week 2'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-launch-art-portfolio-piece',
  'subject': 'Arts Award',
  'type': 'lesson',
  'title': 'Develop the piece, keep the decisions · LAUNCH Creative Arts',
  'file': 'Launch/Slideshows/LAUNCH_ART_W11_Develop_the_piece_keep_the_decisions_Classic.html',
  'family': 'LAUNCH · Art & Arts Award',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (LAUNCH · Autumn 2 · Week 3), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'launch', 'creative arts', 'autumn 2 · week 3'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-build-asdan-helpful-plan',
  'subject': 'BUILD Vocational & PfA',
  'type': 'lesson',
  'title': 'A small plan that helps · BUILD ASDAN',
  'file': 'BUILD_ASDAN/Autumn2_W1-W6_2026-27/BUILD_ASDAN_A2_DUKE_W9_A_small_plan_that_helps_Classic.html',
  'family': 'BUILD ASDAN · Autumn 2',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (BUILD · Autumn 2 · Week 1), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'build', 'asdan', 'autumn 2 · week 1'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-build-asdan-useful-roles',
  'subject': 'BUILD Vocational & PfA',
  'type': 'lesson',
  'title': 'One goal, useful roles · BUILD ASDAN',
  'file': 'BUILD_ASDAN/Autumn2_W1-W6_2026-27/BUILD_ASDAN_A2_DUKE_W10_One_goal_useful_roles_Classic.html',
  'family': 'BUILD ASDAN · Autumn 2',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (BUILD · Autumn 2 · Week 2), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'build', 'asdan', 'autumn 2 · week 2'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-grow-asdan-idea-evidence',
  'subject': 'GROW Vocational & PfA',
  'type': 'lesson',
  'title': 'Choose an idea from evidence · GROW ASDAN',
  'file': 'GROW_ASDAN/Autumn2_W1-W6_2026-27/ENT_A2_W9_Choose_an_idea_from_evidence_Classic.html',
  'family': 'GROW ASDAN · Autumn 2',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (GROW · Autumn 2 · Week 1), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'grow', 'asdan', 'autumn 2 · week 1'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-grow-asdan-plan-station',
  'subject': 'GROW Vocational & PfA',
  'type': 'lesson',
  'title': 'Plan the kit station · GROW ASDAN',
  'file': 'GROW_ASDAN/Autumn2_W1-W6_2026-27/ENT_A2_W10_Plan_the_kit_station_Classic.html',
  'family': 'GROW ASDAN · Autumn 2',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (GROW · Autumn 2 · Week 2), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'grow', 'asdan', 'autumn 2 · week 2'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-launch-asdan-team-contract',
  'subject': 'LAUNCH Vocational & PfA',
  'type': 'lesson',
  'title': 'Agree a team plan that works · LAUNCH ASDAN',
  'file': 'LAUNCH_ASDAN/W7-W12_2026-27/lessons/PEQ/PEQ_W9_Agree_a_team_plan_that_works_Classic.html',
  'family': 'LAUNCH ASDAN · Personal Effectiveness',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (LAUNCH · Autumn 2 · Week 1), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'launch', 'asdan', 'autumn 2 · week 1'],
  'year': '2026-27'},
 {'id': 'classic-33-b2-launch-asdan-team-schedule',
  'subject': 'LAUNCH Vocational & PfA',
  'type': 'lesson',
  'title': 'Make the team plan usable · LAUNCH ASDAN',
  'file': 'LAUNCH_ASDAN/W7-W12_2026-27/lessons/PEQ/PEQ_W10_Make_the_team_plan_usable_Classic.html',
  'family': 'LAUNCH ASDAN · Personal Effectiveness',
  'added': '2026-09-07',
  'desc': 'Classic-chassis lesson from the reviewed 33-pack (LAUNCH · Autumn 2 · Week 2), served beside the existing '
          'lesson for the same week; the existing lesson keeps its standing.',
  'keywords': ['classic chassis', '33-pack', 'launch', 'asdan', 'autumn 2 · week 2'],
  'year': '2026-27'}]

# Exact reviewed files, not patterns. A future new UI file requires an explicit
# change here; a lesson cannot become permitted because it shares a directory.
# The verifier and pin tool exclude themselves to avoid a recursive file hash.
REVIEWED_PATHS = (
    "index.html", "Science_Teesside/index.html", "Humanities_Teesside/index.html", "humanities_teesside.html",
    # UX2 A2/A3 (2026-09-08): the shared subject page, its engine, its stylesheet and the published spine.
    "subject.html", "assets/catalogue/hub.js", "assets/catalogue/hub.css", "data/calendar-spine.json",
    "Humanities_Teesside/David_Cover_Autumn1_W3-W7/index.html",
    "assets/catalogue/catalogue.css", "assets/catalogue/catalogue.js",
    "assets/catalogue/lesson-navigation.js",
    "assets/catalogue/science-shelf.css", "assets/catalogue/science-shelf.js",
    "assets/catalogue/terms-and-styles.json", "assets/catalogue/science-shelf.json", "assets/catalogue/humanities-shelf.json",
    "tools/catalogue/build_catalogue.py", "tools/catalogue/build_science_shelf.py", "tools/catalogue/build_humanities_shelf.py",
    "tools/catalogue/check_catalogue_static.py", "tools/catalogue/check_catalogue_dom.cjs", "tools/catalogue/verify_education_navigation.cjs",
    "tools/catalogue/SHELF_SELECTION.json", "tools/catalogue/HUMANITIES_SELECTION.json",
    "tools/easter/science_original_browser.cjs",
    "tools/prepare_served_publications.py", "tools/test_served_publications.py",
    # GLV3 admits only these reviewed publisher checks and cover inputs.
    ".github/workflows/glv3-verify.yml", "_glv3/tools/verify_change_boundary.py",
    "_glv3/tools/browser_verify.mjs", "_glv3/tools/chip_gate.mjs",
    "tools/humanities_resources/SOURCE_MANIFEST.json", "tools/humanities_resources/DOWNLOAD_MANIFEST.json",
    "tools/humanities_resources/CONTENT.json", "tools/humanities_resources/ORIGINAL_MEMBER_MANIFEST.json",
    "tools/humanities_resources/build_resources.py", "tools/humanities_resources/check_resources.py",
    "tools/humanities_resources/resource.css", "tools/humanities_resources/resource.js",
    "tools/catalogue/TERM_AND_STYLE_EVIDENCE.json", "tools/catalogue/TERM_REVIEW.json",
    "tools/catalogue/SCIENCE_WEEK_BINDINGS.json",
    # Recovered reviewed Education correction: gravity statements explicitly
    # condition equal free-fall on negligible air resistance in both formats.
    "primary/year5/science/autumn/forces/Lesson8_ExploreGravity.html",
    "primary/year5/science/autumn/forces/Y5_Forces_SoW_and_Plans.docx",
)


# Owner-reviewed additive Science download transaction, 6 September 2026.
# Every path is explicit; no directory wildcard can admit future payloads.
REVIEWED_PATHS += ('assets/catalogue/science-download-bindings.json', 'Science_Teesside/Teaching_Packs/BUILD/BUILD_Science_Autumn1_W3-W7_Teaching_Guide.docx', 'Science_Teesside/Teaching_Packs/BUILD/BUILD_Science_Autumn1_W3-W7_Teaching_Guide.pdf', 'Science_Teesside/Teaching_Packs/BUILD/DOWNLOAD_INDEX.json', 'Science_Teesside/Teaching_Packs/BUILD/SOURCE_MANIFEST.json', 'Science_Teesside/Teaching_Packs/BUILD/START_HERE.txt', 'Science_Teesside/Teaching_Packs/BUILD/assets/made-by-matt-approved.jpg', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W3-W7_Complete_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W3A_Backbones_Lesson_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W3B_Backbone_Evidence_Lesson_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W3_Teaching_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W4A_Muscle_Pairs_Lesson_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W4B_Muscle_Model_Lesson_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W4_Teaching_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W5A_Body_Needs_Lesson_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W5B_Food_Jobs_Mission_Lesson_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W5_Teaching_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W6A_Balanced_Plate_Lesson_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W6B_Model_Plate_Comparison_Lesson_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W6_Teaching_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W7A_Food_Sources_Lesson_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W7B_Food_Chain_Investigation_Lesson_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W7_Teaching_Pack.zip', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3A/BUILD_Science_Autumn1_W3A_Backbones.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3A/BUILD_Science_Autumn1_W3A_Backbones.pptx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3A/BUILD_Science_Autumn1_W3A_Backbones_Pupil.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3A/BUILD_Science_Autumn1_W3A_Backbones_Pupil.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3A/BUILD_Science_Autumn1_W3A_Backbones_Teacher.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3A/BUILD_Science_Autumn1_W3A_Backbones_Teacher.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3B/BUILD_Science_Autumn1_W3B_Backbone_Evidence.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3B/BUILD_Science_Autumn1_W3B_Backbone_Evidence.pptx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3B/BUILD_Science_Autumn1_W3B_Backbone_Evidence_Pupil.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3B/BUILD_Science_Autumn1_W3B_Backbone_Evidence_Pupil.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3B/BUILD_Science_Autumn1_W3B_Backbone_Evidence_Teacher.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W3B/BUILD_Science_Autumn1_W3B_Backbone_Evidence_Teacher.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4A/BUILD_Science_Autumn1_W4A_Muscle_Pairs.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4A/BUILD_Science_Autumn1_W4A_Muscle_Pairs.pptx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4A/BUILD_Science_Autumn1_W4A_Muscle_Pairs_Pupil.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4A/BUILD_Science_Autumn1_W4A_Muscle_Pairs_Pupil.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4A/BUILD_Science_Autumn1_W4A_Muscle_Pairs_Teacher.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4A/BUILD_Science_Autumn1_W4A_Muscle_Pairs_Teacher.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4B/BUILD_Science_Autumn1_W4B_Muscle_Model.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4B/BUILD_Science_Autumn1_W4B_Muscle_Model.pptx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4B/BUILD_Science_Autumn1_W4B_Muscle_Model_Pupil.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4B/BUILD_Science_Autumn1_W4B_Muscle_Model_Pupil.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4B/BUILD_Science_Autumn1_W4B_Muscle_Model_Teacher.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W4B/BUILD_Science_Autumn1_W4B_Muscle_Model_Teacher.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5A/BUILD_Science_Autumn1_W5A_Body_Needs.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5A/BUILD_Science_Autumn1_W5A_Body_Needs.pptx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5A/BUILD_Science_Autumn1_W5A_Body_Needs_Pupil.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5A/BUILD_Science_Autumn1_W5A_Body_Needs_Pupil.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5A/BUILD_Science_Autumn1_W5A_Body_Needs_Teacher.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5A/BUILD_Science_Autumn1_W5A_Body_Needs_Teacher.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5B/BUILD_Science_Autumn1_W5B_Food_Jobs_Mission.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5B/BUILD_Science_Autumn1_W5B_Food_Jobs_Mission.pptx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5B/BUILD_Science_Autumn1_W5B_Food_Jobs_Mission_Pupil.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5B/BUILD_Science_Autumn1_W5B_Food_Jobs_Mission_Pupil.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5B/BUILD_Science_Autumn1_W5B_Food_Jobs_Mission_Teacher.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W5B/BUILD_Science_Autumn1_W5B_Food_Jobs_Mission_Teacher.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6A/BUILD_Science_Autumn1_W6A_Balanced_Plate.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6A/BUILD_Science_Autumn1_W6A_Balanced_Plate.pptx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6A/BUILD_Science_Autumn1_W6A_Balanced_Plate_Pupil.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6A/BUILD_Science_Autumn1_W6A_Balanced_Plate_Pupil.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6A/BUILD_Science_Autumn1_W6A_Balanced_Plate_Teacher.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6A/BUILD_Science_Autumn1_W6A_Balanced_Plate_Teacher.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6B/BUILD_Science_Autumn1_W6B_Model_Plate_Comparison.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6B/BUILD_Science_Autumn1_W6B_Model_Plate_Comparison.pptx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6B/BUILD_Science_Autumn1_W6B_Model_Plate_Comparison_Pupil.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6B/BUILD_Science_Autumn1_W6B_Model_Plate_Comparison_Pupil.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6B/BUILD_Science_Autumn1_W6B_Model_Plate_Comparison_Teacher.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W6B/BUILD_Science_Autumn1_W6B_Model_Plate_Comparison_Teacher.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7A/BUILD_Science_Autumn1_W7A_Food_Sources.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7A/BUILD_Science_Autumn1_W7A_Food_Sources.pptx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7A/BUILD_Science_Autumn1_W7A_Food_Sources_Pupil.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7A/BUILD_Science_Autumn1_W7A_Food_Sources_Pupil.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7A/BUILD_Science_Autumn1_W7A_Food_Sources_Teacher.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7A/BUILD_Science_Autumn1_W7A_Food_Sources_Teacher.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7B/BUILD_Science_Autumn1_W7B_Food_Chain_Investigation.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7B/BUILD_Science_Autumn1_W7B_Food_Chain_Investigation.pptx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7B/BUILD_Science_Autumn1_W7B_Food_Chain_Investigation_Pupil.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7B/BUILD_Science_Autumn1_W7B_Food_Chain_Investigation_Pupil.pdf', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7B/BUILD_Science_Autumn1_W7B_Food_Chain_Investigation_Teacher.docx', 'Science_Teesside/Teaching_Packs/BUILD/lessons/W7B/BUILD_Science_Autumn1_W7B_Food_Chain_Investigation_Teacher.pdf', 'Science_Teesside/Teaching_Packs/BUILD/resources/BUILD_Science_Autumn1_W3_Cards_and_Labels.docx', 'Science_Teesside/Teaching_Packs/BUILD/resources/BUILD_Science_Autumn1_W3_Cards_and_Labels.pdf', 'Science_Teesside/Teaching_Packs/BUILD/resources/BUILD_Science_Autumn1_W4_Cards_and_Labels.docx', 'Science_Teesside/Teaching_Packs/BUILD/resources/BUILD_Science_Autumn1_W4_Cards_and_Labels.pdf', 'Science_Teesside/Teaching_Packs/BUILD/resources/BUILD_Science_Autumn1_W5_Cards_and_Labels.docx', 'Science_Teesside/Teaching_Packs/BUILD/resources/BUILD_Science_Autumn1_W5_Cards_and_Labels.pdf', 'Science_Teesside/Teaching_Packs/BUILD/resources/BUILD_Science_Autumn1_W6_Cards_and_Labels.docx', 'Science_Teesside/Teaching_Packs/BUILD/resources/BUILD_Science_Autumn1_W6_Cards_and_Labels.pdf', 'Science_Teesside/Teaching_Packs/BUILD/resources/BUILD_Science_Autumn1_W7_Cards_and_Labels.docx', 'Science_Teesside/Teaching_Packs/BUILD/resources/BUILD_Science_Autumn1_W7_Cards_and_Labels.pdf', 'Science_Teesside/Teaching_Packs/GROW/DOWNLOAD_INDEX.json', 'Science_Teesside/Teaching_Packs/GROW/SOURCE_MANIFEST.json', 'Science_Teesside/Teaching_Packs/GROW/START_HERE.pdf', 'Science_Teesside/Teaching_Packs/GROW/START_HERE.txt', 'Science_Teesside/Teaching_Packs/GROW/assets/made-by-matt-approved.jpg', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W3A.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W3B.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W4A.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W4B.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W5A.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W5B.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W6A.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W6B.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W7A.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W7B.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_Week3.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_Week4.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_Week5.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_Week6.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_Week7.zip', 'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_Weeks3-7_Teaching_Pack.zip', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3A/GROW_Science_Autumn1_W3A_Friction.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3A/GROW_Science_Autumn1_W3A_Friction.pptx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3A/GROW_W3A_Friction_Pupil.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3A/GROW_W3A_Friction_Pupil.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3A/GROW_W3A_Friction_Teacher.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3A/GROW_W3A_Friction_Teacher.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3A/START_HERE.txt', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3B/GROW_Science_Autumn1_W3B_Friction_Test.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3B/GROW_Science_Autumn1_W3B_Friction_Test.pptx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3B/GROW_Science_Autumn1_W3B_Friction_Test_Pupil.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3B/GROW_Science_Autumn1_W3B_Friction_Test_Pupil.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3B/GROW_Science_Autumn1_W3B_Friction_Test_Teacher.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3B/GROW_Science_Autumn1_W3B_Friction_Test_Teacher.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3B/GROW_W3B_Friction_Measurements.xlsx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W3B/START_HERE.txt', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4A/GROW_Science_Autumn1_W4A_Mechanisms.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4A/GROW_Science_Autumn1_W4A_Mechanisms.pptx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4A/GROW_Science_Autumn1_W4A_Mechanisms_Pupil.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4A/GROW_Science_Autumn1_W4A_Mechanisms_Pupil.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4A/GROW_Science_Autumn1_W4A_Mechanisms_Teacher.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4A/GROW_Science_Autumn1_W4A_Mechanisms_Teacher.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4A/START_HERE.txt', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4B/GROW_Science_Autumn1_W4B_Lever_Test.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4B/GROW_Science_Autumn1_W4B_Lever_Test.pptx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4B/GROW_Science_Autumn1_W4B_Lever_Test_Pupil.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4B/GROW_Science_Autumn1_W4B_Lever_Test_Pupil.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4B/GROW_Science_Autumn1_W4B_Lever_Test_Teacher.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4B/GROW_Science_Autumn1_W4B_Lever_Test_Teacher.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W4B/START_HERE.txt', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5A/GROW_Science_Autumn1_W5A_Fair_Test.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5A/GROW_Science_Autumn1_W5A_Fair_Test.pptx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5A/GROW_Science_Autumn1_W5A_Fair_Test_Pupil.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5A/GROW_Science_Autumn1_W5A_Fair_Test_Pupil.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5A/GROW_Science_Autumn1_W5A_Fair_Test_Teacher.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5A/GROW_Science_Autumn1_W5A_Fair_Test_Teacher.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5A/START_HERE.txt', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5B/GROW_Science_Autumn1_W5B_Fair_Test_Practical.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5B/GROW_Science_Autumn1_W5B_Fair_Test_Practical.pptx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5B/GROW_Science_Autumn1_W5B_Fair_Test_Practical_Pupil.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5B/GROW_Science_Autumn1_W5B_Fair_Test_Practical_Pupil.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5B/GROW_Science_Autumn1_W5B_Fair_Test_Practical_Teacher.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5B/GROW_Science_Autumn1_W5B_Fair_Test_Practical_Teacher.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5B/GROW_W5B_Fair_Test_Measurements.xlsx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W5B/START_HERE.txt', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6A/GROW_Science_Autumn1_W6A_Earth_And_Planets.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6A/GROW_Science_Autumn1_W6A_Earth_And_Planets.pptx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6A/GROW_Science_Autumn1_W6A_Earth_And_Planets_Pupil.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6A/GROW_Science_Autumn1_W6A_Earth_And_Planets_Pupil.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6A/GROW_Science_Autumn1_W6A_Earth_And_Planets_Teacher.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6A/GROW_Science_Autumn1_W6A_Earth_And_Planets_Teacher.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6A/START_HERE.txt', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6B/GROW_Science_Autumn1_W6B_Earth_And_Planets.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6B/GROW_Science_Autumn1_W6B_Earth_And_Planets.pptx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6B/GROW_Science_Autumn1_W6B_Earth_And_Planets_Pupil.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6B/GROW_Science_Autumn1_W6B_Earth_And_Planets_Pupil.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6B/GROW_Science_Autumn1_W6B_Earth_And_Planets_Teacher.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6B/GROW_Science_Autumn1_W6B_Earth_And_Planets_Teacher.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W6B/START_HERE.txt', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7A/GROW_Science_Autumn1_W7A_The_Moon.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7A/GROW_Science_Autumn1_W7A_The_Moon.pptx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7A/GROW_Science_Autumn1_W7A_The_Moon_Pupil.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7A/GROW_Science_Autumn1_W7A_The_Moon_Pupil.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7A/GROW_Science_Autumn1_W7A_The_Moon_Teacher.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7A/GROW_Science_Autumn1_W7A_The_Moon_Teacher.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7A/START_HERE.txt', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7B/GROW_Science_Autumn1_W7B_The_Moon.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7B/GROW_Science_Autumn1_W7B_The_Moon.pptx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7B/GROW_Science_Autumn1_W7B_The_Moon_Pupil.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7B/GROW_Science_Autumn1_W7B_The_Moon_Pupil.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7B/GROW_Science_Autumn1_W7B_The_Moon_Teacher.docx', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7B/GROW_Science_Autumn1_W7B_The_Moon_Teacher.pdf', 'Science_Teesside/Teaching_Packs/GROW/lessons/W7B/START_HERE.txt', 'Science_Teesside/Teaching_Packs/index.html', 'Science_Teesside/Teaching_Packs/packs.css', 'tools/science_teaching_packs/BUILD_QA.json', 'tools/science_teaching_packs/BUILD_SOURCE_PROVENANCE.json', 'tools/science_teaching_packs/GROW_QA.json', 'tools/science_teaching_packs/build_hub.py', 'tools/science_teaching_packs/check_packs.py')

# Exact public-title-only amendment; teaching content and native files retained.
REVIEWED_PATHS += ('tools/humanities_resources/PUBLIC_LABEL_CHANGES.json', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/BH_W3.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/BH_W4.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/BH_W5.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/BH_W6.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/BH_W7.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/BR_W3.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/BR_W4.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/BR_W5.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/BR_W6.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/BR_W7.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/GH_W3.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/GH_W4.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/GH_W5.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/GH_W6.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/GH_W7.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/GR_W3.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/GR_W4.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/GR_W5.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/GR_W6.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/GR_W7.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/LH_W3.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/LH_W4.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/LH_W5.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/LH_W6.html', 'Humanities_Teesside/David_Cover_Autumn1_W3-W7/LH_W7.html')

# Reviewed Science visual refresh: explicit additional native files and archives.
# Existing routes are retained; this list grants no directory-wide exception.
REVIEWED_PATHS += (
    'Science_Teesside/Teaching_Packs/BUILD/SOURCE_MAPPING.json',
    'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W3-W7_DOCX_Collection.zip',
    'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W3-W7_PDF_Collection.zip',
    'Science_Teesside/Teaching_Packs/BUILD/downloads/BUILD_Science_Autumn1_W3-W7_PPTX_Collection.zip',
    'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W3-W7_DOCX_Collection.zip',
    'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W3-W7_PDF_Collection.zip',
    'Science_Teesside/Teaching_Packs/GROW/downloads/GROW_Science_Autumn1_W3-W7_PPTX_Collection.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/DOWNLOAD_INDEX.json',
    'Science_Teesside/Teaching_Packs/LAUNCH/Pupil_Worksheets.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/SOURCE_MANIFEST.json',
    'Science_Teesside/Teaching_Packs/LAUNCH/START_HERE.txt',
    'Science_Teesside/Teaching_Packs/LAUNCH/Teacher_Guide_And_Answers.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Teacher_Guide_And_Answers.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L1_Microscopy.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L1_Microscopy.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L1_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L1_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L1_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L1_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L1_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L2_Magnification.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L2_Magnification.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L2_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L2_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L2_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L2_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L2_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L3_Scale_Bars.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L3_Scale_Bars.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L3_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L3_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L3_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L3_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3L3_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3_Weekly_Plan.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_3/W3_Weekly_Plan.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L1_Diffusion.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L1_Diffusion.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L1_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L1_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L1_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L1_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L1_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L2_Gas_Exchange.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L2_Gas_Exchange.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L2_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L2_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L2_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L2_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L2_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L3_Diffusion_Evidence.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L3_Diffusion_Evidence.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L3_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L3_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L3_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L3_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4L3_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4_Weekly_Plan.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_4/W4_Weekly_Plan.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L1_Osmosis.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L1_Osmosis.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L1_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L1_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L1_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L1_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L1_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L2_Osmosis_Investigation.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L2_Osmosis_Investigation.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L2_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L2_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L2_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L2_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L2_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L3_Osmosis_Data.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L3_Osmosis_Data.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L3_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L3_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L3_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L3_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5L3_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5_Weekly_Plan.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_5/W5_Weekly_Plan.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L1_Active_Transport.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L1_Active_Transport.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L1_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L1_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L1_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L1_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L1_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L2_Root_Hairs_And_Gut.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L2_Root_Hairs_And_Gut.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L2_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L2_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L2_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L2_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L2_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L3_Compare_Transport.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L3_Compare_Transport.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L3_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L3_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L3_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L3_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6L3_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6_Weekly_Plan.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_6/W6_Weekly_Plan.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/LAUNCH_Science_Assessment.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/LAUNCH_Science_Assessment.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L1_Review.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L1_Review.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L1_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L1_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L1_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L1_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L1_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L2_Command_Words.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L2_Command_Words.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L2_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L2_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L2_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L2_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L2_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L3_Assessment_And_Response.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L3_Assessment_And_Response.pptx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L3_Worksheet.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L3_Worksheet.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L3_depth.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L3_standard.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7L3_supported.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7_Weekly_Plan.docx',
    'Science_Teesside/Teaching_Packs/LAUNCH/Week_7/W7_Weekly_Plan.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/Weekly_Plans.pdf',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W3-W7_Complete_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W3-W7_DOCX_Collection.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W3-W7_PDF_Collection.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W3-W7_PPTX_Collection.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W3L1_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W3L2_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W3L3_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W3_Teaching_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W4L1_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W4L2_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W4L3_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W4_Teaching_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W5L1_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W5L2_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W5L3_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W5_Teaching_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W6L1_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W6L2_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W6L3_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W6_Teaching_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W7L1_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W7L2_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W7L3_Lesson_Pack.zip',
    'Science_Teesside/Teaching_Packs/LAUNCH/downloads/LAUNCH_Science_Autumn1_W7_Teaching_Pack.zip',
    'tools/science_teaching_packs/refresh_packs.py',
)

# Exact image-credit addendum and source-bound browser proof for this refresh.
REVIEWED_PATHS += (
    'Science_Teesside/Teaching_Packs/GROW/Image_Credits.docx',
    'Science_Teesside/Teaching_Packs/GROW/Image_Credits.pdf',
    'tools/science_teaching_packs/check_hub_browser.cjs',
    'tools/science_teaching_packs/VISUAL_REFRESH_QA.json',
    '.github/workflows/science-teaching-packs.yml',
)

ADDITIVE_TAG_KEYS = frozenset({"halfTerm", "unit"})  # UX2 A1; mirrors CATALOGUE_ADDITIVE_TAG_KEYS in the gate


def row_digest(rows: list) -> str:
    return hashlib.sha256(json.dumps(rows, ensure_ascii=False, separators=(",", ":")).encode("utf-8")).hexdigest()


def without_tags(rows: list) -> list:
    return [{k: v for k, v in row.items() if k not in ADDITIVE_TAG_KEYS} for row in rows]


def preserved_rows_errors(rows: list) -> list[str]:
    errors = []
    if len(rows) != ORIGINAL_ROW_COUNT + len(SHELF_ROWS):
        errors.append("catalogue must contain the original 734 rows plus exactly the reviewed hub rows")
    if row_digest(without_tags(rows[:ORIGINAL_ROW_COUNT])) != ORIGINAL_ROWS_SHA256:
        errors.append("an original catalogue row was removed, reordered or edited")
    if without_tags(rows[ORIGINAL_ROW_COUNT:]) != SHELF_ROWS:
        errors.append("the appended hub rows differ from the reviewed navigation entries")
    return errors


def module(path: Path):
    spec = importlib.util.spec_from_file_location("catalogue_gate", path)
    value = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(value)
    return value


def pin(lessons: Path, apps: Path, *, check: bool) -> dict:
    gates = [lessons / GATE, apps / GATE]
    originals = [p.read_text("utf-8") for p in gates]
    if originals[0] != originals[1]:
        raise ValueError("gate copies differ; reconcile their reviewed logic before pinning. Nothing written")
    rows = json.loads((lessons / "resources.json").read_text("utf-8"))
    errors = preserved_rows_errors(rows)
    if errors:
        raise ValueError("; ".join(errors))
    gate = module(gates[0])
    files = {path: hashlib.sha256((lessons / path).read_bytes()).hexdigest() for path in REVIEWED_PATHS}
    text = (lessons / "index.html").read_text("utf-8")
    pins = {"visible_body_sha256": hashlib.sha256(gate.normalized_visible_body(text, "lessons").encode("utf-8")).hexdigest(), "files": files}
    replacement = "# BEGIN REVIEWED CATALOGUE PINS\nCATALOGUE_PINS = " + json.dumps(pins, indent=4) + "\n# END REVIEWED CATALOGUE PINS"
    patched, count = re.subn(r"# BEGIN REVIEWED CATALOGUE PINS\n.*?# END REVIEWED CATALOGUE PINS", lambda _: replacement, originals[0], flags=re.S)
    if count != 1:
        raise ValueError("expected exactly one reviewed catalogue pin block")
    for name, owner in (("resources.json", lessons), ("apps.json", apps)):
        digest = hashlib.sha256((owner / name).read_bytes()).hexdigest()
        pattern = re.compile(r'("' + re.escape(name) + r'":\s*")([0-9a-f]{64})(")')
        patched, count = pattern.subn(lambda m: m[1] + digest + m[3], patched)
        if count != 1:
            raise ValueError("expected exactly one manifest pin: " + name)
    changed = patched != originals[0]
    if check and changed:
        raise ValueError("reviewed catalogue or manifest pins differ; review and re-pin both copies")
    if not check and changed:
        # Prepare the complete, identical replacement before the first write.
        # Restore both originals if an OS write fails during the local operation.
        try:
            for path in gates:
                path.write_text(patched, "utf-8")
        except OSError:
            for path, original in zip(gates, originals):
                path.write_text(original, "utf-8")
            raise
    return {"status": "PASS", "mode": "check" if check else "pin", "reviewedFiles": len(files), "originalRowsPreserved": ORIGINAL_ROW_COUNT, "appendedShelfRows": len(SHELF_ROWS), "gateSha256": hashlib.sha256(patched.encode()).hexdigest()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lessons", type=Path, required=True)
    parser.add_argument("--apps", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        print(json.dumps(pin(args.lessons.resolve(), args.apps.resolve(), check=args.check), indent=2))
        return 0
    except (ValueError, OSError) as exc:
        print("[FAIL] " + str(exc))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
