#!/usr/bin/env python3
"""Re-stamp catalogue source digests for files whose ONLY change is the generated splash region.

    restamp_generated_region_digests.py --base <commit> [--write | --check]

tools/catalogue/TERM_AND_STYLE_EVIDENCE.json records, for each hashed entry, the sha256 of the
bytes its term/style evidence was derived from, and assets/catalogue/lesson-order.json projects
that digest as sourceSha256. When a route is re-stamped with the canonical maker splash
(tools/render_maker_splash.py on the Site, via the pinned generator), those bytes change while
nothing the evidence reads changes -- so the catalogue static check goes red on a content-hash
mismatch that is not a content change at all.

Re-stamping a recorded digest is only honest if the evidence still holds, so this refuses to move
any digest unless it can PROVE the difference is confined to the generated region: the file at
--base and the file in the working tree must be byte-identical once the region between
MBM-MAKER-SPLASH:BEGIN and MBM-MAKER-SPLASH:END (and the surrounding whitespace) is removed from
each. A file that differs anywhere else is refused by name, not re-stamped quietly.

The set is derived, never typed: every hashed entry whose recorded digest differs from the working
tree is a candidate, and each candidate must pass the region proof.

--check exits non-zero if any recorded digest still differs from the working tree.
After --write, run tools/catalogue/build_lesson_order.py to project the digests.
"""
from __future__ import annotations
import argparse, hashlib, json, re, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EVIDENCE = ROOT / 'tools/catalogue/TERM_AND_STYLE_EVIDENCE.json'
BEGIN = '<!-- MBM-MAKER-SPLASH:BEGIN generated by tools/render_maker_splash.py, do not edit by hand -->'
END = '<!-- MBM-MAKER-SPLASH:END -->'
REGION = re.compile(rb'\s*' + re.escape(BEGIN.encode()) + rb'.*?' + re.escape(END.encode()) + rb'\s*', re.S)


def without_region(raw: bytes) -> bytes:
    """The bytes with every generated splash region (and its surrounding whitespace) removed."""
    return REGION.sub(b'\n', raw)


def base_bytes(commit: str, path: str) -> bytes | None:
    try:
        return subprocess.run(['git', '-C', str(ROOT), 'show', f'{commit}:{path}'],
                              check=True, capture_output=True).stdout
    except subprocess.CalledProcessError:
        return None


def candidates() -> list[tuple[str, str, str]]:
    """(path, recorded digest, working-tree digest) for every hashed entry that has moved."""
    entries = json.loads(EVIDENCE.read_text())['entries']
    out = []
    for path, meta in entries.items():
        recorded = meta.get('sha256')
        if not recorded:
            continue
        source = ROOT / path
        if not source.is_file():
            continue
        actual = hashlib.sha256(source.read_bytes()).hexdigest()
        if actual != recorded:
            out.append((path, recorded, actual))
    return sorted(out)


def prove(path: str, base: str) -> str:
    """'' when the only difference is the generated region, else why it was refused."""
    old = base_bytes(base, path)
    if old is None:
        return 'not present at the base commit'
    new = (ROOT / path).read_bytes()
    if BEGIN.encode() not in new:
        return 'the working-tree file carries no generated region'
    if without_region(old) != without_region(new):
        return 'differs outside the generated region'
    return ''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--base', help='the commit the recorded digests were taken from')
    ap.add_argument('--write', action='store_true')
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--self-test', action='store_true', help='planted-failure control for the region proof')
    a = ap.parse_args()

    if a.self_test:
        sample = b'<p>before</p>\n' + BEGIN.encode() + b'\nGENERATED\n' + END.encode() + b'\n<p>after</p>\n'
        moved = b'<p>before</p>\n' + BEGIN.encode() + b'\nGENERATED v2\n' + END.encode() + b'\n<p>after</p>\n'
        edited = b'<p>before</p>\n' + BEGIN.encode() + b'\nGENERATED v2\n' + END.encode() + b'\n<p>AFTER</p>\n'
        stripped = b'<p>before</p>\n<p>after</p>\n'
        ok = without_region(sample) == without_region(moved)
        print(('GREEN' if ok else 'RED  ') + ' a changed region alone leaves the remainder equal')
        red = without_region(moved) != without_region(edited)
        print(('GREEN' if red else 'RED  ') + ' CONTROL: one byte edited outside the region breaks the equality')
        same = without_region(sample).replace(b'\n\n', b'\n') == stripped
        print(('GREEN' if same else 'RED  ') + ' the region and its surrounding whitespace are what is removed')
        return 0 if (ok and red and same) else 1

    moved = candidates()
    if a.check:
        for path, recorded, actual in moved:
            print(f'RED  recorded digest is stale: {path} recorded {recorded} actual {actual}')
        print(f'{len(moved)} stale recorded digest(s)')
        return 1 if moved else 0

    if not a.base:
        print('--base is required to prove a re-stamp'); return 2
    if not moved:
        print('0 stale recorded digests — nothing to re-stamp'); return 0

    refused, accepted = [], []
    for path, recorded, actual in moved:
        why = prove(path, a.base)
        (refused if why else accepted).append((path, recorded, actual, why))
    for path, recorded, actual, why in refused:
        print(f'REFUSED {path}: {why}')
    for path, recorded, actual, _ in accepted:
        print(f'PROVED  {path}: only the generated region differs from {a.base}')
        print(f'        {recorded} -> {actual}')
    if refused:
        print(f'{len(refused)} file(s) refused — a digest is not moved without the proof')
        return 1
    if a.write:
        doc = json.loads(EVIDENCE.read_text())
        for path, _, actual, _ in accepted:
            doc['entries'][path]['sha256'] = actual
        EVIDENCE.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + '\n')
        print(f're-stamped {len(accepted)} recorded digest(s); now run tools/catalogue/build_lesson_order.py')
    else:
        print(f'{len(accepted)} re-stamp(s) proved; pass --write to apply')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
