#!/usr/bin/env python3
"""Inventory and classify every Art Teesside estate file.

The Markdown/JSON output is evidence, not a manually maintained count. It lists
the concrete path behind each category and fails if the renderable HTML
population moves without an explicit update to the expected contract.
"""
from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ART = REPO / "Art_Teesside"
ROOT_ENTRY = REPO / "art_teesside.html"
LESSON_RE = re.compile(r"^(?:BUILD|GROW|LAUNCH)_ART_(?:A2_)?W\d+_.+\.html$")
EXPECTED_HTML = {
    "renderable HTML lesson": 31,
    "renderable HTML hub": 3,
    "printable resource": 8,
    "scheme or run sheet": 9,
    "support HTML": 2,
}
EXCLUDED_PARTS = {"__pycache__", ".pytest_cache", "node_modules"}
HISTORICAL_DOCS = {
    "A2a_Table_and_Chain.md",
    "Defect_Register_Pass4.md",
    "Rebuild_Plan_Pass4.md",
}


def classify(path: Path) -> str:
    rel = path.relative_to(ART)
    name = path.name
    if path.suffix.lower() == ".html":
        if LESSON_RE.match(name):
            return "renderable HTML lesson"
        if name == "START_HERE.html":
            return "renderable HTML hub"
        if "Printable" in name or "Pack" in name:
            return "printable resource"
        if "Scheme_of_Work" in name or "Run_Sheets" in name:
            return "scheme or run sheet"
        return "support HTML"
    if path == ART / "art-teach.css":
        return "shared CSS"
    if path == ART / "art-teach.js":
        return "shared JavaScript"
    if rel.parts and rel.parts[0] == "tools":
        if name == ".gitignore":
            return "other support file"
        if path.suffix.lower() == ".json":
            return "data file"
        if path.suffix.lower() in {".py", ".js", ".sh"}:
            return "test or validation tool"
        if path.suffix.lower() == ".md":
            return "documentation"
    if name in HISTORICAL_DOCS:
        return "historical report"
    if path.suffix.lower() == ".md":
        return "documentation"
    if path.suffix.lower() in {".json", ".csv", ".tsv", ".yaml", ".yml"}:
        return "data file"
    if path.suffix.lower() in {".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".avif"}:
        return "image or visual asset"
    return "other support file"


def files() -> list[Path]:
    return sorted(
        (path for path in ART.rglob("*") if path.is_file() and not (set(path.parts) & EXCLUDED_PARTS)),
        key=lambda path: path.relative_to(REPO).as_posix(),
    )


def build() -> dict:
    grouped: dict[str, list[dict[str, int | str]]] = defaultdict(list)
    for path in files():
        grouped[classify(path)].append({
            "path": path.relative_to(REPO).as_posix(),
            "bytes": path.stat().st_size,
        })
    html_total = sum(len(grouped[key]) for key in EXPECTED_HTML)
    applicable = len(grouped["renderable HTML lesson"]) + len(grouped["renderable HTML hub"]) + 1
    return {
        "scope_root": "Art_Teesside/",
        "root_entry_point": ROOT_ENTRY.relative_to(REPO).as_posix(),
        "root_entry_point_bytes": ROOT_ENTRY.stat().st_size,
        "file_count_beneath_scope": sum(len(rows) for rows in grouped.values()),
        "html_count_beneath_scope": html_total,
        "applicable_presentation_entry_points_including_root": applicable,
        "categories": {key: grouped[key] for key in sorted(grouped)},
    }


def markdown(data: dict) -> str:
    lines = [
        "# Art Teesside estate inventory",
        "",
        "Generated by `Art_Teesside/tools/inventory_estate.py`. Counts are accompanied by the exact paths they describe.",
        "",
        f"- Files beneath `Art_Teesside/`: **{data['file_count_beneath_scope']}**",
        f"- HTML files beneath `Art_Teesside/`: **{data['html_count_beneath_scope']}**",
        f"- Applicable lesson/hub entry points including `{data['root_entry_point']}`: **{data['applicable_presentation_entry_points_including_root']}**",
        f"- Separate root entry point: `{data['root_entry_point']}` ({data['root_entry_point_bytes']} bytes)",
        "",
    ]
    for category, rows in data["categories"].items():
        lines.extend([f"## {category} — {len(rows)}", ""])
        lines.extend(f"- `{row['path']}` — {row['bytes']} bytes" for row in rows)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", dest="json_path", type=Path)
    parser.add_argument("--markdown", dest="markdown_path", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = build()
    problems: list[str] = []
    for category, expected in EXPECTED_HTML.items():
        actual = len(data["categories"].get(category, []))
        if actual != expected:
            problems.append(f"{category}: expected {expected}, found {actual}")
    if data["html_count_beneath_scope"] != 53:
        problems.append(f"HTML total: expected 53, found {data['html_count_beneath_scope']}")
    if data["applicable_presentation_entry_points_including_root"] != 35:
        problems.append(
            "applicable entry points: expected 35, found " +
            str(data["applicable_presentation_entry_points_including_root"])
        )

    text = markdown(data)
    print(text, end="")
    if args.json_path:
        args.json_path.parent.mkdir(parents=True, exist_ok=True)
        args.json_path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if args.markdown_path:
        args.markdown_path.parent.mkdir(parents=True, exist_ok=True)
        args.markdown_path.write_text(text, encoding="utf-8")
    if problems:
        print("INVENTORY CONTRACT FAILED", file=__import__("sys").stderr)
        for problem in problems:
            print("  " + problem, file=__import__("sys").stderr)
        return 1
    print("ART ESTATE INVENTORY PASS — every discovered file classified; 53 scoped HTML and 35 applicable entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
