#!/usr/bin/env python3
# l2k_plan.py — pass PEQ-L2K: the three-lane year ledger, built and PROVEN here.
#
# Single source of numeric truth for the Kitchen Programme year plan
# (GROW_ASDAN/PEQ_L2_Kitchen/). Emits:
#   _passpq/inputs/peq_l2k_year_ledger.json          (data twin, drives the SoW page build)
#   _passpq/inputs/PEQ_L2K_YearPlan_2026-27.xlsx     (data-only xlsx twin)
#
# Every figure is asserted before anything is written; a ledger that does not
# sum raises and nothing is emitted — that IS the red gate (Addendum B §B2).
# All times are integer MINUTES (210 min = 3.5 h default week) so sums are exact.
#
# Facts: _passpq/SPEC_FACTS.md + _passpq/SPEC_FACTS_L2.md (spec v1.2 Oct 2025).
# GLH counts taught/supervised time incl. assessment by the centre assessor
# (spec §9 p16, §5.1 p9). Co-delivery (one supervised hour banked to two units)
# is used sparingly, declared per week, and grounded in the spec's own model:
# ComSk plan/use evidence is EXPECTED to be generated through a challenge that
# leads to another unit (pp25/39/54), ASDAN's worked assessment plan co-assesses
# two units in the same weekly activities (SPEC_FACTS §19), and the qualification
# GLH totals themselves sit below the unit sums (134 vs 140 at E3), so ASDAN's
# arithmetic already nets overlap out.

import json, os, sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
OUT_JSON = os.path.join(ROOT, "_passpq", "inputs", "peq_l2k_year_ledger.json")
OUT_XLSX = os.path.join(ROOT, "_passpq", "inputs", "PEQ_L2K_YearPlan_2026-27.xlsx")

# ---------------------------------------------------------------------------
# PEQ-YEAR-3 §2 — the rates are now MEASURED FROM THE REAL TIMETABLE.
#
# The owner supplied the 2026-27 timetable. It supersedes everything that stood
# here before: the planner-derived 1-7 period band, the owner slot-ruling that
# picked seven within it, and the "GROW/LAUNCH not establishable" verdict. All
# three are retired. Source of truth: _passpq/TIMETABLE_2026-27.md, generated by
# _passpq/tools/timetable_extract.py with a workbook cell cited per row.
#
# Measured, per ROOM, on the printed classification rule:
#   (a) explicitly ASDAN/PEQ-labelled   the floor
#   (b) carryable                       PfA · Community/enterprise · Careers ·
#                                       Vocational/practical · Enrichment/outdoor · Catch-up
#
#   room     (a) slots  (a) h/wk   (a)+(b) slots  (a)+(b) h/wk   owner-decision
#   Build        0        0.000          8           5.333            2
#   Grow         2        1.333          8           5.333            1
#   Launch       4        2.667          8           5.333            1
#
# NO LANE INHERITS ANOTHER'S RATE. The three rooms are equal on (a)+(b) because
# the timetable makes them equal - each independently has eight carryable slots -
# not because one figure was copied onto the others. They differ sharply on the
# floor, which is the number that matters if the carryable slots are ever
# disallowed: Build's ASDAN-labelled floor is ZERO.
ROOM_MEASURED = {
 "Build":  {"a_slots": 0, "ab_slots": 8, "a_min": 0,   "ab_min": 320, "owner_decision": 2},
 "Grow":   {"a_slots": 2, "ab_slots": 8, "a_min": 80,  "ab_min": 320, "owner_decision": 1},
 "Launch": {"a_slots": 4, "ab_slots": 8, "a_min": 160, "ab_min": 320, "owner_decision": 1},
}
# The working basis is (a)+(b): PEQ evidence is generated THROUGH the carryable
# activities, which is the spec's own delivery model. The floor (a) is reported
# beside it on every surface so the honest worst case stays visible.
WEEKLY_MIN = 320          # MEASURED: 8 timetabled 40-minute slots = 5.333 GLH/week
DESIGN_MIN = 210          # the pedagogical allocation the six-block year was laid out on
PERIOD_MIN = 40           # the estate's period unit, from the timetable's own time column
SLOT_BAND = (1, 8)        # 1 slot .. the 8 carryable slots each room actually has
DERIVATION = (
    "MEASURED from the owner's 2026-27 timetable workbooks (PEQ-YEAR-3 §1), not derived from "
    "planners and not chosen by ruling. Period unit 40 min, read off the timetable's own time "
    "column and cross-checked against the Teacher Timetable header. Per room, on the printed "
    "classification rule: Build (a) 0 slots / (a)+(b) 8; Grow (a) 2 / 8; Launch (a) 4 / 8. The "
    "working basis is (a)+(b) = 8 slots = 320 min = 5.333 h/wk, identical across the three "
    "rooms because the timetable makes it so - no lane inherits another's rate. The floor "
    "differs and is reported beside it: Build has NO explicitly ASDAN-labelled slot at all, "
    "Grow has 1.333 h/wk, Launch 2.667 h/wk. Three slots are owner-decision and counted in "
    "neither figure (the DT-vs-Behaviour-Intervention disagreement between the two workbooks), "
    "plus one borderline label. See _passpq/TIMETABLE_2026-27.md for the source cell of every "
    "row."
)
WEEKS = 38
DECK_MIN = 40             # one timetabled 40-minute period per live deck (measured, §"method" below)

# The measurement method for the live 12 weeks (Addendum B gate: "assigned by
# measurement (state the method) not assertion"):
DECK_METHOD = (
    "12 live decks (LAUNCH_ASDAN/PEQ W1-6 + GROW_ASDAN/PEQ W1-6) x one timetabled "
    "40-minute period each = 480 min = 8.0 GLH. The period length is the estate's "
    "timetable unit (the science chassis is named v3_40min; GROW PEQ runs Thursday P4, "
    "one period). The decks PROGRAM 53 min of slide time each (sum of data-timer values "
    "on every deck's 10 slides) - i.e. they over-program the slot; the GLH claimed is "
    "the supervised 40-minute slot, never the programme. Deck-to-unit assignment "
    "follows each deck's own banking line."
)

# ---- units (credits, GLH) per lane -----------------------------------------
# skill keys: Com, DecMk, LSk, TmWk, Th (ThSk at E3/L1, CrThSk2 at L2), Wellb
UNITS = {
 "E3": {"Com": ("ComSkE3", 3, 30), "DecMk": ("DecMkSkE3", 2, 20), "LSk": ("LSkE3", 2, 20),
        "TmWk": ("TmWkSkE3", 2, 20), "Th": ("ThSkE3", 2, 20), "Wellb": ("WellbLeE3", 3, 30)},
 "L1": {"Com": ("ComSk1", 3, 27), "DecMk": ("DecMkSk1", 2, 18), "LSk": ("LSk1", 2, 18),
        "TmWk": ("TmWkSk1", 2, 18), "Th": ("ThSk1", 3, 27), "Wellb": ("WellbLe1", 3, 27)},
 "L2": {"Com": ("ComSk2", 3, 24), "DecMk": ("DecMkSk2", 2, 16), "LSk": ("LSk2", 2, 16),
        "TmWk": ("TmWkSk2", 2, 16), "Th": ("CrThSk2", 3, 24), "Wellb": ("WellbLe2", 3, 24)},
}
SKILLS = ["Com", "DecMk", "LSk", "TmWk", "Th", "Wellb"]

# Qualification ladders: (name, credits, qual GLH, milestone week, constituent skills)
QUALS = {
 "E3": [("Entry Level Award (610/5901/8)", 4, 40, 14, ["DecMk", "TmWk"]),
        ("Entry Level Extended Award (610/5903/1)", 9, 86, 26, ["DecMk", "TmWk", "Com", "LSk"]),
        ("Entry Level Certificate (610/5902/X)", 14, 134, 38, SKILLS)],
 "L1": [("Level 1 Award (610/5904/3)", 4, 36, 14, ["DecMk", "TmWk"]),
        ("Level 1 Extended Award (610/5906/7)", 9, 77, 26, ["DecMk", "TmWk", "Com", "LSk"]),
        ("Level 1 Certificate (610/5905/5)", 14, 120, 38, SKILLS)],
 "L2": [("Level 2 Award (610/5907/9)", 4, 32, 14, ["DecMk", "TmWk"]),
        ("Level 2 Extended Award (610/5909/2)", 9, 68, 26, ["DecMk", "TmWk", "Com", "LSk"]),
        ("Level 2 Certificate (610/5908/0)", 15, 106, 38, SKILLS)],
}

# PEQ-YEAR-2 §2 — the block boundaries, and what each one rests on.
#
# AUTUMN IS EVIDENCED AND WAS WRONG HERE. Re-derived from the dates rather than
# read off a label: 31 Aug -> 14 Dec 2026 is 105 days = 16 Mondays; minus the one
# half-term week (26-30 Oct) = 15 teaching weeks, split Aut1 = 8 (w/c 1 Sep ->
# w/c 19 Oct) and Aut2 = 7 (w/c 2 Nov -> w/c 14 Dec, term ending Fri 18 Dec).
# Stated identically in five places (Planning/{BUILD,GROW,LAUNCH}/README.txt and
# both year-plan workbooks' 'Key Dates & Compliance' tabs), and enumerated week by
# week in BUILD_Autumn_Year_Plan_ASDAN_Update.xlsx [Autumn Overview] A6:B21.
# This file previously spent 7 + 7 = 14 on autumn -- the PLACEHOLDER shape those
# same READMEs declare dead ("Those placeholders are dead - do not reuse them").
# Corrected below. It mattered in a teacher-facing way: W8 is the AUDIT week and
# the LAST week of Aut 1, and the printed week shells were labelling it Aut2.
#
# SPRING AND SUMMER ARE NOT EVIDENCED. The repo holds no spring or summer term
# date at all -- no Easter date, no February or May half-term, no INSET day.
# Their boundaries below are ASSUMPTIONS carried forward, and are labelled as
# such on the year map. See TERM_EVIDENCE.
#
# WHY THE YEAR STAYS 38. The SoW workbooks' own scheme totals 39 (7+7+6+6+6+7),
# so WEEKS = 38 is that 39 with a week taken off SUMMER, on top of the dead
# 14-week autumn -- two deviations, not one. Neither 39 nor 40 can simply be set:
# lane_rows() hand-allocates exactly 38 weeks and build() asserts every week sums
# to DESIGN_MIN, so WEEKS = 39 dies on "E3 W39: design 0 != 210". Re-cutting the
# year would move every milestone and every criteria-to-week mapping on the
# strength of 24 unevidenced weeks, which is exactly what this pass may not do.
# The +1 that autumn correctly gains is therefore absorbed by Sum2, the last and
# least-evidenced block, and that is said plainly on the page.
BLOCKS = [("Aut1", 1, 8), ("Aut2", 9, 15), ("Spr1", 16, 21), ("Spr2", 22, 27),
          ("Sum1", 28, 33), ("Sum2", 34, 38)]
TERM_EVIDENCE = {
 "Aut1": {"weeks": 8, "evidenced": True,
          "source": "Planning/*/README.txt + BUILD_Autumn_Year_Plan_ASDAN_Update.xlsx "
                    "[Autumn Overview] A6:B21; re-derived from the dates (w/c 1 Sep -> w/c 19 Oct)"},
 "Aut2": {"weeks": 7, "evidenced": True,
          "source": "same; w/c 2 Nov -> w/c 14 Dec, term ends Fri 18 Dec"},
 "Spr1": {"weeks": 6, "evidenced": False, "source": "assumption carried forward; no calendar in repo"},
 "Spr2": {"weeks": 6, "evidenced": False, "source": "assumption carried forward; no calendar in repo"},
 "Sum1": {"weeks": 6, "evidenced": False, "source": "assumption carried forward; no calendar in repo"},
 "Sum2": {"weeks": 5, "evidenced": False,
          "source": "assumption, and the block that absorbs autumn's evidenced +1 inside a "
                    "38-week year. The SoW scheme says 7, which would make the year 40."},
}
CALENDAR_NOTE = (
 "Autumn 2026 = 15 teaching weeks, EVIDENCED and re-derived from the dates (Aut1 8 + Aut2 7). "
 "Spring and summer have NO term dates anywhere in the repo: their block lengths are declared "
 "assumptions. The year total of 38 weeks is itself an assumption - the estate's own SoW scheme "
 "totals 39, and evidenced-autumn plus that scheme's spring/summer would give 40. The ledger "
 "cannot simply be re-cut to 39 or 40: lane_rows() hand-allocates 38 weeks and build() refuses "
 "any other length, so changing it would move every milestone and every criteria week on the "
 "strength of 24 unevidenced weeks. OUTSTANDING FOR MATT: confirm term dates / teaching weeks "
 "for spring and summer 2026-27."
)

# ---- the live 12-week deck spine (weeks 1-12) ------------------------------
# (week, suite, deck, skill banked — from each deck's banking line)
DECKS = [
 (1, "LAUNCH", "W1 Intro and Choosing My Level", "Com"),
 (2, "LAUNCH", "W2 What Makes Communication Effective", "Com"),
 (3, "LAUNCH", "W3 Active Listening and Giving Feedback", "Com"),
 (4, "LAUNCH", "W4 Plan a Communication Activity", "Com"),
 (5, "LAUNCH", "W5 Deliver the Activity and Gather Evidence", "Com"),
 (6, "LAUNCH", "W6 Review Progress and Sign Off the Unit", "Com"),
 (7, "GROW", "W1 Knowing Myself (core-skills audit)", "LSk"),
 (8, "GROW", "W2 Goals That Work (SMART planning)", "LSk"),
 (9, "GROW", "W3 Working With Others", "TmWk"),
 (10, "GROW", "W4 Managing Myself (routines)", "LSk"),
 (11, "GROW", "W5 Solving Problems", "Th"),
 (12, "GROW", "W6 Present My Progress", "LSk"),
]

def deck_minutes(week):
    for w, suite, name, sk in DECKS:
        if w == week:
            return sk, DECK_MIN, f"{suite} {name}"
    return None, 0, None

# ---- per-lane weekly allocations (minutes), hand-set, machine-proven -------
# row = {skill: physical minutes}; co = {skill: co-delivered minutes} (the same
# physical session banked to a second unit, declared).
def lane_rows(lane):
    R = [dict() for _ in range(WEEKS + 1)]   # 1-indexed
    C = [dict() for _ in range(WEEKS + 1)]
    def p(w, **kw):
        for k, v in kw.items(): R[w][k] = R[w].get(k, 0) + v
    def co(w, **kw):
        for k, v in kw.items(): C[w][k] = C[w].get(k, 0) + v
    # deck slot, all lanes share the mixed-room session (level-correct demand per lane)
    for w in range(1, 13):
        sk, m, _ = deck_minutes(w)
        p(w, **{sk: m})
    if lane == "E3":
        p(1, TmWk=170); p(2, TmWk=120, Wellb=50); p(3, TmWk=120, Wellb=50)
        p(4, TmWk=170); p(5, TmWk=170)
        p(6, TmWk=120, DecMk=50); p(7, TmWk=120, DecMk=50); p(8, TmWk=120, DecMk=50)
        p(9, DecMk=170); p(10, DecMk=170); p(11, DecMk=170); p(12, DecMk=170)
        p(13, TmWk=50, DecMk=160); p(14, DecMk=210)
        for w in range(15, 20): p(w, LSk=180, Com=30)
        p(20, LSk=140, Com=70)
        co(17, Com=40); co(18, Com=40)          # Com prep generated through the LSk ladder (spec pp25/54)
        for w in range(21, 27): p(w, Com=210)
        for w in range(27, 32): p(w, Th=170, Wellb=40); co(w, Wellb=60)  # Wellb plan in live use during the investigation
        p(32, Th=140, Wellb=70); co(32, Wellb=40)
        p(33, Th=170, Wellb=40)
        for w in range(34, 39): p(w, Wellb=210)
    elif lane == "L1":
        p(1, TmWk=170); p(2, TmWk=120, Wellb=50); p(3, TmWk=120, Wellb=50)
        p(4, TmWk=170); p(5, TmWk=130, Wellb=40)
        p(6, TmWk=120, DecMk=50); p(7, TmWk=120, DecMk=50); p(8, TmWk=90, DecMk=80)
        p(9, DecMk=170); p(10, DecMk=170); p(11, DecMk=170); p(12, DecMk=170)
        p(13, DecMk=170, Wellb=40); p(14, DecMk=50, Wellb=160)
        for w in range(15, 20): p(w, LSk=160, Com=50)
        p(20, LSk=120, Com=60, Wellb=30)
        for w in range(21, 26): p(w, Com=180, Wellb=30)
        p(26, Com=170, Wellb=40)
        for w in range(27, 33): p(w, Th=180, Wellb=30)
        for w in range(28, 32): co(w, Wellb=30)
        p(33, Th=180, Wellb=30); p(34, Th=180, Wellb=30); p(35, Th=140, Wellb=70)
        for w in range(36, 39): p(w, Wellb=210)
    elif lane == "L2":
        p(1, TmWk=170); p(2, TmWk=120, Wellb=50); p(3, TmWk=120, Wellb=50)
        p(4, TmWk=170); p(5, TmWk=170)
        p(6, TmWk=100, DecMk=70); p(7, TmWk=70, DecMk=100)
        p(8, DecMk=170); p(9, DecMk=170); p(10, DecMk=170); p(11, DecMk=170)
        p(12, DecMk=110, Wellb=60)
        p(13, Wellb=100, QA=110); p(14, Wellb=100, QA=110)
        for w in range(15, 20): p(w, LSk=160, Com=50)
        p(20, Com=130, Wellb=80)
        for w in range(21, 26): p(w, Com=140, Wellb=70)
        p(26, Com=120, Wellb=50, QA=40)
        for w in range(27, 33): p(w, Th=180, Wellb=30)
        p(33, Th=180, Wellb=30); p(34, Th=140, Wellb=70)
        p(35, Wellb=210); p(36, Wellb=110, QA=100)
        p(37, QA=210); p(38, QA=210)
    return R, C

# Unit-complete / evaluation weeks derived below; plan windows (10-hour use,
# spec: 5 of 6 units per level; Com carries activity minima instead):
PLAN_WINDOWS = {   # skill: (plan opens, window closes, review point week) — all lanes share the vehicle
 "TmWk": (2, 12, 6),     # team plan decided together in W2; weekly cook cycles; review W6
 "DecMk": (9, 13, 11),   # decision plan opens with the menu/budget project
 "LSk": (15, 19, 18),    # learning plan opens with the technique ladder
 "Th": (27, 32, 30),     # investigation plan (ThSk E3/L1 · CrThSk2 L2)
 "Wellb": (27, 36, 32),  # wellbeing-in-learning plan, used across the summer learning weeks
}
COM_ACTIVITY = {  # Com has no 10-hour window; activity minima instead (SPEC_FACTS §16 / _L2 §4)
 "plan_weeks": (21, 22), "activity_weeks": (23, 25), "eval_week": 26,
 "E3": "ONE activity: presentation >=2 min OR discussion >=5 min OR text >=100 words",
 "L1": "ONE activity: presentation >=3 min OR discussion >=8 min OR text >=250 words",
 "L2": "TWO plans over two DIFFERENT ways: presentation >=4 min / discussion >=10 min / text >=500 words",
}

def build():
    lanes = {}
    for lane in ("E3", "L1", "L2"):
        R, C = lane_rows(lane)
        # -- PEQ-YEAR-1 §2: re-anchor the design onto the DERIVED week ------------
        # lane_rows lays the six-block pedagogical year out at DESIGN_MIN a week, closing
        # the E3 and L1 ledgers only with a declared co-delivery top-up. The derived week is
        # wider, so those minutes are now affordable as REAL supervised time: fold them into
        # the physical ledger and withdraw the co-delivery claim entirely. Whatever is left
        # is declared QA/consolidation and is never claimed against a unit.
        for w in range(1, WEEKS + 1):
            design = sum(R[w].values())
            assert design == DESIGN_MIN, f"{lane} W{w}: design {design} != {DESIGN_MIN}"
            for sk, m in C[w].items():
                R[w][sk] = R[w].get(sk, 0) + m
            used = sum(R[w].values())
            assert used <= WEEKLY_MIN, f"{lane} W{w}: {used} min allocated > derived week {WEEKLY_MIN}"
            R[w]["QA"] = R[w].get("QA", 0) + (WEEKLY_MIN - used)
        C = [dict() for _ in range(WEEKS + 1)]   # co-delivery withdrawn — the hours are real now
        # -- assertions: the red gate --
        for w in range(1, WEEKS + 1):
            phys = sum(R[w].values())
            assert phys == WEEKLY_MIN, f"{lane} W{w}: physical {phys} != {WEEKLY_MIN}"
        totals, cum, complete_wk = {}, {}, {}
        for sk in SKILLS:
            t = sum(R[w].get(sk, 0) + C[w].get(sk, 0) for w in range(1, WEEKS + 1))
            totals[sk] = t
            need = UNITS[lane][sk][2] * 60
            assert t == need, f"{lane} {UNITS[lane][sk][0]}: ledger {t} min != unit GLH {need} min"
            c, wk = 0, None
            for w in range(1, WEEKS + 1):
                c += R[w].get(sk, 0) + C[w].get(sk, 0)
                if wk is None and c >= need: wk = w
            complete_wk[sk] = wk
        qa = sum(R[w].get("QA", 0) for w in range(1, WEEKS + 1))
        co_total = sum(sum(C[w].values()) for w in range(1, WEEKS + 1))
        phys_total = WEEKLY_MIN * WEEKS
        assert sum(totals.values()) + qa == phys_total + co_total, f"{lane}: attribution mismatch"
        # milestones: constituent units complete by milestone week; credits + qual GLH stated
        miles = []
        for (name, cr, qglh, mw, skills) in QUALS[lane]:
            for sk in skills:
                assert complete_wk[sk] <= mw, f"{lane} {name}: {sk} completes W{complete_wk[sk]} > W{mw}"
            unit_glh = sum(UNITS[lane][sk][2] for sk in skills)
            unit_cr = sum(UNITS[lane][sk][1] for sk in skills)
            assert unit_cr == cr or (lane == "L1" and cr == 14 and unit_cr == 15), \
                f"{lane} {name}: credits {unit_cr} != {cr}"
            assert unit_glh >= qglh, f"{lane} {name}: unit GLH {unit_glh} < qual GLH {qglh}"
            miles.append({"qual": name, "credits": cr, "unit_credits": unit_cr,
                          "qual_glh": qglh, "unit_glh": unit_glh, "week": mw})
        # plan windows: >=600 min of the unit's supervised time inside the window, closed before eval
        for sk, (o, cl, rev) in PLAN_WINDOWS.items():
            inwin = sum(R[w].get(sk, 0) + C[w].get(sk, 0) for w in range(o, cl + 1))
            assert inwin >= 600, f"{lane} {sk}: window W{o}-W{cl} holds {inwin} min < 600"
            assert o <= rev <= cl, f"{lane} {sk}: review point W{rev} outside window"
        lanes[lane] = {"rows": [dict(R[w]) for w in range(1, WEEKS + 1)],
                       "co": [dict(C[w]) for w in range(1, WEEKS + 1)],
                       "totals_min": totals, "qa_min": qa, "co_min": co_total,
                       "complete_week": complete_wk, "milestones": miles}
    # deck spine sums to 8.0 GLH exactly
    assert len(DECKS) == 12 and 12 * DECK_MIN == 480
    return lanes

# ---- sensitivity table (Addendum B: 2 / 3 / 4 h/wk, default 3.5) -----------
def sensitivity():
    rows = []
    CO_CAP = {"E3": 420, "L1": 120, "L2": 0}   # the declared co-delivery in the 3.5 h plan
    # Re-based (PEQ-YEAR-1 §2) onto the MEASURED 40-minute period rather than the round
    # numbers 2/3/3.5/4, none of which is a whole number of the estate's real periods.
    # Each row is a whole count of timetabled periods; the owner input is carried alongside,
    # flagged, so the page can show it without presenting it as derived.
    lo, hi = SLOT_BAND
    live_slots = WEEKLY_MIN / PERIOD_MIN
    grid = {n: n * PERIOD_MIN / 60.0 for n in range(lo, hi + 1)}
    grid[live_slots] = WEEKLY_MIN / 60.0        # the derived rate; may coincide with a band row
    for slots, hpw in sorted(grid.items(), key=lambda t: t[1]):
        year = int(round(hpw * 60)) * WEEKS
        cell = {"slots": slots, "whole_periods": float(slots).is_integer(),
                "live": abs(hpw - WEEKLY_MIN / 60.0) < 1e-9,
                "hpw": round(hpw, 4), "year_glh": round(year / 60.0, 2), "lanes": {}}
        for lane in ("E3", "L1", "L2"):
            reach = []
            for (name, cr, qglh, mw, skills) in QUALS[lane]:
                need = sum(UNITS[lane][sk][2] for sk in skills) * 60
                ok = need <= year + CO_CAP[lane]
                reach.append({"qual": name.split(" (")[0], "unit_glh_h": need / 60.0, "ok": ok,
                              "short_h": 0 if ok else (need - year - CO_CAP[lane]) / 60.0})
            cell["lanes"][lane] = reach
        rows.append(cell)
    return rows

def _assert_measured_matches_timetable():
    """ROOM_MEASURED must still equal what the timetable extract measured.

    The per-room ceilings are genuinely DERIVED PER LANE - perturbing one room's
    ab_slots moves that room's GLH and no other, which is the property that keeps
    the identical 202.67 across all three honest. It is a coincidence of the real
    timetable, not one constant applied three times: the three splits are 0+8, 2+6
    and 4+4, three different shapes that happen to total 8 each.

    But ROOM_MEASURED is TRANSCRIBED from _passpq/inputs/timetable_2026-27.json
    rather than read from it, and a transcribed copy of a measurement is a
    measurement that can go stale without anything noticing. Re-extract the
    timetable, change a classification, and these numbers would quietly keep
    describing the old one. So they are reconciled here, every run.
    """
    src = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "..", "inputs", "timetable_2026-27.json")
    with open(src, encoding="utf-8") as fh:
        tt = json.load(fh)
    for room, m in ROOM_MEASURED.items():
        c = tt["counts"][room]
        a, b = c.get("a", 0), c.get("b", 0)
        od = c.get("owner-decision", 0)
        assert m["a_slots"] == a, \
            f"ROOM_MEASURED[{room}].a_slots={m['a_slots']} but the timetable measures {a}"
        assert m["ab_slots"] == a + b, \
            f"ROOM_MEASURED[{room}].ab_slots={m['ab_slots']} but the timetable measures {a + b}"
        assert m["owner_decision"] == od, \
            f"ROOM_MEASURED[{room}].owner_decision={m['owner_decision']} but the timetable measures {od}"
        assert m["a_min"] == a * PERIOD_MIN, \
            f"ROOM_MEASURED[{room}].a_min={m['a_min']} != {a} slots x {PERIOD_MIN} min"
        assert m["ab_min"] == (a + b) * PERIOD_MIN, \
            f"ROOM_MEASURED[{room}].ab_min={m['ab_min']} != {a + b} slots x {PERIOD_MIN} min"
    assert WEEKLY_MIN == max(m["ab_min"] for m in ROOM_MEASURED.values()), \
        "WEEKLY_MIN no longer matches the largest measured room"


def _assert_calendar():
    """A block scheme that does not cover the year, or a TERM_EVIDENCE table that
    disagrees with the blocks it documents, is a silent falsehood on 38 printed
    pages. Fail the build instead."""
    span = sum(z - a + 1 for _, a, z in BLOCKS)
    assert span == WEEKS, f"BLOCKS span {span} != WEEKS {WEEKS}"
    assert BLOCKS[0][1] == 1 and BLOCKS[-1][2] == WEEKS, "BLOCKS must start at W1 and end at WEEKS"
    for i in range(1, len(BLOCKS)):
        assert BLOCKS[i][1] == BLOCKS[i - 1][2] + 1, f"gap/overlap before {BLOCKS[i][0]}"
    for (b, a, z) in BLOCKS:
        assert TERM_EVIDENCE[b]["weeks"] == z - a + 1, \
            f"TERM_EVIDENCE {b} says {TERM_EVIDENCE[b]['weeks']} wks, BLOCKS says {z - a + 1}"
    ev = sum(t["weeks"] for t in TERM_EVIDENCE.values() if t["evidenced"])
    assert ev == 15, f"evidenced autumn should total 15 weeks, got {ev}"


# ---------------------------------------------------------------------------
# PEQ-YEAR-3 §3 — the cooking reality check.
#
# THE WHOLE SCHOOL HAS EXACTLY ONE COOKING-LABELLED SLOT: Build, Wednesday
# Period 5, 12:50-13:30, "PfA / cooking", Science Teacher. Measured across every
# cell of both workbooks. At 38 weeks that is 25.33 GLH - it cannot carry an L2
# Certificate (120 unit-GLH) or any Certificate at any level, and the Kitchen year
# as written before this pass implied more kitchen time than the timetable gives.
#
# Worth knowing where the label lives: the LANE GRIDS never say "cooking" at all.
# Build Wed P5 reads a bare "PfA" there. The label is in [Teacher Timetable]!J11
# and corroborated in the summary's G29 and split-teaching E5. Reading only the
# lane grids finds zero cooking slots and is wrong.
#
# THE RULING (instrument §3): the kitchen is a CONTEXT, not a room booking, so it
# extends across each lane's carryable practical cluster. The slots below are the
# kitchen sessions, named one by one, verified present in the measured timetable.
COOKING_SLOTS = [
 {"lane": "Build", "day": "Wed", "period": "P5", "time": "12:50-13:30",
  "label": "PfA / cooking", "role": "Science Teacher", "source": "[Build Timetable]!D11",
  "cooking_labelled": True},
]
KITCHEN_CLUSTER = {
 "Build": [
   {"day": "Wed", "period": "P5", "time": "12:50-13:30", "label": "PfA / cooking",
    "role": "Science Teacher", "source": "[Build Timetable]!D11", "bucket": "b"},
   {"day": "Fri", "period": "P3", "time": "11:00-11:40", "label": "Vocational / practical",
    "role": "Science Teacher", "source": "[Build Timetable]!F8", "bucket": "b"}],
 "Grow": [
   {"day": "Tue", "period": "P5", "time": "12:50-13:30", "label": "Vocational / practical",
    "role": "Maths Teacher", "source": "[Grow Timetable]!C11", "bucket": "b"},
   {"day": "Thu", "period": "P5", "time": "12:50-13:30", "label": "Vocational / practical",
    "role": "Maths Teacher", "source": "[Grow Timetable]!E11", "bucket": "b"}],
 "Launch": [
   {"day": "Mon", "period": "P4", "time": "11:40-12:20", "label": "Vocational / ASDAN option",
    "role": "Science Teacher", "source": "[Launch Timetable]!B9", "bucket": "a"},
   {"day": "Tue", "period": "P5", "time": "12:50-13:30", "label": "PfA / ASDAN",
    "role": "Science Teacher", "source": "[Launch Timetable]!C11", "bucket": "a"},
   {"day": "Thu", "period": "P4", "time": "11:40-12:20", "label": "PfA / ASDAN",
    "role": "English Teacher", "source": "[Launch Timetable]!E9", "bucket": "a"},
   {"day": "Wed", "period": "P6", "time": "13:30-14:10", "label": "Vocational / ASDAN option",
    "role": "English Teacher", "source": "[Launch Timetable]!D12", "bucket": "a"}],
}


def kitchen_capacity():
    """Per lane: how many kitchen sessions, what that is in hours, and what it can
    genuinely evidence on its own - stated as a ceiling, not implied."""
    out = {}
    cook_min = len(COOKING_SLOTS) * PERIOD_MIN
    for lane, slots in KITCHEN_CLUSTER.items():
        mins = len(slots) * PERIOD_MIN
        yr = mins * WEEKS / 60
        reach = {}
        for lv in ("E3", "L1", "L2"):
            for (name, cr, qglh, mw, sk) in QUALS[lv]:
                unit_glh = sum(UNITS[lv][x][2] for x in sk)
                reach[f"{lv} {name.split(' (')[0]}"] = {
                    "unit_glh": unit_glh, "reachable_on_kitchen_alone": unit_glh <= yr}
        out[lane] = {"slots": slots, "n_slots": len(slots),
                     "h_per_week": round(mins / 60, 4), "year_glh": round(yr, 2),
                     "reach_on_kitchen_alone": reach}
    out["_cooking_labelled_whole_school"] = {
        "n": len(COOKING_SLOTS), "h_per_week": round(cook_min / 60, 4),
        "year_glh": round(cook_min * WEEKS / 60, 2), "slots": COOKING_SLOTS,
        "statement": (
            f"The whole school timetables {len(COOKING_SLOTS)} cooking-labelled slot: "
            f"Build Wednesday P5, 12:50-13:30, 'PfA / cooking', Science Teacher. At {WEEKS} "
            f"weeks that is {cook_min * WEEKS / 60:.2f} GLH. On its own it carries NO "
            f"qualification at any level - the smallest, the Level 2 Award, needs 32 unit-GLH "
            f"and would take it most of the year, and no Certificate is within reach of it at "
            f"all. That is why the kitchen is run as a context across the carryable practical "
            f"cluster rather than as a single booked room.")}
    return out


def room_reachability():
    """PEQ-YEAR-3 §2. For each ROOM at its own MEASURED rate, at both the floor
    (a: explicitly ASDAN-labelled slots only) and the ceiling (a+b: including the
    carryable slots), which of Award / Extended / Certificate is reachable at each
    level - and where it is NOT, that is stated rather than left implied.

    Two thresholds are reported because the spec carries two and they differ:
      qual GLH  - the qualification's own published GLH
      unit GLH  - the sum of its constituent units' GLH, which is what the ledger
                  must actually bank, and is the stricter test. The verdict uses
                  the stricter one; both are printed so nobody has to guess which."""
    out = {}
    for room, m in ROOM_MEASURED.items():
        cell = {"a_min": m["a_min"], "ab_min": m["ab_min"],
                "a_h_per_week": round(m["a_min"] / 60, 4),
                "ab_h_per_week": round(m["ab_min"] / 60, 4),
                "a_year_glh": round(m["a_min"] * WEEKS / 60, 2),
                "ab_year_glh": round(m["ab_min"] * WEEKS / 60, 2),
                "owner_decision_slots": m["owner_decision"], "levels": {}}
        for lane in ("E3", "L1", "L2"):
            rows = []
            for (name, cr, qglh, mw, skills) in QUALS[lane]:
                unit_glh = sum(UNITS[lane][sk][2] for sk in skills)
                rows.append({
                    "qual": name.split(" (")[0], "credits": cr,
                    "qual_glh": qglh, "unit_glh": unit_glh, "milestone_week": mw,
                    "reachable_at_floor": unit_glh * 60 <= m["a_min"] * WEEKS,
                    "reachable_at_ceiling": unit_glh * 60 <= m["ab_min"] * WEEKS,
                    "short_at_floor_h": max(0, round(unit_glh - m["a_min"] * WEEKS / 60, 2)),
                })
            cell["levels"][lane] = rows
        out[room] = cell
    return out


def main():
    _assert_calendar()
    _assert_measured_matches_timetable()
    lanes = build()
    sens = sensitivity()
    data = {
        "pass": "PEQ-L2K v2 + Addendum B", "built": "2026-08-22",
        "weekly_min_default": WEEKLY_MIN, "weeks": WEEKS, "blocks": BLOCKS,
        "deck_min": DECK_MIN, "deck_method": DECK_METHOD,
        "term_evidence": TERM_EVIDENCE, "calendar_note": CALENDAR_NOTE,
        "period_min": PERIOD_MIN, "slot_band": list(SLOT_BAND), "derivation": DERIVATION,
        "room_measured": ROOM_MEASURED, "room_reachability": room_reachability(),
        "kitchen": kitchen_capacity(),
        "weekly_min_is_owner_input": True,
        "decks": [{"week": w, "suite": s, "deck": d, "skill": sk} for (w, s, d, sk) in DECKS],
        "units": {lane: {sk: {"code": u[0], "credits": u[1], "glh": u[2]} for sk, u in UNITS[lane].items()}
                  for lane in UNITS},
        "plan_windows": {sk: {"open": o, "close": c, "review": r} for sk, (o, c, r) in PLAN_WINDOWS.items()},
        "com_activity": COM_ACTIVITY,
        "lanes": lanes, "sensitivity": sens,
        "l1_cert_choice": (
            "DECIDED (centre orchestration, PEQ-YEAR-1 s3). The L1 Certificate is 14 credits "
            "while the six L1 units sum to 15. THE CENTRE TEACHES AND EVIDENCES ALL SIX L1 "
            "UNITS - 15 credits, every one at level; spec s5.1 permits exceeding the 14 "
            "minimum. This is a choice already made, not an open question. The fallback, if a "
            "pupil is stretched by L1 Thinking (the largest E3-to-L1 step: assumptions + "
            "primary/secondary sources) or an exact-14 claim is later preferred, is the five "
            "other L1 units (12 cr at L1) + ThSkE3 (2 cr adjacent) = 14 - the only exact-14 "
            "arithmetic, with min-11-at-level and max-3-below both satisfied. Which shape is "
            "CLAIMED is stated to ASDAN at names-confirmation, ~4 weeks before EQA sampling; "
            "that is a normal step in the EQA cycle, not a decision still to be taken."),
        "orchestration": {
            "decided": "2026-08-21 (owner), recorded PEQ-YEAR-1 s3",
            "entry_settled": ("Learners are registered and units are entered. The centre "
                              "orchestrates units, levels and order freely; no third-party "
                              "sign-off is outstanding for entry."),
            "l1_lane": "all six L1 units, 15 credits, all at level (s5.1 permits exceeding 14)",
            "barred_combinations": ("Each pupil banks each of the six skills at ONE level only "
                                    "(spec s6.5); the credit from the highest-level unit counts. "
                                    "The witness sheet's Level tick is the record."),
            "launch_room": ("The LAUNCH room runs the Entry 3, Level 1 and Level 2 routes "
                            "CONCURRENTLY - one mixed session, three demands, three levels of "
                            "evidence. The L2 route is staff-directed and appears in-deck behind "
                            "the Guidance toggle."),
            "lane_targets": ("SET, on the derived rate of 7 x 40-minute periods (4.667 h/wk) - MEASURED "
                             "band (1-7 periods, from BUILD) plus the OWNER RULING of 2026-08-22 "
                             "selecting seven; not a pure repo measurement, and not measured in "
                             "the GROW or LAUNCH rooms at all. "
                             "ALL THREE LANES TARGET THE FULL CERTIFICATE: Entry Level "
                             "Certificate (14 cr) - Level 1 Certificate (14 cr, claimed from "
                             "the six-unit 15) - Level 2 Certificate (15 cr). Award by W14, "
                             "Extended Award by W26, Certificate by W38 on every lane, each "
                             "milestone proven in the ledger rather than asserted. The "
                             "co-delivery claim is WITHDRAWN on all three lanes (was E3 7 h, "
                             "L1 2 h): at 4.667 h/wk the hours are real supervised time and "
                             "the six-unit ledgers close without it, leaving 37.3 h (E3), "
                             "42.3 h (L1) and 57.3 h (L2) of declared QA/consolidation."),
        },
    }
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    with open(OUT_JSON, "w") as f:
        json.dump(data, f, indent=1)
    write_xlsx(data)
    print("PROVEN and written:")
    for lane in ("E3", "L1", "L2"):
        L = lanes[lane]
        tot = {k: v / 60.0 for k, v in L["totals_min"].items()}
        print(f"  {lane}: units {tot} · co-delivered {L['co_min']/60.0} h · QA/unassigned {L['qa_min']/60.0} h")
    print(f"  physical year: {WEEKLY_MIN*WEEKS/60.0} h/lane at {WEEKLY_MIN/60.0} h/wk x {WEEKS} wks")
    print("\n  PER-ROOM REACHABILITY at the measured rates (unit-GLH test, the stricter one):")
    rr = data["room_reachability"]
    for room in ("Build", "Grow", "Launch"):
        c = rr[room]
        print(f"    {room}: floor (a) {c['a_h_per_week']} h/wk = {c['a_year_glh']} GLH/yr"
              f"  |  ceiling (a+b) {c['ab_h_per_week']} h/wk = {c['ab_year_glh']} GLH/yr")
        for lane in ("E3", "L1", "L2"):
            f = "".join("Y" if q["reachable_at_floor"] else "n" for q in c["levels"][lane])
            g = "".join("Y" if q["reachable_at_ceiling"] else "n" for q in c["levels"][lane])
            print(f"       {lane}  A/E/C at floor {f}   at ceiling {g}")
    print(f"  -> {OUT_JSON}\n  -> {OUT_XLSX}")

def write_xlsx(data):
    import openpyxl
    wb = openpyxl.Workbook()
    ws = wb.active; ws.title = "YearMap"
    head = ["Week", "Block", "Deck (live 12)", "Lane"] + [data["units"]["E3"][sk]["code"].replace("E3", "") + " (min)" for sk in SKILLS] + ["QA/unassigned (min)", "Co-delivered (min, unit)", "Physical (min)"]
    # use skill keys as neutral column names instead
    head = ["Week", "Block", "Deck (live 12)", "Lane", "Com", "DecMk", "LSk", "TmWk", "Th/CrTh", "Wellb", "QA", "Co-delivered", "Physical"]
    ws.append(head)
    blocks = {w: b for (b, a, z) in data["blocks"] for w in range(a, z + 1)}
    decks = {d["week"]: f'{d["suite"]} {d["deck"]}' for d in data["decks"]}
    for lane in ("E3", "L1", "L2"):
        rows = data["lanes"][lane]["rows"]; cos = data["lanes"][lane]["co"]
        for i in range(data["weeks"]):
            w = i + 1; r = rows[i]; c = cos[i]
            co_txt = "; ".join(f'{v} {k}' for k, v in c.items()) or ""
            ws.append([w, blocks[w], decks.get(w, ""), lane] +
                      [r.get(sk, 0) for sk in SKILLS] + [r.get("QA", 0), co_txt, sum(r.values())])
    ws2 = wb.create_sheet("UnitLedgers")
    ws2.append(["Lane", "Unit", "Credits", "Unit GLH (h)", "Ledger (h)", "Complete by week"])
    for lane in ("E3", "L1", "L2"):
        for sk in SKILLS:
            u = data["units"][lane][sk]; L = data["lanes"][lane]
            ws2.append([lane, u["code"], u["credits"], u["glh"], L["totals_min"][sk] / 60.0, L["complete_week"][sk]])
    ws3 = wb.create_sheet("Milestones")
    ws3.append(["Lane", "Qualification", "Credits", "Qual GLH", "Constituent unit GLH", "Milestone week"])
    for lane in ("E3", "L1", "L2"):
        for m in data["lanes"][lane]["milestones"]:
            ws3.append([lane, m["qual"], m["credits"], m["qual_glh"], m["unit_glh"], m["week"]])
    ws4 = wb.create_sheet("Sensitivity")
    ws4.append(["h per week", "Year physical GLH", "Lane", "Qualification", "Unit GLH needed", "Reachable", "Short by (h)"])
    for row in data["sensitivity"]:
        for lane in ("E3", "L1", "L2"):
            for q in row["lanes"][lane]:
                ws4.append([row["hpw"], row["year_glh"], lane, q["qual"], q["unit_glh_h"],
                            "YES" if q["ok"] else "NO", q["short_h"]])
    ws5 = wb.create_sheet("Method")
    ws5.append(["Live-deck GLH measurement method"]); ws5.append([data["deck_method"]])
    ws5.append([]); ws5.append(["L1 Certificate 14-of-15 choice"]); ws5.append([data["l1_cert_choice"]])
    wb.save(OUT_XLSX)

if __name__ == "__main__":
    main()
